---
title: "Curve"
author: "Youmin Chun"
date: "2026-09-13 00:00:01"
description: "미분기하학에서 다루는 곡선, 그리고 곡선과 관련된 여러 개념에 대해서 설명한다."
categories: 
  - Math > Differential Geometry
---

# Definition 1
**(i)** A map $\alpha: (a, b) \to \mathbb{R}^3$ is called a ***curve***.

**(ii)** A curve $\alpha: (a, b) \to \mathbb{R}^3$ is called a ***regular curve*** if $\alpha \in C^{\infty}$ and $\alpha'(t) \neq \mathbf{0}, \forall t \in (a, b)$.

**(iii)** For a curve $\alpha: (a, b) \to \mathbb{R}^3$, the vector $\alpha'(t_0)$ is called the ***velocity vector*** at $t = t_0$, and the map $\alpha'$ is called the ***velocity vector field***.

**(iv)** For a curve $\alpha: (a, b) \to \mathbb{R}^3$, the real number $\vert \alpha'(t_0) \vert$ is called the ***speed*** of $\alpha$ at $t = t_0$. If $\vert \alpha'(t) \vert = 1, \forall t \in (a, b)$, then $\alpha$ is called a ***unit speed curve***.

**(v)** For a regular curve $\alpha: (a, b) \to \mathbb{R}^3$, the map $T(t) = \frac{\alpha'(t)}{\vert \alpha'(t) \vert}$ is called the ***tangent vector field***.

**(vi)** For a regular curve $\alpha: (a, b) \to \mathbb{R}^3$, the set 

$$l = \{ \mathbf{w} \in \mathbb{R}^3 \mid \mathbf{w} = \alpha(t_0) + \lambda T(t_0), \lambda \in \mathbb{R} \}$$

is called the ***tangent line*** of $\alpha$ at $t = t_0$.

물리적인 직관을 가지고 있으면 정의를 받아들이기 더 쉬운데, 수학적으로는 곡선이라고 부르지만 물리학적으로는 어떤 입자가 이동하는 경로라고 봐도 무방하다. 때문에 그 도함수를 속도라고 부른다.

벡터 필드(vector field)라고 하면 곡선 위의 점 $\alpha(t)$를 시점으로 하는 벡터를 의미한다. 따라서 탄젠트 벡터 필드는 특정 시점 $t$에서의 곡선 위의 점 $\alpha(t)$에서 곡선에 접하는 접선 벡터이다.

한편 곡선을 다룰 때 어떤 기하학적인 대상, 다시 말해 $\mathbb{R}^3$의 점들을 모아놓은 집합으로 바라볼 수도 있지만, 위 정의와 같이 매개변수화된 벡터값 함수로 볼 수도 있다. 두 번째 관점이 우리가 주요하게 바라보는 관점인데, 이 경우 곡선을 표현하는 매개변수화는 하나로 유일하지 않다. 다시 말해 동일한 이미지를 갖는 곡선의 함수식이 여러 개가 존재할 수 있고, 이 중 어떤 함수는 정칙 곡선(regular curve)이 될 수도 있고 되지 않을 수도 있다. 함수가 정의된 식 자체에 문제가 있을 수도 있고, 정의역에 따라서도 여부가 달라진다. 이러한 사실들은 매개변수를 바꿔주는 재매개변수화(reparametrization)의 도입이 필요함을 시사한다.

# Definition 2
A ***reparametrization*** of a curve $\alpha : (a, b) \to \mathbb{R}^3$ is a bijective function $g: (c, d) \to (a, b)$ such that $g, g^{-1} \in C^{\infty}$.

# Theorem 1
Let $\alpha : (a, b) \to \mathbb{R}^3$ be a regular curve, and let $g: (c, d) \to (a, b)$ be a reparametrization. Set $\beta = \alpha \circ g$.

**(i)** $g'(s) \neq 0, \forall s \in (c, d)$

**(ii)** $\beta : (c,d) \to \mathbb{R}^3$ is a regular curve.

**(iii)** If $T$ is a tangent vector field of $\alpha$ at $t = t_0$ and $S$ is a tangent vector field of $\beta$ at $s_0 = g(t_0)$, then $S= \pm T$.

후술하겠지만 재매개변수화는 곡선의 이미지, 정칙성(regularity), 길이 등의 값들을 보존하고, 오직 곡선의 방향과 속도만을 바꿀 뿐이다. 단순하게 말해서 재매개변수화는 변수와 변수의 정의역을 바꾸는 역할을 하는데, 여기서 변수가 변하는 방향이 기존 변수와 동일하게 바뀔 수도 있고, 거꾸로 바뀔 수도 있다. 동일하게 바뀌면 $g$는 증가함수이고, 거꾸로 바뀌면 $g$는 감소함수이다.

한편 정의를 보면 재매개변수화 $g$는 항상 역함수 $g^{-1}$를 가지는데, $g^{-1}$ 또한 재매개변수화의 정의를 모두 만족함을 알 수 있다. 즉 재매개변수화의 역함수 또한 재매개변수화가 된다.

## Proof
**(i)** Let $t = g(s)$. Then

$$\begin{align*}
1 &= \frac{d}{ds}s \\
&= \frac{d}{ds}(g^{-1} \circ g)(s) \\
&= \frac{dg^{-1}}{dt}\Big|_{t=g(s)} \frac{dg}{ds},
\end{align*}$$

which implies that $g'(s) = \frac{dg}{ds} \neq 0$.

**(ii)** Note that

$$\begin{align*}
\beta'(s) &= (\alpha \circ g)'(s) \\
&= \alpha'(g(s)) \cdot g'(s).
\end{align*}$$

Since $\alpha$ is a regular curve, $\alpha'(t) \neq \mathbf{0}, \forall t \in (a, b)$. Also, by (i), $g'(s) \neq 0$. Thus, $\beta'(s) \neq \mathbf{0}, \forall s \in (c, d)$, which means that $\beta$ is regular.

**(iii)** By **(ii)**, $\beta$ is regular so that $S$ is well-defined. Note that

$$T = \frac{\alpha'(t_0)}{\| \alpha'(t_0) \|} \quad \text{and} \quad S = \frac{\beta'(s_0)}{\| \beta'(s_0) \|}.$$

Then we have

$$\begin{align*}
S &= \frac{\beta'(s_0)}{\| \beta'(s_0) \|} \\
&= \frac{\alpha'(g(s_0)) \cdot g'(s_0)}{\| \alpha'(g(s_0)) \cdot g'(s_0) \|} \\
&= \frac{\alpha'(t_0) \cdot g'(s_0)}{\| \alpha'(t_0) \| \cdot \vert g'(s_0) \vert} \\
&= \pm \frac{\alpha'(t_0)}{\| \alpha'(t_0) \|} \\
&= \pm T. \quad \blacksquare
\end{align*}$$

# Definition 3
Let $\gamma : (c, d) \to \mathbb{R}^3$ be a regular curve.

**(i)** A ***segment*** of $\gamma$ is a curve $\alpha : [a, b] \to \mathbb{R}^3$ such that $\alpha(t) = \gamma(t), \forall t \in [a, b]$

**(ii)** The ***length*** of a segment $\alpha: [a, b] \to \mathbb{R}^3$, denoted by $l_{[a, b]}(\alpha)$, is defined as
$$l_{[a, b]}(\alpha) = \int_a^b \| \alpha'(t) \| dt$$

**(iii)** The ***arc length*** along a regular curve $\alpha : (a, b) \to \mathbb{R}^3$ is defined as 

$$s = h(t) = \int_{t_0}^t \| \alpha'(u) \| du$$

where $t_0 \in (a, b)$. 

곡선을 정의할 때 정의역을 보면 모두 열린 구간인데, 곡선의 길이를 구하기 위해 적분을 하려면 정의역을 닫힌 구간으로 만들어줘야 할 필요성이 생기고, 세그먼트는 그러한 필요에 의해 정의된 개념이다. 한편 곡선의 길이를 어떤 고정된 값으로 구할 수도 있지만, 적분 구간을 변수 $t$로 두어서 길이 자체를 함수로 만들 수도 있는데, 아래 정리에서 볼 수 있듯이 그 자체로 재매개변수화가 된다.

# Theorem 2
**(i)** Let $\alpha: [a, b] \to \mathbb{R}^3$ be a segment of a regular curve $\gamma$, and let $g: [c, d] \to [a, b]$ be a reparametrization restricted to $[c, d]$. Set $\beta = \alpha \circ g$. Then $l_{[a, b]}(\alpha) = l_{[c, d]}(\beta)$.

**(ii)** The arc length $s = h(t)$ along a regular curve $\alpha : (a, b) \to \mathbb{R}^3$ is a reparametrization $h: (a,b) \to (c,d)$ for some interval $(c, d)$.

다시 말해 곡선의 길이는 재매개변수화에 대해서 불변이다. 당연할 것이, 길이라 하면 곡선 그 자체의 특징이므로 변수를 바꿨다고 달라질리 없다.

## Proof
**(i)** Let $t = g(s)$. Then we have

$$\begin{align*}
l_{[c, d]}(\beta) &= \int_c^d \| \beta'(s) \| ds \\
&= \int_c^d \| \alpha'(g(s)) \cdot g'(s) \| ds \\
&= \int_c^d \| \alpha'(t) \| \cdot \vert g'(s) \vert ds
\end{align*}$$

By Theorem 1 **(i)** and the definition of a reparametrization, $g'(s) > 0$ or $g'(s) < 0$ for all $s$ in $[c, d]$.

**Case 1:** $g'(s) > 0, \forall s \in [c, d]$. 

Then $a = g(c), b = g(d)$. Thus, we have

$$\begin{align*}
l_{[c, d]}(\beta) &= \int_c^d \| \alpha'(t) \| g'(s) ds \\
&= \int_a^b \| \alpha'(t) \| dt \\
&= l_{[a, b]}(\alpha).
\end{align*}$$

**Case 2:** $g'(s) < 0, \forall s \in [c, d]$. 

Then $b = g(c)$ and $a = g(d)$. Thus, we have

$$\begin{align*}
l_{[c, d]}(\beta) &= \int_c^d \| \alpha'(t) \| \cdot (-g'(s)) ds \\
&= -\int_b^a \| \alpha'(t) \| dt \\
&= \int_a^b \| \alpha'(t) \| dt \\
&= l_{[a, b]}(\alpha).
\end{align*}$$

In both cases, we have $l_{[a, b]}(\alpha) = l_{[c, d]}(\beta)$.

**(ii)** Note that

$$s = h(t) = \int_{t_0}^t \| \alpha'(u) \| du$$

for some $t_0 \in (a,b)$. By the fundamental theorem of calculus, we have $h'(t) = \| \alpha'(t) \|$, so that $h$ is increasing. Thus, $h$ is one-to-one and onto for some interval $(c, d)$. Since $\alpha$ is a regular curve, $h \in C^{\infty}$. By the inverse function theorem, $h^{-1} = g \in C^{\infty}$, and therefore $h: (a, b) \to (c,d)$ is a reparametrization. $\blacksquare$

# Definition 4
Let $h: (a,b) \to (c,d)$ be the arc length for a regular curve $\alpha : (a, b) \to \mathbb{R}^3$. The inverse function $g : (c, d) \to (a, b)$ of $h$, that is, $g = h^{-1}$, is called the ***arc length reparameterization***.

## Example
Let $\alpha(t) = \mathbf{u} + t\mathbf{v}$ for some vectors $\mathbf{u}, \mathbf{v} \in \mathbb{R}^3$ and $t \in [0, \infty)$. Then $\alpha'(t) = \mathbf{v}$, so

$$h(t) = \int_0^t \| \alpha'(t) \| dt = \| \mathbf{v}\|t.$$

By Theorem 2 **(ii)**, $h$ has an inverse function $t = h^{-1}(s)$. Note that $t = h^{-1}(s) = \frac{s}{\| \mathbf{v} \|}$. If we let $\beta = \alpha \circ h^{-1}$, then we have

$$\begin{align*}
\beta(s) &= (\alpha \circ h^{-1})(s) \\
&= \alpha(h^{-1}(s)) \\
&= \mathbf{u} + h^{-1}(s)\mathbf{v} \\
&= \mathbf{u} + s\frac{\mathbf{v}}{\| \mathbf{v} \|}.
\end{align*}$$

위 예시는 우리가 위와 같이 곡선의 길이로 재매개변수화를 해주는 이유를 적나라하게 보여준다. 이와 같이 재매개변수화를 하면 우리는 항상 곡선의 속도를 $1$로 맞춰줄 수가 있게 된다.

# Reference
- R. S. Millman and G. D. Parker, Elements of Differential Geometry, Prentice-Hall, 1977.