---
title: "Group Isomorphism"
author: "Youmin Chun"
date: "2026-07-31"
categories: 
  - Math > Abstract Algebra > Group Theory
---

## Definition
Let $G$ and $G'$ be groups. 

**(i)** A map $\phi: G \to G'$ is a ***homomorphism*** if 

$$\phi(ab) = \phi(a)\phi(b), \forall a, b \in G.$$

Let $\phi : G \to G'$ be a homomorphism.

**(ii)** If $\phi$ is injective, then $\phi$ is called a ***monomorphism***.

**(iii)** If $\phi$ is surjective, then $\phi$ is called an ***epimorphism***.

**(iv)** If $\phi$ is bijective, then $\phi$ is called an ***isomorphism***. If an isomorphism $\phi : S \to T$ of $S$ with $T$ exists, then $S$ and $T$ are said to be ***isomorphic*** groups and we denote by $S \cong T$ (or $S \simeq T$).

**(v)** If $\phi$ is an isomorphism and $G = G'$, then $\phi$ is called an ***automorphism***.

## Theorem
- Let $\phi: G \to G'$ be a group homomorphism. Then

**(i)** $\phi(e_G) = e_{G'}$.

**(ii)** For each $a \in G$, $\phi(a^{-1}) = (\phi(a))^{-1}$

**(iii)** $H \le G \implies \phi(H) \le G'$

**(iv)** $K \le G' \implies \phi^{-1}(K) \le G$

## Example 1
**(i)** $\langle \mathbb{R}, + \rangle \cong \langle \mathbb{R}^+, \cdot \rangle$.

$\big[ (\because)$ Define $\phi : \langle \mathbb{R}, + \rangle \to \langle \mathbb{R}^+, \cdot \rangle$ by

$$\phi(r) = 2^r, \forall r \in \mathbb{R}$$

Then $\phi$ is clearly bijective. Let $a, b \in \mathbb{R}$. Since

$$ \begin{align*}
\phi(a + b) &= 2^{a + b} \\
&= 2^a \cdot 2^b \\
&= \phi(a) \cdot \phi(b),
\end{align*}$$

$\phi$ is an isomorphism.$\big]$

**(ii)** $\langle \mathbb{Z}, + \rangle \cong \langle 2\mathbb{Z}, + \rangle$.

$\big[(\because)$ Define $\phi : \mathbb{Z} \to 2\mathbb{Z}$ by

$$\phi(a) = 2a, \forall a \in \mathbb{Z}.$$

Then $\phi$ is clearly bijective. Let $a, b \in \mathbb{Z}$. Since

$$ \begin{align*}
\phi(a + b) &= 2(a + b) \\
&= 2a + 2b \\
&= \phi(a) + \phi(b),
\end{align*}$$

$\phi$ is an isomorphism.$\big]$

**(iii)** $\langle \mathbb{Q}, + \rangle \not\cong \langle \mathbb{R}, + \rangle$. 

$\big[(\because)$ Since $\vert \mathbb{Q} \vert = \aleph_0 \lneq 2^{\aleph_0} = \vert \mathbb{R} \vert$, there does not exist a bijection between $\mathbb{Q}$ and $\mathbb{R}$.$\big]$

**(iv)** $\langle \mathbb{Q}, + \rangle \not\cong \langle \mathbb{Z}, + \rangle$.

$\big[(\because)$ Suppose that there is an isomorphism $\phi$ of $\langle \mathbb{Q}, + \rangle$ with $\langle \mathbb{Z}, + \rangle$. Note that $\phi(q) = 1$ for some $q \in \mathbb{Q}$. Then

$$\begin{align*}
\phi(q) &= \phi \left( \frac{q}{2} + \frac{q}{2} \right) \\
&= \phi \left( \frac{q}{2} \right) + \phi \left( \frac{q}{2} \right) \\
&= 2 \phi \left( \frac{q}{2} \right) \\
&= 1.
\end{align*}$$ 

Note that $\phi \left( \frac{q}{2} \right) \in \mathbb{Z}$ but there is no $x \in \mathbb{Z}$ such that $2x = 1$. $\bigotimes$ Thus $\phi$ is not an isomorphism.$\big]$

**(v)** $\langle \mathbb{C}, \cdot \rangle \not\cong \langle \mathbb{R}, \cdot \rangle$.

$\big[(\because)$ Suppose that there is an isomorphism $\phi$ of $\langle \mathbb{C}, \cdot \rangle$ with $\langle \mathbb{R}, \cdot \rangle$. Note that $\phi(z^2) = -1$ for some $z \in \mathbb{C}$. Then

$$\begin{align*}
\phi(z^2) &= \phi(z \cdot z) \\
&= \phi(z) \cdot \phi(z) \\
&= (\phi(z))^2 \\
&= -1.
\end{align*}$$ 

Note that $(\phi(z))^2 = -1$ has no solution in $\mathbb{R}$. $\bigotimes$ Thus $\phi$ is not an isomorphism.$\big]$

**(vi)** $\langle \mathbb{R}^{2 \times 2}, \cdot \rangle \not\cong \langle \mathbb{R}, \cdot \rangle$.

$\big[(\because)$ Suppose that there is an isomorphism $\phi$ of $\langle \mathbb{R}^{2 \times 2}, \cdot \rangle$ with $\langle \mathbb{R}, \cdot \rangle$. Let $A, B \in \mathbb{R}^{2 \times 2}$. Then

$$\begin{align*}
\phi(A \cdot B) &= \phi(A) \cdot \phi(B) \\
&= \phi(B) \cdot \phi(A) \\
&= \phi(B \cdot A),
\end{align*}$$

which means that $A \cdot B = B \cdot A$ for all $A, B \in \mathbb{R}^{2 \times 2}$. $\bigotimes$ Thus $\phi$ is not an isomorphism.$\big]$ 

## Example 2
Let $G, G'$ be groups.

**(i)** The map $\phi:G \to G'$ defined by 

$$\phi(g) = e_{G'}, \forall g \in G$$

is a homomorphism. We call such a map $\phi$ the ***trivial homomorphism***.

**(ii)** The identity map $\mathrm{id}_G:G \to G$ defined by 

$$\mathrm{id}_G(g) = g, \forall g \in G$$

is an automorphism. 

**(iii)** Let $F = \mathbb{R}^{\mathbb{R}}$. Then clearly $\langle F, + \rangle$ is a group. For each $c \in \mathbb{R}$, define $\phi_c: F \to \mathbb{R}$ by 

$$\phi_c(f) = f(c), \forall f \in F$$

Then $\phi_c$ is a homomorphism. 

$\big[(\because)$ Let $f, g \in F$. Then 

$$\begin{align*}
\phi_c(f+g) &= (f+g)(c) \\
&= f(c) + g(c) \\
&= \phi_c(f) + \phi_c(g),
\end{align*}$$

so $\phi_c$ is a homomorphism.$\big]$

Let $\alpha \in \mathbb{R}$. Define the function $f_{\alpha}: \mathbb{R} to \mathbb{R}$ by

$$f_{\alpha}(x) = \alpha, \forall x \in \mathbb{R}.$$ 

Then $f_{\alpha} \in F$ and $\phi_c(f_{\alpha}) = f_{\alpha}(c) = \alpha$. Thus $\phi_c$ is surjective, so that it is an epimorphism. 

**(iv)** Let $A \in \mathbb{R}^{m \times n}$. Define $\phi: \mathbb{R}^n \to \mathbb{R}^m$ by 

$$\phi(x) = Ax, \forall x \in \mathbb{R}^n.$$

Then $\phi$ is a homomorphism. 

**(v)** Let $n \ge 2$. Define $\phi: \mathbb{Z} \to \mathbb{Z}_n$ by 

$$\phi(a) = a \pmod{n}, \forall a \in \mathbb{Z}.$$

Then $\phi$ is an epimorphism. 

$\big[(\because)$ Let $a, b \in \mathbb{Z}$. Then $a \equiv r_1 \pmod{n}$ and $b \equiv r_2 \pmod{n}$ for some $r_1, r_2 \in \{ 0, 1, ..., n-1 \}$. Note that $a+b \equiv r_1 + r_2 \pmod{n}$. Then

$$\begin{align*}
\phi(a+b) &\equiv r_1 + r_2 \pmod{n} \\
&= \phi(a) + \phi(b),
\end{align*}$$

so $\phi$ is a homomorphism. 

Let $r \in \{ 0, 1, ..., n-2 \}$. Then clearly $\phi(r) = r$, so $\phi$ is surjective, hence it is an epimorphism.$\big]$

**(vi)** Define $\phi: \mathbb{C} \setminus \{ 0 \} \to \mathbb{R}^+$ by 

$$\phi(z) = \vert z \vert, \forall z \in \mathbb{C} \setminus \{ 0 \}.$$

Clearly, $\phi$ is a homomorphism. Note that $\mathrm{Ker}(\phi)$ is a unit circle in the complex plane.

**(vii)** Defined $\phi: S_n \to \mathbb{Z}_2$ by 

$$\phi(\sigma) = \begin{cases} 
0 & \text{if } \sigma \text{ is even} \\
1 & \text{if } \sigma \text{ is odd}
\end{cases}$$

for all $\sigma \in S_n$. Then clearly $\phi$ is an epimorphism.

**(viii)** Let $G = \displaystyle \prod_{i=1}^n G_i$ be a direct product of groups. For each $k \in \{ 1, ..., n \}$, define $\iota_k : G_k \to G$ by 

$$\iota_k(g_k) = (e_1, \cdots, e_{k-1}, g_k, e_{k+1}, \cdots, e_n), \forall g_k \in G_k.$$

Then $\iota_k$ is a monomorphism, but not epimorphism in general. The map $\iota_k$ is called the ***natural injection***.

Furthermore, For each $k \in \{ 1, ..., n \}$, define $\pi_k : G \to G_k$ by 

$$\pi_k(g_1, \cdots, g_n) = g_k, \forall (g_1, \cdots, g_n) \in G.$$

Then $\pi_k$ is an epimorphism, but not monomorphism in general. The map $\pi_k$ is called the ***canonical epimorphism***, or the ***projection map***.

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.