---
title: "Pagerank"
author: "Youmin Chun"
date: "2026-08-19"
description: "네트워크 이론에서의 페이지랭크(PageRank)에 대해서 소개한다."
categories: 
  - Math > Graph Theory > Network Analysis
---

# Pagerank
고유벡터 중심성(eigenvector centrality)은 유향그래프에 적용할 경우 상식적으로 작동하지 않는 문제가 있었고, 이를 해결하기 위해 개선된 개념이 카츠 중심성(Katz centrality)이었다. 그러나 카츠 중심성 또한 완벽한 개념은 아니다. 

> **Katz Centrality**
> $$x_i = \alpha \sum_j A_{ij} x_j + \beta$$

카츠 중심성은 어떤 노드의 주변 노드의 중심성이 높으면 그 노드의 중심성 또한 함께 높아지도록 정의되었다. 그런데 이러한 세팅이 항상 합리적일까?

예를 들어 어쩌다가 네이버 홈 화면에 내 블로그의 어떤 글이 게재되었다고 하자. 이를 네트워크 식으로 표현하면 네이버라는 노드에서 출발해서 내 블로그라는 노드로 도착하는 링크, 즉 에지가 연결되었다고 볼 수 있다. 한편 자명하게 네이버는 많은 사람들이 드나드는 페이지이므로 매우 높은 카츠 중심성을 가지고 있을텐데, 그러면 내 블로그 또한 네이버의 중심성의 값만큼 더해진 중심성을 가지게 될 것이다. 그러나 상식적으로 네이버만큼 내 블로그의 중심성이 높다고 볼 수는 없다. 네이버는 내 블로그 말고도 수많은 페이지와 링크가 연결되어 있을 것이기에, 이 또한 감안해서 보정된 값이 중심성에 추가되어야 할 것이다. 이러한 컨셉을 반영해서 카츠 중심성을 개선한 개념이 ***페이지랭크(pagerank)***다.

## Definition
Let $G$ be a directed network, and let $\mathbf{A}$ be the adjacency matrix of $G$. The ***pagerank*** $x_i$ of a vertex $i$ is defined as

$$x_i = \alpha \sum_j A_{ij} \frac{x_j}{d^-_j} + \beta$$

where $\alpha, \beta$ are nonnegative constants, and $d^-_j$ is the out-degree of the vertex $j$. If a vertex $j$ has zero out-degree, i.e., $d^-_j = 0$, then we set $d^-_j = 1$ for convenience. In matrix form,

$$\mathbf{x} = \alpha \mathbf{A} \mathbf{D}^{-1} \mathbf{x} + \beta \mathbf{1}$$

where $\mathbf{D}$ is the diagonal matrix with $D_{ii} = \max \{ d^-_i, 1 \}$.

위에서 설명한 예시를 생각했을 때, $x_j$에 out-degree $d^-_j$를 나눠주도록 정의하는 방식이 합리적이다. 만약 밖으로 내보내는 링크가 없는 노드일 경우, 즉 $d^- = 0$일 경우 페이지랭크에 한해서 $0$이 아닌 $1$로 간주하도록 한다. 어차피 이 경우 $A_{ij} = 0$이므로 계산에 영향을 미치지 않는다. 이러한 컨벤션에 맞춰서 차수행렬 $\mathbf{D}$ 또한 조금 다르게 정의해준다.

한편 상수 $\alpha, \beta$는 카츠 중심성과 동일한 의미로 사용된다. 즉 $\alpha$는 가중치를 의미하며, $\beta$는 모든 노드들에 부여되는 기본값을 의미한다. 마찬가지로 위 식을 정리하면 다음과 같다.

$$\begin{align*}
&\mathbf{x} = \alpha \mathbf{A} \mathbf{D}^{-1} \mathbf{x} + \beta \mathbf{1} \\
\implies &\mathbf{x} - \alpha \mathbf{A} \mathbf{D}^{-1} \mathbf{x} = \beta \mathbf{1} \\
\implies &(\mathbf{I} - \alpha \mathbf{A} \mathbf{D}^{-1}) \mathbf{x} = \beta \mathbf{1} \\
\implies &\mathbf{x} = \beta(\mathbf{I} - \alpha \mathbf{A} \mathbf{D}^{-1})^{-1} \mathbf{1} \\
\implies &\mathbf{x} = \beta \mathbf{D} (\mathbf{D} - \alpha \mathbf{A})^{-1} \mathbf{1} 
\end{align*}$$

간단하게 $\beta = 1$로 두면 최종적으로 $\mathbf{x} = \mathbf{D} (\mathbf{D} - \alpha \mathbf{A})^{-1} \mathbf{1}$을 얻는다. 카츠 중심성과 동일하게 역행렬이 존재하도록 적당한 $\alpha$의 값을 선택해야 하고, 이는 행렬 $\mathbf{A} \mathbf{D}^{-1}$의 스펙트럴 래디어스의 값에 따라 결정된다. 

## Extension
기본값인 $\beta$를 각 노드마다 다르게 부여하고 싶으면 다음과 같이 정의할 수도 있다.

$$\begin{align*}
\mathbf{x} &= \alpha \mathbf{A} \mathbf{D}^{-1} \mathbf{x} + \pmb{\beta} \\
x_i &= \alpha \sum_j A_{ij} \frac{x_j}{d^-_j} + \beta_i
\end{align*}$$

# Reference
- Newman, M.E.J. (2010). Networks: An Introduction. Oxford University Press.