---
title: "Ideal Gas"
author: "Youmin Chun"
date: "2026-07-08"
categories: 
  - Physics > Thermodynamics
---

# 1. Ideal Gas
## 1.1. Definition
- ***Ideal gas*** is a system of non-interacting, point-like and zero size particles.

현실적인 입자라면 입자들 사이에 작용하는 여러 가지 종류의 인력이 있지만, 이상 기체는 그러한 인력들이 없다고 가정하고 기체 입자들이 오로지 충돌로만 상호작용한다고 가정한다. 때문에 완벽하게 무작위적으로 탄성 충돌을 하는 입자들로 간주한다.

## 1.2. Ideal Gas Equation
$$PV = nk_BT$$

$P, V, T, n$는 각각 이상 기체의 압력, 부피, 온도, 몰수를 의미하며 $k_B$는 볼츠만 상수이다. 이상 기체에 대해서 위 방정식이 항상 성립함을 수식적으로 입증할 수 있고, 실험적으로도 알려져 있으니 받아들이고 사용하도록 하자.

## 1.3. Variables
- Variables which scale with the system size, like $V$ and $U$, are called ***extensive variables.*** Those which are independent of system size, like $P$ and $T$, are called ***intensive variables.***

부피를 생각해보면 분명히 기체 입자들이 $1 m^3$ 부피에 들어있는 상황과 $0.5 m^3$ 부피에 들어있는 상황은 명백히 다르다. 그러나 압력의 경우 기체 입자 전체 시스템이 가하는 압력이나 절반의 기체 입자들이 가하는 압력이나 동일하다고 간주할 수 있다. 즉 기체에 대해서 생각할 수 있는 여러 물리량들이 있지만 시스템의 사이즈에 따라서 위와 같이 두 종류의 물리량들로 구분할 수 있다. 

# 2. Thermodynamic Limit
열역학을 다루는 많은 경우에서 기체는 항상 이상 기체를 가정한다. 이에 더해 기체 입자의 개수가 무한히 많다는 수학적인 가정을 하게 되는데, 이를 thermodynamic limit이라고 부른다. 구체적으로는 다음과 같이 가정한다.

$$N \to \infty \text{ and } V \to \infty \text{ keeping } \frac{N}{V} = \text{const.}$$

예컨대 '압력'이라는 물리량을 생각해보자. 어떤 박스에 갇혀 있는 기체 입자들에 대해서 압력을 측정한다고 하면, '면적 당 작용하는 힘'이라는 정의에 따라 수많은 입자들이 힘을 가하는 면적과 그 힘을 알아야 한다. 이때 기체 입자들이 무한히 많다고 가정하면 박스의 모든 면에 힘을 가한다고 단순하게 생각할 수 있고, 실제 기체 입자도 아보가드로 수 만큼 들어있을 것이기에 그렇게 큰 문제가 되진 않는다. 따라서 논의를 좀 더 단순하게 만들기 위해 이러한 가정은 필수적이라고 할 수 있겠다. 



# Reference
- Blundell, Stephen J. , Blundell, Katherine M. (2009). Concepts in Thermal Physics (2nd ed.). Oxford University Press.