---
title: "Degree"
author: "Youmin Chun"
date: "2026-08-05"
categories: 
  - Math > Graph Theory
---

## Definition 1
Let $G$ be an undirected graph with $n$ vertices and $m$ edges, and let $v_i \in V(G)$.

**(i)** The ***neighborhood*** $N_G(v_i)$ of $v_i$ is the set $N_G(v_i) = \{ u \in V(G) \mid u \sim v_i \}$.

**(ii)** The ***degree*** $\deg_G(v_i)$ of $v_i$ is the size of the neighborhood of $v_i$, that is, $\deg_G(v_i) = \vert N_G(v_i) \vert$.

**(iii)** The ***mean degree*** of a vertex in $G$ is defined as

$$c := \frac{1}{n} \sum_{i=1}^n \deg_G(v_i).$$

**(iv)** The ***density*** of $G$ is 

$$\rho(G) = \frac{m}{\binom{n}{2}} = \frac{2m}{n(n-1)} = \frac{c}{n-1}.$$

**(v)** A graph $G$ is called ***regular*** if $\deg_G(v_i) = c$ for all $v_i \in V(G)$.

## Remark 1
Let $G$ be an undirected graph with $n$ vertices and $m$ edges, and let $A$ be the adjacency matrix of $G$. Let $v_i \in V(G)$.

**(i)** Note that

$$\deg_G(v_i) = \sum_{j=1}^n A_{ij}.$$

**(ii)** The ***handshaking lemma*** holds;

$$2m = \sum_{i=1}^n \deg_G(v_i) = \sum_{i, j} A_{ij}$$

**(iii)** By the handshaking lemma, we have 
$$c = \frac{2m}{n}.$$ 

**(iv)** Note that $0 \le \rho(G) \le 1.$ If a graph is sufficiently large, then $\rho(G)$ can be approximated as $\rho \approx \frac{c}{n}.$ 

If $\displaystyle 0 < \lim_{n \to \infty} \rho(G) < \infty$, then $G$ is said to be ***dense***. If $\displaystyle \lim_{n \to \infty} \rho(G) = 0$, then $G$ is said to be ***sparse***. 

## Definition 2
Let $G$ be a directed graph with $n$ vertices and $m$ edges, and let $v_i \in V(G)$. 

**(i)** The ***indegree*** of a vertex $v_i$ is $\mathrm{deg}^+(v_i) = \vert \{ u \in V(G) \mid u \to v_i \}$ and the ***outdegree*** of a vertex $v_i$ is $\mathrm{deg}^-(v_i) = \vert \{ u \in V(G) \mid v_i \to u \}$.

**(ii)** The ***mean indegree*** of a vertex in $G$ is defined as

$$c_{in} := \frac{1}{n} \sum_{i=1}^n \mathrm{deg}^+(v_i)$$

and the ***mean outdegree*** is defined as

$$c_{out} := \frac{1}{n} \sum_{i=1}^n \mathrm{deg}^-(v_i).$$

## Remark 2
Let $G$ be a directed graph with $n$ vertices and $m$ edges, and let $A$ be the adjacency matrix of $G$. Let $v_i \in V(G)$.

**(i)** Note that

$$\mathrm{deg}^+(v_i) = \sum_{j=1}^n A_{ji} \quad \text{and} \quad \mathrm{deg}^-(v_i) = \sum_{j=1}^n A_{ij}.$$

**(ii)** The ***handshaking lemma*** holds;

$$m = \sum_{i=1}^n \mathrm{deg}^+(v_i) = \sum_{i=1}^n \mathrm{deg}^-(v_i) = \sum_{i, j} A_{ij}.$$

**(iii)** By the handshaking lemma, we have

$$c_{in} = \frac{m}{n} = c_{out}.$$

# Reference
- Matousek, J., & Nesetril, J. (2008). Invitation to Discrete Mathematics. Oxford University Press.
- Newman, M.E.J. (2010). Networks: An Introduction. Oxford University Press.