---
title: "Product Topology"
author: "Youmin Chun"
date: "2026-07-10"
categories: 
  - Math > Topology
---

## Theorem 1
Let $(X, \mathscr{T})$ and $(Y, \mathscr{T}')$ be topological spaces. 

**(i)** The collection 

$$\mathscr{B} = \{ U \times V \mid U \in \mathscr{T}, V \in \mathscr{T}' \}$$

of subsets of $X \times Y$ is a basis on $X \times Y$. The topology generated by $\mathscr{B}$ is called the ***product topology*** on $X \times Y$.

**(ii)** If $\mathscr{B}$ is a basis for $\mathscr{T}$ and $\mathcal{C}$ is a basis for $\mathscr{T}'$, then 

$$\mathcal{D} = \{ B \times C \mid B \in \mathscr{B}, C \in \mathcal{C} \}$$

is also a basis for the product topology on $X \times Y$.

### Proof
**(i)** Let $(x, y) \in X \times Y$. Since $X \times Y \in \mathscr{B}$, the firsit condition is satisfied.

If $(x, y) \in U_1 \times V_1 \cap U_2 \times V_2$ for $U_1, U_2 \in \mathscr{T}$ and $V_1, V_2 \in \mathscr{T}'$, then we have 

$$(x, y) \in U_1 \times V_1 \cap U_2 \times V_2 = (U_1 \cap U_2) \times (V_1 \cap V_2) \in \mathscr{B}$$

since $\mathscr{T}$ and $\mathscr{T}'$ are topologies. Thus $\mathscr{B}$ is a basis.

**(ii)** We will use [Theorem 3](../Basis_Topology/index.qmd#sec-theorem-3). Let $\mathscr{T}$ be the product topology. For each $W \in \mathscr{T}$ and each $(x, y) \in W$, $\exists U \in \mathscr{T}, V \in \mathscr{T}'$ such that $(x, y) \in U \times V \subset W$ by (i). Since $\mathscr{B}$ and $\mathcal{C}$ are bases, $\exists B \in \mathscr{B}, C \in \mathcal{C}$ such that 

$$(x, y) \in B \times C \subset U \times V \subset W,$$

which means that $\mathcal{D}$ is a basis. $\blacksquare$

## Remark
Let $(X, \mathscr{T})$ and $(Y, \mathscr{T}')$ be topological spaces, and let $\pi_1: X \times Y \to X$ and $\pi_2: X \times Y \to Y$ be the projection maps. If $U \in \mathscr{T}$ and $V \in \mathscr{T}'$, then we have 

$$\begin{align*}
\pi_1^{-1}(U) &= U \times Y \\
\pi_2^{-1}(V) &= X \times V,
\end{align*}$$

so that 

$$\pi_1^{-1}(U) \cap \pi_2^{-1}(V) = (U \times Y) \cap (X \times V) = U \times V.$$

## Theorem 2
Let $(X, \mathscr{T})$ and $(Y, \mathscr{T}')$ be topological spaces. The collection

$$\mathscr{S} = \{ \pi_1^{-1}(U) \mid U \in \mathscr{T} \} \cup \{ \pi_2^{-1}(V) \mid V \in \mathscr{T}' \}$$

is a subbasis for the product topology on $X \times Y$.

### Proof
Note that $\pi^{-1}_1(X) = X \times Y$. Since $X \in \mathscr{T}$, $\pi_1^{-1}(X) \in \mathscr{S}$. Thus $X \times Y = \pi_1^{-1}(X) \subset \bigcup \mathscr{S}$. Since each $\pi_1^{-1}(U)$ and $\pi_2^{-1}(V)$ are subsets of $X \times Y$, their union $\bigcup \mathscr{S}$ is also a subset of $X \times Y$, that is, $\bigcup \mathscr{S} \subset X \times Y$. Thus $\bigcup \mathscr{S} = X \times Y$, which means that $\mathscr{S}$ is a subbasis on $X \times Y$.

Let $\mathscr{T}'$ be the topology generated by $\mathscr{S}$ and let $\mathscr{T}$ be the product topology. Note that each element of $\mathscr{S}$ is a basis element of $\mathscr{T}$. Since every basis element of $\mathscr{T}$ is also an open set of $\mathscr{T}$, we have $\mathscr{S} \subset \mathscr{T}$. By definition of topology, any finite intersections of elements of $\mathscr{S}$ are also open sets of $\mathscr{T}$. By definition of topology, any unions of open sets of $\mathscr{T}$ are also open sets of $\mathscr{T}$. Since every open set of $\mathscr{T}'$ is a union of a finite intersection of elements of $\mathscr{S}$, every open set of $\mathscr{T}'$ is also an open set of $\mathscr{T}$. Thus, $\mathscr{T}' \subset \mathscr{T}$. 

Let $U \times V$ be a basis element of $\mathscr{T}$. Since 

$$U \times V = \pi^{-1}_1(U) \cap \pi^{-1}_2(V),$$

we have $\mathscr{T} \subset \mathscr{T}'$. Thus we have $\mathscr{T} = \mathscr{T}'$. $\blacksquare$ 

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.
