---
title: "Temperature(온도)"
author: "Young Jeong Lee"
date: "2026-08-01"
description: "천문학에서 이용되는 온도에 대해 소개하는 글이다."
categories: 
  - Astronomy > Radio Astronomy
---

# 1. Temperature 

- 열역학적 평형 상태에 있는 흑체 복사의 스펙트럼 분포는 다음과 같이 쓸 수 있다:

$$
B_\nu(T)=\frac{2h\nu^3}{c^2}\frac{1}{e^{h\nu/kT}-1}, \qquad B_\lambda(T)=\frac{2hc^2}{\lambda^5}\frac{1}{e^{hc/k\lambda T}-1} \tag{1.1}
$$

- 식 (1.1)을 주파수($\nu$) 혹은 파장($\lambda$)에 대해서 적분하면 흑체의 total brightness를 얻을 수 있다:

$$
B(T)=\frac{2h}{c^2}\int_0^{\infty}\frac{\nu^3}{e^{h\nu/kT}-1}d\nu \tag{1.2}
$$

- $x={h\nu} / {kT}$ 로 두고 식 (1.2)를 적분하면 다음과 같은 결과를 얻는다: 

$$
B(T)=\sigma T^4,\qquad  
\sigma=\frac{2\pi^4 k^4}{15c^2 h^3}=1.8047\times10^{-5}\mathrm{erg\ cm^{-2}s^{-1} \ K^{-4}}  
\qquad \tag{1.3}
$$

- 흑체 복사 스펙트럼의 최댓값은 **빈 변위 법칙(Wien's displacement law)**으로 나타낼 수 있다:

$$
\frac{\nu_{\max}}{\mathrm{GHz}} = 58.789 \left(\frac{T}{\mathrm{K}}\right), \qquad \left(\frac{\lambda_{\max}}{\mathrm{cm}}\right)\left(\frac{T}{\mathrm{K}}\right) = 0.28978 \tag{1.4}
$$

## 1.1. Brightness Temperature 

- 레일리-진스 법칙의 중요한 특징 중 하나는 복사를 방출하는 흑체의 밝기와 열역학적 온도가 비례한다는 것이다. 이로부터 어떤 extended source의 brightness를 온도로 정의할 수 있는데, 이를 **brightness temperature**라고 한다:
  - 다르게 표현하면 $I_\nu = B_\nu(T_b)$ 를 이용하는 온도로 플랑크 함수에서 특정한 한 점을 통해서 얻는 온도이다. 

$$
T_b = \frac{c^2}{2k\nu^2} I_\nu = \frac{\lambda^2}{2k} I_\nu \tag{1.5}
$$

- 식 (1.5)를 $S_{\nu}$ 에 대해 바꿔쓰면 다음과 같다:

$$
S_\nu = \frac{2k\nu^2}{c^2} T_b \Delta \Omega \tag{1.6}
$$


- 가우시안 source라면, 식 (1.6)을 다음과 같이 쓸 수 있다:

$$
\left[\frac{S_\nu}{\mathrm{Jy}}\right] = 2.65 T_b \left[\frac{\theta}{\mathrm{arcminutes}}\right]^2 \left[\frac{\lambda}{\mathrm{cm}}\right]^{-2}  \tag{1.7}
$$

- $S_{\nu}$ 와 source의 크기를 알 수 있다면 source의 brightness temperature를 결정할 수 있다. 
- 만약 복사가 흑체에 의해 방출되고 $h\nu \ll kT$ 인 경우, $T_b$ 는 주파수에 무관한 source의 열역학적 온도를 준다. 반면, 다른 과정이 이 복사의 방출에 관여한다면 $T_b$ 가 주파수에 의존하게 된다. 

<div style="height: 3rem;"></div>

- 망원경의 민감도(sensitivity) 문제로 인해 high intensity, 즉, high brightness temperature를 갖는 천체가 적절한 연구 대상이 된다.
- 간섭계로 검출 가능한 최소 brightness temperature $T^{\text{min}}_b$ 는 플럭스 밀도 $S_\nu$, baseline 길이 $b$, 그리고 볼츠만 상수 $k$ 에 따라 다음과 같이 결정된다:

$$
T_{\text{b}}^{\min} = \frac{2}{\pi k} b^2 S_{\nu} \tag{1.8}
$$

- 보통 $T^{\text{min}}_b$ 은 $10^6 \sim 10^8 {\rm K}$ 의 범위를 갖는다. 
- VLBI 이미지를 통해서 어떠한 구조의 brightness temperature는 다음과 같은 관계식을 통해서 계산된다:

$$
T_{\text{b}} = 1.22 \cdot 10^{12} \frac{S_{\nu}(1+z)}{d^{2}\nu^{2}} \tag{1.9}
$$

- $d$: 각지름(angular diameter)

<div style="height: 3rem;"></div>

- **Radiation temperature**는 복사장을 온도 단위로 표현하는 일반적인 용어로 플랑크 법칙의 $h\nu \ll kT$ 에서 유도된다. 그 결과, 형태는 식 (1.5)와 동일하다.
- 식 (1.5)를 주파수 한계 값에 대한 표현으로 나타내면 다음과 같다:

$$
\frac{\nu}{\mathrm{GHz}} \ll 20.84 \left(\frac{T}{\mathrm{K}}\right) \tag{1.10}
$$

- 식 (1.10)을 통해서 mm, sub-mm 파장대의 낮은 온도에 대한 경우를 제외하면 모든 열적 전파원에 대해서 식 (1.5)를 이용할 수 있다는 사실을 알 수 있다. 

<div style="height: 3rem;"></div>

- **Intrinsic brightness temperature**: 제트 플라즈마와 함께 움직이는 계에서 측정한 제트 자체의 물리적인 brightness temperature
- **equipartition brightness temperature**: 방출 입자의 에너지 밀도와 자기장의 에너지 밀도가 비슷할 때, 얻어지는 싱크로트론 source가 가질 것으로 예상되는 brightness temperature

<style>
h2 {
border-bottom: none !important;
}
</style>
