---
title: "Generating Set"
author: "Youmin Chun"
date: "2026-09:02 00:00:02"
description: "순환군을 일반화한 개념인 Generating Set에 대해서 설명한다."
categories: 
  - Math > Abstract Algebra > Group Theory
---

## Definition
Let $G$ be a group and let $S = \{ a_i \mid i \in I \}$ be a subset of $G$. 

**(i)** The smallest subgroup of $G$ containing $S$ is called the ***subgroup generated by $S$***, and is denoted by $\langle S \rangle$ or $\langle \{ a_i \mid i \in I \} \rangle$.

**(ii)** If $\langle S \rangle = G$, then we say that ***$S$ generates $G$***, and the $a_i$'s are called ***generators*** of $G$. (Or $G$ is ***generated by*** $S$)

**(iii)** If there exists $a_1, ..., a_n \in G$ such that $G = \langle \{ a_1, ..., a_n \} \rangle$, then $G$ is said to be ***finitely generated***. In this case, we write $G = \langle a_1, ..., a_n \rangle$.

## Theorem 1
Let $G$ be a group and let $S \subset G$. Then 

$$\langle S \rangle = \bigcap_{S \subset H \le G} H.$$

### Proof
Let $X$ be a subgroup of $G$ containing $S$. Since $X \in \{ H \mid S \subset H \le G \}$, we have 

$$\bigcap_{S \subset H \le G} H \subset X,$$

which means that $\bigcap_{S \subset H \le G} H$ is the smallest subgroup of $G$ containing $S$. Thus

$$\langle S \rangle = \bigcap_{S \subset H \le G} H. \blacksquare$$

## Theorem 2
Let $G$ be a group and let $S = \{ a_i \mid i \in I \} \subset G$. Then the subgroup of $G$ generated by $S$ consists of finite products of integral powers of the $a_i$, where powers of a fixed $a_i$ may occur several times in the product.

### Proof
Let $K$ denote the set of all finite products of integral powers of the $a_i$. Since the subgroup of $G$ generated by $S$ is $\bigcap_{S \subset H \le G} H$ and each $H$ is a subgroup of $G$, containing $S$, for any element $a$ in $K$, $a \in H$ for all $H$ such that $S \subset H \le G$. Thus $K \subset \bigcap_{S \subset H \le G} H$. 

Let $a, b \in K$. Since each $a$ and $b$ is the product of finitely many integral powers of the $a_i$'s, so is $b^{-1}$. Thus $ab^{-1}$ is also a product of finitely many integral powers of the $a_i$'s, so that $ab^{-1} \in K$. Hence $K \le G$. 

Since $\bigcap_{S \subset H \le G} H$ is the smallest subgroup of $G$ containing $S$, we have $\bigcap_{S \subset H \le G} H \subset K$. Therefore, $\langle S \rangle = \bigcap_{S \subset H \le G} H = K$. $\blacksquare$

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.