---
title: "Morera Theorem"
author: "Youmin Chun"
date: "2026-09-01 00:00:10"
description: "복소해석학의 모레라 정리와 코시 부등식에 대해서 소개한다."
categories: 
  - Math > Complex Analysis
---

## Morera Theorem
Let $f$ be continuous on a domain $D$. If 

$$\int_C f(z) \, dz = 0$$

for every closed contour $C$ in $D$, then $f$ is analytic throughout $D$.

[Cauchy-Goursat Theorem]이 $f$가 analytic일 때 모든 closed contour에 대해서 적분이 $0$인 것을 보인 것과 반대로, 모레라 정리는 적분이 $0$일 때 $f$가 analytic임을 보인다. 

### Proof
By [Theorem 1](../Antiderivative/index.qmd#sec-theorem-1), $f$ has an antiderivative $F$ in $D$, which means that there exists an analytic function $F$ such that $F'(z) = f(z), \forall z \in D$. Since $f$ is a derivative of $F$, $f$ is analytic by [Corollary 2](../Cauchy_Integral_Formula/index.qmd#sec-corollary-2). $\blacksquare$

## Cauchy's Inequality
Suppose that a function $f$ is analytic inside and on a positively oriented circle $C_R$, centered at $z_0$ and with radius $R$. If we define $\displaystyle M_R := \max _ {z \in C_R} \vert f(z) \vert$, then 

$$\left\vert f^{(n)}(z_0) \right\vert \le \frac{n! M_R}{R^n}, \forall n \in \mathbb{N}.$$

This inequality is called ***Cauchy's inequailty***.

### Proof
By Cauchy integral formula, we have 

$$f^{(n)}(z_0) = \frac{n!}{2\pi i} \int _ {C_R} \frac{f(z)}{(z - z_0)^{n+1}} \, dz.$$

Since $\vert z - z_0 \vert = R$ for all $z$ in $C_R$, we have that by $ML$-lemma,

$$\begin{align*}
\left\vert f^{(n)}(z_0) \right\vert &= \left \vert \frac{n!}{2\pi i} \int _ {C_R} \frac{f(z)}{(z - z_0)^{n+1}} \, dz \right \vert \\
& \le \frac{n!}{2 \pi} \frac{M_R}{R^{n+1}} \cdot 2 \pi R \\
&= \frac{n! M_R}{R^n}. \quad \blacksquare
\end{align*}$$

# Reference
- Brown, James Ward, & Churchill, Ruel V. (2017). Complex Variables and Applications (9th ed.). McGraw-Hill.