---
title: "Homomorphism"
author: "Youmin Chun"
date: "2026-06-25 00:00:02"
description: "대수학의 준동형사상(Homomorphism)과 여러가지 사상들에 대해서 소개한다."
categories: 
  - Math > Abstract Algebra > Binary Algebraic Structure
---

## Definition
- Let $\langle S, \ast \rangle$ and $\langle T, \ast' \rangle$ be binary algebraic structures. 

**(i)** A ***homomorphism*** of $S$ with $T$ is a function $\phi : S \to T$ such that 

$$\phi(x \ast y) = \phi(x) \ast' \phi(y), \forall x, y \in S.$$

**(ii)** If $\phi$ is injective, then $\phi$ is called a ***monomorphism***.

**(iii)** If $\phi$ is surjective, then $\phi$ is called an ***epimorphism***.

**(iv)** If $\phi$ is bijective, then $\phi$ is called an ***isomorphism***. If an isomorphism $\phi : S \to T$ of $S$ with $T$ exists, then $S$ and $T$ are said to be ***isomorphic*** binary structures and we denote by $S \cong T$ (or $S \simeq T$).

**(v)** If $\phi$ is an isomorphism and $S = T$, then $\phi$ is called an ***automorphism***.

## Theorem
Let $\phi : \langle S, \ast \rangle \to \langle T, \ast' \rangle$ be an epimorphism of $S$ with $T$. If $e$ is the identity element of $\langle S, \ast \rangle$, then $\phi(e)$ is the identity element of $\langle T, \ast' \rangle$.

### Proof
Let $t \in T$. Then $\exists s \in S$ such that $\phi(s) = t$ because $\phi$ is surjective. Thus we have

$$\begin{align*}
\phi(e) \ast' t & = \phi(e) \ast' \phi(s) \\
&= \phi(e \ast s) \\
&= \phi(s) \\
&= t,
\end{align*}$$ 

and similarly $t \ast' \phi(e) = t$. Hence $\phi(e)$ is the identity element of $\langle T, \ast' \rangle$. $\blacksquare$

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.