---
title: "Frenet-Serret Frame"
author: "Youmin Chun"
date: "2026-09-19 00:00:02"
description: "프레네-세레 도구와 좌표계에 대해서 설명한다."
categories: 
  - Math > Differential Geometry > Curve Theory
---

# Definition
Let $\alpha: (a, b) \to \mathbb{R}^3$ be a regular unit speed curve.

**(i)** The ***tangent vector field*** is the map $T(s) = \alpha'(s)$.

**(ii)** The ***curvature*** of $\alpha$ is the map $\kappa(s) = \| T'(s) \|$.

**(iii)** The ***normal vector field*** is the map $N(s) = \frac{T'(s)}{\kappa(s)}$.

**(iv)** The ***binormal vector field*** is the map $B(s) = T(s) \times N(s)$.

**(v)** The ***torsion*** of $\alpha$ is the map $\tau(s) = - \langle B'(s), N(s) \rangle$.

**(vi)** The ***Frenet-Serret appratus*** of $\alpha$ is the set $\{ T(s), N(s), B(s), \kappa(s), \tau(s) \}$.

$T$는 말 그대로 각 점에서의 곡선에 접하는 접선 벡터다. 한편 곡률 $\kappa$는 $T$의 도함수의 크기로 정의되는데, 곡선이 **많이 굽어있을수록** $T$는 급격하게 변하고, 다시 말해 $T'$의 크기는 커진다. 반면 곡선이 **많이 굽어있지 않고 평평할수록** $T$는 별로 변하지 않고, 다시 말해 $T'$의 크기는 작아진다. 이렇듯 곡률, 즉 곡선이 굽어있는 정도는 접선벡터의 변화량의 크기로 정의하는 것이 직관적이라는 사실을 알 수 있다.

다음과 같이 $xy$ 평면에 속하는 곡선 $\alpha(s) = (x(s), y(s)), \forall s \in (a,b)$을 고려하자. 만약 $\alpha$가 단위 속력 곡선이라면 $\{ x'(s) \}^2 + \{ y'(s) \}^2 = 1$이 성립하고, 따라서 $\alpha(s) = (\cos(\theta(s)), \sin(\theta(s)))$과 같이 표현할 수 있게 된다. 이때 곡률을 계산해보면

$$\begin{align*}
\kappa(s) &= \| T'(s) \| \\
&= \| (-\sin(\theta(s)) \cdot \theta'(s), \cos(\theta(s)) \cdot \theta'(s)) \| \\
&= \vert \theta'(s) \|
\end{align*}$$

을 얻는다. 즉 위와 같이 곡률을 정의하는 방법이 직관적임과 더불어 합리적이라는 사실을 알 수 있다.

한편 $T$은 곡선에 접하는 방향을 가지는 벡터인 반면 $T'$은 $T$에 수직한 방향을 갖는다. 이해를 위해 평면 상에서 위로 볼록한 이차함수와 같은 꼴로 곡선이 놓여 있다고 생각해보자. 이때 접선 벡터 $T$가 변하는 방향을 생각하면 곡선의 "안쪽"으로 변하는 사실을 알 수 있다. 다시 말해 $T$가 변하는 방향은 늘 곡선의 "안쪽"을 가리키는 것이고, 때문에 $T'$은 $T$와 수직하되 곡선의 안쪽을 향하는 방향을 가진다. 이때 노말 벡터 $N$은 $T'$의 방향을 가지는 단위 벡터로 정의된다.

좀 더 물리적인 센스로 생각해본다면, $N$은 일종의 "외력"의 방향을 가리킨다고 볼 수 있다. 곡선을 어떤 입자가 공간 상에서 이동해나가는 궤적, 혹은 경로라고 볼 때, 만약 입자가 어떠한 외력도 받지 않는다면 현재의 관성을 유지한 채 운동 상태를 유지할 것이고, 어떤 초기속도를 가지고 있었다면 그 초기속도를 따라 직선 궤도를 그리며 나아갈 것이다. 이는 다시 말해 전혀 굽어있지 않은 상태를 의미한다. 반면 입자가 어떤 외력을 받고 있다면 궤도가 외력이 가하는 방향으로 휘게 될 것이고, 이는 $T'$이 곡선의 안쪽 방향을 가진다는 사실과 일맥상통한다.

그리고 $T$와 $N$의 외적으로 만들어지는 바이노말 벡터 $B$는 $T$와 $N$이 만드는 평면에 수직한 벡터인데, 물리적으로는 어떤 순간에 입자가 회전하는 회전축 방향을 가리킨다고 이해할 수 있다. 마지막으로 토션은 $B$의 $N$방향의 변화율이라고 볼 수 있는데, 직관적으로는 **곡선이 꼬여있는 정도**를 의미한다고 받아들일 수 있다. $\mathbb{R}^3$에서 $z$축을 향하여 일정하게 올라가는 나선(helix)을 생각해보자. $N$은 항상 $z$축을 향할 것이고, $B$는 시간이 지날수록 이리저리 흔들리며 뱅글뱅글 도는 방향으로 변하게 될 것이다. 직관적으로 $B'$의 $N$방향 성분을 측정하면 외력이 작용함에 따라 회전축이 얼마나 흔들리는지 측량할 수 있다. 곡선이 더 극단적으로 꼬여있을수록 그 변화율은 더욱 커질 것이고, 곡선이 흔들리지 않고 안정적으로 놓여있을수록 그 변화율은 더욱 적어진다. 만약 곡선이 한 평면 안에 완전히 속해 있다면, 다시 말해 입자가 일정한 회전축을 가진 채 운동한다면 곡선은 전혀 꼬여있지 않다고 이해할 수 있고, 실제로도 토션은 항상 $0$의 값을 갖는다.

한편, 이렇게 정의한 세 개의 벡터 $T(s), N(s), B(s)$는 각각 단위벡터이면서 서로 직교한다. 또한 전체 공간이 $\mathbb{R}^3$이므로 집합 $\{ T(s), N(s), B(s) \}$는 $\mathbb{R}^3$의 기저를 이룬다. 다시 말해 곡선 위의 점 $s$이 주어질 때마다 그 점에 의존하는 $\mathbb{R}^3$의 정규직교기저가 주어지는 것이다. 

## Example
**(i)** Consider the curve $\alpha(s) = \left(r \cos \frac{s}{r}, r \sin \frac{s}{r}, 0 \right), \forall s \in (a,b)$. Then $\alpha$ is a unit speed curve, and we have

$$\begin{align*}
\kappa(s) &= \| T'(s) \| \\
&= \left\| \left( -\frac{1}{r} \sin \frac{s}{r}, \frac{1}{r} \cos \frac{s}{r}, 0 \right) \right\| \\
&= \sqrt{\left( -\frac{1}{r} \sin \frac{s}{r} \right)^2 + \left( \frac{1}{r} \cos \frac{s}{r} \right)^2} \\
&= \sqrt{\frac{1}{r^2} \left( \sin^2 \frac{s}{r} + \cos^2 \frac{s}{r} \right)} \\
&= \frac{1}{r}. \end{align*}$$

Furthermore, note that

$$\begin{align*}
N(s) &= \left( -\cos \frac{s}{r}, -\sin \frac{s}{r}, 0 \right), \\
B(s) &= T(s) \times N(s) \\
&= \begin{vmatrix} \mathbf{i} & \mathbf{j} & \mathbf{k} \\ -\sin \frac{s}{r} & \cos \frac{s}{r} & 0 \\ -\cos \frac{s}{r} & -\sin \frac{s}{r} & 0 \end{vmatrix} \\
&= \mathbf{k} = (0, 0, 1). 
\end{align*}$$

Thus, we have

$$\begin{align*}
\tau(s) &= - \langle B'(s), N(s) \rangle \\
&= 0.
\end{align*}$$

즉 원의 경우 곡률은 모든 점에 대해서 반지름의 역수인 $\frac{1}{r}$로 일정하고, 한 평면에 완전히 속해 있으므로 토션은 $0$임을 알 수 있다.

## Properties
Let $\alpha(s)$ be a unit speed curve.

**(i)** For each $s$ such that $\kappa(s) \neq 0$, the set $\{ T(s), N(s), B(s) \}$ is an orthonormal basis of $\mathbb{R}^3$.

**(ii)** If $\kappa \equiv 0$ on an interval $[a, b]$, then the curve segment $\alpha: [a, b] \to \mathbb{R}^3$ is a straight line.

**(iii)** Suppose that $\kappa \not \equiv 0$. If $\tau \equiv 0$, then $\alpha$ is a plane curve.

### Proof
**(i)** By construction, we have that $\| T(s) \| = 1 = \| N(s) \|$, $B(s) \perp T(s)$ and $B(s) \perp N(s)$. Note that

$$\begin{align*}
1 &= \| T(s) \|^2 \\
&= \langle T(s), T(s) \rangle \\
\implies 0 &= \frac{d}{ds} \langle T(s), T(s) \rangle \\
&= 2 \langle T(s), T'(s) \rangle \\
\implies 0 &= \langle T(s), N(s) \rangle,
\end{align*}$$

so $T(s) \perp N(s)$.

Note that $\| B(s) \| = \| T(s) \| \| N(s) \| = 1$ since $B(s)$ is defined as $T(s) \times N(s)$. Thus $\{ T(s), N(s), B(s) \}$ is an orthonormal basis of $\mathbb{R}^3$.

**(ii)** Since $\kappa(s) = \| T'(s) \| = 0$, we have $T'(s) = 0$, so $T(s) = c$ for some constant vector $c$. By the fundamental theorem of calculus, we have

$$\begin{align*}
\alpha(s) &= \int_a^s \alpha'(u) du + \alpha(a) \\
&= \int_a^s T(u) du + \alpha(a) \\
&= c(s-a) + \alpha(a),
\end{align*}$$

which is the equation of a straight line.

**(iii)** Suppose that $\tau \equiv 0$. By the Frenet-Serret formula, $B' \equiv 0$, so $B$ is a constant vector. We claim that $\langle \alpha(s) - \alpha(s_0), B(s) \rangle = 0$ for any $s, s_0$.

$$\begin{align*}
\frac{d}{ds} \langle \alpha(s) - \alpha(s_0), B(s) \rangle &= \langle \alpha'(s), B(s) \rangle + \langle \alpha(s) - \alpha(s_0), B'(s) \rangle \\
&= \langle T(s), B(s) \rangle + \langle \alpha(s) - \alpha(s_0), 0 \rangle \\
&= 0,
\end{align*}$$

so we have $\langle \alpha(s) - \alpha(s_0), B(s) \rangle = c$ for some constant $c$. Taking $s = s_0$, we obtain $c = 0$. Thus, $\langle \alpha(s) - \alpha(s_0), B(s) \rangle = 0$, which means that $\alpha(s)$ lies in the plane through $\alpha(s_0)$ and perpendicular to $B(s)$. $\blacksquare$

# Frenet-Serret Formula
Let $\alpha(s)$ be a unit speed curve with $\kappa \not \equiv 0$, and let $\{ T(s), N(s), B(s), \kappa(s), \tau(s) \}$ be a Frenet-Serret appartus of $\alpha$ at $s$. Then we have:

**(i)** $T'(s) = \kappa(s) N(s)$

**(ii)** $N'(s) = -\kappa(s) T(s) + \tau(s) B(s)$

**(iii)** $B'(s) = -\tau(s) N(s)$

In matrix form,

$$\begin{bmatrix}
T' \\
N' \\
B'
\end{bmatrix} = \begin{bmatrix}
0 & \kappa & 0 \\
-\kappa & 0 & \tau \\
0 & -\tau & 0
\end{bmatrix} \begin{bmatrix}
T \\
N \\
B
\end{bmatrix}.$$

$B'$을 잘 보면 오직 $N$에만 의존하는 걸 알 수 있는데, 다시 말해 바이노말 벡터는 $T$나 그 자신 $B$ 방향으로 변하지 않고 오직 $N$ 방향으로만 변한다는 것이다. 또한 그 비례 상수가 토션으로 주어지는데, 토션의 정의 자체가 $B'$의 $N$ 방향 변화량으로 정의되었기 때문에 자연스럽게 이해할 수 있다. 뒤집어서 말하면, 토션이 $0$이면 $B$는 변하지 않고, 이는 주어진 커브가 어떤 한 평면에 완전히 속하게 됨을 알 수 있다.

## Proof
Note that each vector $v$ in $\mathbb{R}^3$ can be expressed as:

$$v = \langle v, T \rangle T + \langle v, N \rangle N + \langle v, B \rangle B.$$

**(i)** By definition of the normal vector $N(s) = \frac{T'(s)}{\kappa(s)}$, we have $T'(s) = \kappa(s) N(s)$.

**(ii)** Note that 

1. $\langle N', N \rangle = 0$.

$\big[ (\because)$

$$\begin{align*}
1 &= \langle N, N \rangle \\
\implies 0 &= \frac{d}{ds} \langle N, N \rangle \\
&= \langle N', N \rangle + \langle N, N' \rangle \\
&= 2 \langle N', N \rangle \\
\implies \langle N', N \rangle &= 0.\big]
\end{align*}$$

2. $\langle N', T \rangle = - \kappa$

$\big[ (\because)$ 

$$\begin{align*}
\frac{d}{ds} \langle N, T \rangle &= \langle N', T \rangle + \langle N, T' \rangle \\
&= \langle N', T \rangle + \langle N, \kappa N \rangle \\
&= \langle N', T \rangle + \kappa \| N \|^2 \\
&= \langle N', T \rangle + \kappa \\
\implies \langle N', T \rangle &= - \kappa.\big]
\end{align*}$$

Since $N' = \langle N', T \rangle T + \langle N', N \rangle N + \langle N', B \rangle B = -\kappa T + \tau B$, we have $N' = -\kappa T + \tau B$.

**(iii)** Note that

1. $\langle B', B \rangle = 0$.

$\big[ (\because)$

$$\begin{align*}
1 &= \langle B, B \rangle \\
\implies 0 &= \frac{d}{ds} \langle B, B \rangle \\
&= \langle B', B \rangle + \langle B, B' \rangle \\
&= 2 \langle B', B \rangle \\
\implies \langle B', B \rangle &= 0.\big]
\end{align*}$$

2. $\langle B', T \rangle = 0$.

$\big[ (\because)$ 

$$\begin{align*}
\frac{d}{ds} \langle B, T \rangle &= \langle B', T \rangle + \langle B, T' \rangle \\
&= \langle B', T \rangle + \langle B, \kappa N \rangle \\
&= \langle B', T \rangle + \kappa \langle B, N \rangle \\
&= \langle B', T \rangle + \kappa \cdot 0 \\
&= \langle B', T \rangle \\
\implies \langle B', T \rangle &= 0.\big]
\end{align*}$$

Since $B' = \langle B', T \rangle T + \langle B', N \rangle N + \langle B', B \rangle B = \tau N$, we have $B' = \tau N$. $\blacksquare$

## Corollary
Let $\alpha(s)$ be a unit speed curve with $\kappa \not \equiv 0$. TFAE.

**(i)** $\alpha$ is a plane curve.

**(ii)** $B$ is a constant vector.

**(iii)** $\tau \equiv 0$.

### Proof


# Reference
- R. S. Millman and G. D. Parker, Elements of Differential Geometry, Prentice-Hall, 1977.