---
title: "Residue"
author: "Youmin Chun"
date: "2026-09-10 00:00:02"
description: "복소해석학에서 유수(Residue)에 대해서 소개한다."
categories: 
  - Math > Complex Analysis
---

# Definitions 1
Suppose that a complex function $f$ has an isolated singular point $z_0$. Then there exists $R > 0$ such that $f$ is analytic in $0 < \vert z - z_0 \vert < R$. By Laurent Series, $f$ can be expressed as

$$\begin{align*}
f(z) &= \sum_{n = 0}^\infty a_n (z - z_0)^n + \sum_{n = 1}^\infty \frac{b_n}{(z-z_0)^n} \\
&= \cdots + \frac{b_{2}}{(z-z_0)^{2}} + \frac{b_{1}}{(z-z_0)^{1}} + a_0 + a_1 (z - z_0) + a_2 (z - z_0)^2 + \cdots
\end{align*}$$

where 

$$\begin{align*}
a_n &= \frac{1}{2\pi i} \int_C \frac{f(z)}{(z-z_0)^{n+1}} dz, \quad (n = 0, 1, 2, \dots) \\
b_n &= \frac{1}{2\pi i} \int_C \frac{f(z)}{(z-z_0)^{-n+1}} dz \quad (n = 1, 2, 3, \dots)
\end{align*}$$

and $C$ is any positively oriented simple closed contour around $z_0$ that lies in $0 < \vert z - z_0 \vert < R$.

The ***residue*** of $f$ at $z_0$ is the coefficient of $\frac{1}{z-z_0}$, that is,

$$b_1 = \frac{1}{2\pi i} \int_C f(z) dz.$$

We shall denote it by $b_1 = \displaystyle \operatorname*{Res}_{z = z_0} f(z)$.

함수 $f$가 $z_0$에서 고립특이점을 갖는다면 위 정의에 의해

$$\int_C f(z) dz = 2\pi i \operatorname*{Res}_{z = z_0} f(z)$$

가 성립한다. 다시 말해 함수의 선적분 값을 구하기 위해서 고립특이점에서의 유수(Residue)의 값만 알면 된다는 뜻이기도 하다. 유수는 정의상 고립특이점에서의 함수의 로랑 급수(Laurent Series)에서 $\frac{1}{z-z_0}$의 계수로 주어진다. 따라서 함수가 직접 적분하기 복잡한 경우 로랑 급수를 전개하는 것으로 적분값을 대신 구할 수 있게 된다.

# Cauchy's Residue Theorem
Let $C$ be a simple closed contour in the counterclockwise direction. If a function $f$ is analytic inside and on $C$ except for a finite number of isolated singular points $z_1, z_2, \dots, z_n$ inside $C$, then

$$\int_C f(z) dz = 2\pi i \sum_{k = 1}^n \operatorname*{Res}_{z = z_k} f(z)$$

## Proof
Let each point $z_k$ be the center of a positively oriented circle $C_k$ which is small enough so that they are interior to $C$ and do not intersect each other. Then the circles $C_k$ and the simple closed contour $C$ form the boundary of a closed region throughout which $f$ is analytic and whose interior is a multiply connected domain consisiting of the points inside $C$ and exterior to each $C_k$. Thus, by the principle of deformation of paths, we have

$$\int_C f(z) dz = \sum_{k=1}^n \int_{C_k} f(z) dz.$$

Since $f$ is analytic inside and on each $C_k$ except at $z_k$, we have

$$\int_{C_k} f(z) dz = 2\pi i \operatorname*{Res}_{z = z_k} f(z) \quad (k = 1, 2, \dots, n).$$ 

Therefore, 

$$\int_C f(z) dz = 2\pi i \sum_{k = 1}^n \operatorname*{Res}_{z = z_k} f(z). \blacksquare$$

이처럼 각 유수의 값들만 알면 완벽하게 함수의 적분값을 구할 수 있다. 그런데 왜 하필 유수는 로랑 급수에서 $\frac{1}{z-z_0}$의 계수인 $b_1$일까? 다른 계수들과는 달리 $b_1$은 어디가 특별해서 이처럼 중요한 결과가 생기는 걸까?

위에서 증명한 코시 유수 정리를 다른 방법으로 설명해보자. 각 $C_k$에서 함수 $f$를 로랑 급수로 표현해서 적분하면 다음과 같다.

$$\int_{C_k} f(z) dz = \int_{C_k} \sum_{n=0}^\infty a_n^{(k)} (z - z_k)^n dz + \int_{C_k} \sum_{n=1}^\infty \frac{b_n^{(k)}}{(z - z_k)^n} dz$$

이때 우변의 첫번째 항은 복소공간 전체에서 해석적인 함수이고, 따라서 코시-구르사 정리에 의해 적분값은 $0$이 된다. 즉,

$$\int_{C_k} f(z) dz = \sum_{n=1}^\infty b_n^{(k)} \int_{C_k} \frac{1}{(z - z_k)^n} dz$$

이다. 이때 코시 적분 공식에 의해

$$\int_{C_k} \frac{1}{(z - z_k)^n} dz = \begin{cases}
0, & (n \neq 1) \\
2\pi i, & (n = 1)
\end{cases}$$

이 성립한다. 여기서 계수 $b_1$만 살아남게 되기 때문에 적분값을 결정하는 유수로 $b_1$을 정의하는 것이다. 따라서 전체 선적분의 값은 각 유수들의 합에 $2\pi i$를 곱한 값으로 주어진다.

## Example 1
**(i)** Let $C: \vert z \vert = 1$, and let $\displaystyle f(z) = \frac{e^z-1}{z^4}$. Since $f$ is analytic in $\mathbb{C} \setminus \{ 0 \}$, $z = 0$ is an isolated singular point. By Cauchy's Residue Theorem,

$$\int_C f(z) dz = 2\pi i \operatorname*{Res}_{z = 0} f(z).$$

Note that $\displaystyle e^z = \sum_{n=0}^\infty \frac{z^n}{n!}$. Then we have 

$$\begin{align*}
f(z) &= \frac{e^z-1}{z^4} \\
&= \frac{1}{z^4} \sum_{n=1}^\infty \frac{z^n}{n!} \\
&= \sum_{n=1}^\infty \frac{z^{n-4}}{n!}
\end{align*}$$

Thus, the coefficient of $\frac{1}{z}$ is $\frac{1}{3!} = \frac{1}{6}$, and therefore

$$\int_C f(z) dz = 2\pi i \cdot \frac{1}{6} = \frac{\pi i}{3}.$$

**(ii)** Let $C: \vert z \vert = 1$, and let $\displaystyle f(z) = \cosh\left( \frac{1}{z^2} \right)$. Since $f$ is analytic in $\mathbb{C} \setminus \{ 0 \}$, $z = 0$ is an isolated singular point. By Cauchy's Residue Theorem,

$$\int_C f(z) dz = 2\pi i \operatorname*{Res}_{z = 0} f(z).$$

Note that $\displaystyle \cosh(z) = \sum_{n=0}^\infty \frac{z^{2n}}{(2n)!}$. Then we have 

$$\cosh \left( \frac{1}{z^2} \right) = \sum_{n=0}^\infty \frac{1}{n!} \frac{1}{(z^2)^n} = \sum_{n=0}^\infty \frac{1}{n!} \frac{1}{z^{2n}}$$

where $0 < \vert z \vert < \infty$. Thus, the coefficient of $\frac{1}{z}$ is $0$, and therefore

$$\int_C f(z) dz = 2\pi i \cdot 0 = 0.$$

**(iii)** Let $C: \vert z-2 \vert = 1$, and let $\displaystyle f(z) = \frac{1}{z(z-2)^5}$. Then $z=2$ is an isolated singular point inside of $C$. By Cauchy's Residue Theorem,

$$\int_C f(z) dz = 2\pi i \operatorname*{Res}_{z = 2} f(z).$$

Note that

$$\begin{align*}
\frac{1}{z} &= \frac{1}{2 + (z-2)} \\
&= \frac{1}{2} \frac{1}{1 + \frac{z-2}{2}} \\
&= \frac{1}{2} \sum_{n=0}^\infty \left(- \frac{z-2}{2} \right)^n
\end{align*}$$

where $0 < \vert z-2 \vert < 2$.

Then we have

$$\begin{align*}
f(z) &= \frac{1}{z(z-2)^5} \\
&= \frac{1}{(z-2)^5} \frac{1}{z} \\
&= \frac{1}{(z-2)^5} \sum_{n=0}^\infty \frac{(-1)^n}{2^{n+1}} (z-2)^n \\
&= \sum_{n=0}^\infty \frac{(-1)^n}{2^{n+1}} (z-2)^{n-5}
\end{align*}$$

where $0 < \vert z-2 \vert < 2$. Thus, the coefficient of $\frac{1}{z}$ is $\frac{(-1)^4}{2^5} = \frac{1}{32}$, and therefore

$$\int_C f(z) dz = 2\pi i \cdot \frac{1}{32} = \frac{\pi i}{16}$$

**(iv)** Let $C : \vert z \vert = 2$, and let $\displaystyle f(z) = \frac{4z-5}{z(z-1)}$. Since $f$ is analytic in $\mathbb{C} \setminus \{ 0, 1 \}$, $z = 0$ and $z = 1$ are isolated singular points inside of $C$. By Cauchy's Residue Theorem,

$$\int_C f(z) dz = 2\pi i \left( \operatorname*{Res}_{z = 0} f(z) + \operatorname*{Res}_{z = 1} f(z) \right)$$

Note that

$$\begin{align*}
\frac{4z-5}{z(z-1)} &= \frac{4z-5}{z} \cdot \frac{-1}{1-z} \\
&= \left( 4 - \frac{5}{z} \right) \left( - \sum_{n=0}^\infty z^n \right) \\
&= \sum_{n=0}^\infty -4 z^n + \sum_{n=0}^\infty 5z^{n-1}
\end{align*}$$

where $0 < \vert z \vert < 1$. Thus, the coefficient of $\frac{1}{z}$ is $5$, so $\displaystyle \operatorname*{Res}_{z = 0} f(z) = 5$. On the other hand,

$$\begin{align*}
\frac{4z-5}{z(z-1)} &= \frac{4z - 4 - 1}{z-1} \cdot \frac{1}{1 + (z-1)} \\
&= \left( 4 - \frac{1}{z-1} \right) \sum_{n=0}^\infty (-(z-1))^n \\
&= \sum_{n=0}^\infty 4 (-(z-1))^n - \sum_{n=0}^\infty (-(z-1))^{n-1}
\end{align*}$$

where $0 < \vert z - 1 \vert < 1$. Thus, the coefficient of $\frac{1}{z}$ is $-1$, so $\displaystyle \operatorname*{Res}_{z = 1} f(z) = -1$.

Therefore,

$$\int_C f(z) dz = 2\pi i (5 + (-1)) = 8\pi i$$

이와 같이 함수 $f$의 선적분을 유수를 이용해서 계산하려면 고립특이점 $z_0$ 주변에 대해서 함수의 로랑 급수를 전개해야 하고, 그 급수에서 $\frac{1}{z-z_0}$의 계수를 계산해주면 된다. 로랑 급수를 전개하는 과정에서 위와 같은 대수적인 조작들이 많이 필요하니 연습을 통해 익혀두도록 하자.

# Definition 2
Suppose that a function $f$ is analytic throughout $\mathbb{C}$ except for a finite number of singular points interior to a positively oriented simple closed contour $C$. Then $f$ is analytic throughout the region $R_1 < \vert z \vert < \infty$ for some $R_1 > 0$, that is, $f$ has an isolated singular point at infinity. Let $C_0$ be the circle $\vert z \vert = R_0$, oriented in the clockwise direction, where $R_0 > R_1$. The ***residue of $f$ at infinity*** is defined by means of the equation

$$\int_{C_0} f(z) dz = 2 \pi i \operatorname*{Res}_{z = \infty} f(z)$$

Since $f$ is analytic throughout the closed region bounded by $C_0$ and $C$, we have

$$\int_C f(z) dz = \int_{-C_0} f(z) dz = - \int_{C_0} f(z) dz = - 2 \pi i \operatorname*{Res}_{z = \infty} f(z)$$

by the principle of deformation of path, so

$$\int_C f(z) dz = -2 \pi i \operatorname*{Res}_{z = \infty} f(z)$$

반시계 방향의 곡선인 $C_0$을 따라 걸어갈 때 왼쪽에 무한히 뻗어나가는 평면이 위치한다. 즉, $z = \infty$는 $C_0$의 내부에 있는 점이라고 간주할 수 있고, $f$는 해석함수이므로 $z = \infty$는 고립특이점이다. 따라서 무한대에서도 유수를 정의할 수 있고, 이 값을 통해 우리는 $C$ 내부의 특이점들의 값을 일일이 계산하지 않고도 무한대에서의 유수 하나로 선적분을 계산할 수 있다.

# Theorem 2
If a function $f$ is analytic throughout $\mathbb{C}$ except for a finite number of singular points interior to a positively oriented simple closed contour $C$, then

$$\int_C f(z) dz = 2 \pi i \operatorname*{Res}_{z = \infty} \left[ \frac{1}{z^2} f \left( \frac{1}{z} \right) \right] $$

## Proof
Let $R_1$ be a positive number such that $f$ is analytic throughout the region $R_1 < \vert z \vert < \infty$, and let $C_0$ be the circle $\vert z \vert = R_0$, oriented in the clockwise direction, where $R_0 > R_1$. Note that $f$ can be represented by a Laurent series:

$$f(z) = \sum_{n= -\infty}^{\infty} c_n z^n$$

for $R_1 < \vert z \vert < \infty$, where

$$c_n = \frac{1}{2\pi i} \int_{-C_0} \frac{f(z)}{z^{n+1}} dz, \forall n \in \mathbb{Z}.$$

Then we obtain

$$\begin{align*}
\frac{1}{z^2}f\left( \frac{1}{z} \right) &= \sum_{n=-\infty}^\infty \frac{c_n}{z^{n+2}} \\
&= \sum_{n=-\infty}^\infty \frac{c_{n-2}}{z^n}
\end{align*}$$

where $\displaystyle 0 < \vert z \vert < \frac{1}{R_1}$. Thus, we have

$$\operatorname*{Res}_{z=0} \left[ \frac{1}{z^2} f\left( \frac{1}{z} \right) \right] = c_{-1} = \frac{1}{2\pi i} \int_{-C_0} f(z) dz = \operatorname*{Res}_{z=\infty} f(z). \blacksquare$$

## Example 2

# Theorem 3
Let $z_0$ be an isolated singular point of a function $f$. TFAE.

**(i)** $z_0$ is a pole of order $m$ of $f$.

**(ii)** $f(z)$ can be written in the form

$$f(z) = \frac{\phi(z)}{(z-z_0)^m}$$

where $\phi(z)$ is analytic and nonzero at $z_0$.

Moreover, if statements **(i)** and **(ii)** are true, then

$$\operatorname*{Res}_{z=z_0}f(z) = \frac{\phi^{(m-1)}(z_0)}{(m-1)!}.$$

지금까지의 방법에 의하면 유수를 구하기 위해서는 반드시 함수의 로랑 급수를 구해서 계수를 확인해야만 했다. 그러나 위 정리는 극점의 경우 반드시 위와 같이 어떤 함수 $\phi$와 $(z-z_0)^m$의 조합으로 생길 수 밖에 없음을 말해주고 있으므로, 위 표현과 같이 함수를 잘 나타낼 수만 있다면 굳이 함수의 로랑 급수를 찾지 않아도 간단한 계산으로 유수를 구할 수 있다. 물론 모든 경우에 위 정리를 사용하는 게 더 간편하다는 건 아니고, 함수의 모양에 따라서는 오히려 위 정리를 적용하는 게 더 힘들고 그냥 로랑 급수 전개하는 게 더 편한 경우도 있다. 또한 극점이 여러 개 있을 경우 함수 $\phi$의 개수 또한 여러 개가 존재하고, $f$ 또한 여러 방식으로 나타낼 수 있음을 주의하자.

## Proof
**(i)** $\implies$ **(ii)** 


**(i)** $\impliedby$ **(ii)** 

## Example 3


# Reference
- Brown, James Ward, & Churchill, Ruel V. (2017). Complex Variables and Applications (9th ed.). McGraw-Hill.