---
title: "Division Ring"
author: "Youmin Chun"
date: "2026-09-11 00:00:02"
description: "추상대수학의 Division Ring에 대해서 설명한다."
categories: 
  - Math > Abstract Algebra > Ring Theory
---

# Definition
**(i)** A [ring](../Ring/index.qmd#sec-definition) $R$ is called a ***ring with identity*** if $\exists 1 \in R$ such that $\forall a \in R, a1 = a = 1a$.

**(ii)** Let $R$ be a ring with identity. An element $u \in R$ is called a ***unit*** of $R$ if there exists $b \in R$ such that $ub = 1 = bu$. In this case, we write $b = u^{-1}$.

**(iii)** A ring $R$ with identity is called a ***division ring*** if every nonzero element of $R$ is a unit. That is, every nonzero element has the multiplicative inverse.

본래 환은 덧셈에 대해서 군이고 곱셈에 대해서는 반군이기 때문에 덧셈의 항등원, 역원은 존재하지만 곱셈의 항등원, 역원은 존재할 필요가 없었다. 여기에 곱셈에 대해서도 항등원, 역원의 개념을 부여해 준 환이 division ring이다. 한국어로는 나눗셈환, 상환 정도로 번역되는 듯하다. 또한 군에서 보인 바와 같이 곱셈의 항등원, 역원이 존재한다면 유일하게 존재한다.

한편, 일반적으로 덧셈의 항등원 $0$과 곱셈의 항등원 $1$은 서로 다른 원소라고 가정한다. 만약 환 $R$에서 $0 = 1$이 성립한다고 가정하면 $R = \{ 0 \}$, 즉 $R$은 zero ring이라는 결론이 도출된다.

$$\begin{align*}
a &= 1a \\
&= 0a \\
&= 0
\end{align*}$$

따라서 $0 \neq 1$이라는 가정은 사실상 환이 zero ring이 아니라는 가정과 동일하다.

## Example
**(i)** In $\mathbb{Z}_{14}$, $\{ 1, 3, 5, 9, 11, 13 \}$ is the set of units. In fact, these numbers are relatively prime to $14$.

**(ii)** $\mathbb{Z}$ is a commutative ring with identity, but it is not a division ring, because $\mathbb{Z}$ does not contain the multiplicative inverse in general.

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.