---
title: "Iterative Method"
author: "Youmin Chun"
date: "2026-07-04"
categories: 
  - Math > Numerical Analysis
---

# 1. Iterative Method
## 1.1. Introduction
다음과 같은 1차원 경계값 문제를 고려하자.

\begin{align*}
\begin{cases}
-u''(x) + \sigma u(x) = f(x), \quad x \in (0, 1), \sigma \ge 0 \\
u(0) = 0 = u(1) 
\end{cases}
\end{align*}

$f$가 적당히 주어지면 손으로도 쉽게 풀 수 있는 문제지만, 수치적으로 풀기 위해서는 또 다른 방법이 필요하다. 우선 컴퓨터로 풀기 위해서는 유한한 값들이 필요하기 때문에 도메인을 잘게 쪼개는 과정이 필요하다. 

$$\Omega^h = \left\{ x_j = jh \mid j = 0, 1, \dots, n, h = \frac{1}{m} \right\}$$

$m$은 주어지는 값이다. 편의상 $u(x_j) = v_j, f(x_j) = f_j$로 쓰기로 하자. 그러면 기존에 주어진 문제는 다음과 같이 이산화된 형태로 쓸 수 있다.

\begin{align*}
\begin{cases}
\frac{-v_{j-1} + 2v_j - v_{j+1}}{h^2} + \sigma v_j = f_j, \quad j = 1, \dots, n-1 \\
v_0 = 0 = v_n
\end{cases}
\end{align*}

이제 $j = 1, ..., n-1$까지 식을 차례차례 적어보면 다음과 같이 쓸 수 있고,

\begin{align*}
\frac{1}{h^2}[(2+\sigma h^2)v_1 - v_2] &= f_1 \\
\frac{1}{h^2}[-v_1 + (2+\sigma h^2)v_2 - v_3] &= f_2 \\
\vdots \\
\frac{1}{h^2}[-v_{n-2} + (2+\sigma h^2)v_{n-1}] &= f_{n-1}
\end{align*}

이를 행렬 형태로 적으면 다음과 같다.

$$\frac{1}{h^2}
\begin{bmatrix}
2+\sigma h^2 & -1 & 0 & \cdots & 0 \\
-1 & 2+\sigma h^2 & -1 & \cdots & 0 \\
0 & -1 & 2+\sigma h^2 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 2+\sigma h^2
\end{bmatrix}
\begin{bmatrix}
    v_1 \\
    v_2 \\
    \vdots \\
    v_{n-1}
\end{bmatrix}
= 
\begin{bmatrix}
    f_1 \\
    f_2 \\
    \vdots \\
    f_{n-1}
\end{bmatrix}$$

각 행렬과 벡터를 $A, \mathbf{v}, \mathbf{f}$라고 하면, 결국 연립일차방정식 $A\mathbf{v} = \mathbf{f}$를 푸는 문제로 귀결된다. 간단한 예시를 들기 위해 1차원으로 가지고 왔지만, 2차원도 같은 방식으로 이산화를 시켜보면 같은 형태의 연립일차방정식을 맞닥뜨리게 됨을 확인할 수 있다.

이러한 종류의 선형방정식을 푸는 수치적 방법은 이전부터 활발하게 연구되어 왔는데, 크게 ***direct method***와 ***iterative method***, 다른 말로는 ***relaxation method***로 나뉜다. 

Direct method란 말 그대로 직접 해를 구하는 방법인데, Gauss-Jordan elemination이 대표적인 direct method이다. 유한 번의 대수적인 조작을 거쳐서 정확한 해를 구하는 방법이다. 간단하지만 특정한 종류의 문제에만 사용할 수 있다는 단점이 있다. 

Iterative method는 말 그대로 반복적으로 연산을 거쳐서 해를 구하는 방법인데, Gauss-Seidel method가 대표적인 iterative method이다. 우선 적절한 초기값으로 해를 추정하고 시작하는데, 점점 실제해와 가깝게 근사시킴으로써 원하는 수준의 오차를 가지는 해를 구하는 것이 목표이다. Direct method보다는 조금 복잡할 수 있지만 보다 더 일반적이고 광범위하게 적용될 수 있다는 게 장점이다. 이 문서에서는 iterative method를 중점적으로 소개한다.

## 1.2. Error and Residual
위에서 설명했듯이, iterative method는 적당한 해를 시작으로 실제 해에 점점 근사시키는 것이 목적이다. 당연하게도 근사해와 실제 해는 오차가 있을 수 밖에 없고, 충분히 오차가 작아질 때까지 근사시키면 충분하다. 실제 해를 $\mathbf{u}$, 근사해를 $\mathbf{v}$이라고 하면 ***오차***, 즉 ***error***는 자연스럽게 $\mathbf{e} = \mathbf{u} - \mathbf{v}$로 정의할 수 있겠다. 그런데 당연하게도 오차 $\mathbf{e}$를 구하는 건 실제 해 $\mathbf{u}$를 구하는 것만큼 어려운 일인데, 우리는 실제 해 $\mathbf{u}$를 모르는 상태에서 근사해 $\mathbf{v}$를 $\mathbf{u}$에 근사시키고 싶기 때문이다.

그래서 우리는 ***잔차***, 즉 ***residual***이라는 또 다른 오차를 통해서 근사해 $\mathbf{v}$가 실제 해에 얼마나 가까운지 추정하려고 한다. 선형방정식 $A\mathbf{u} = \mathbf{f}$이 주어졌을 때 잔차는 다음과 같이 정의된다.

$$\mathbf{r} = \mathbf{f} - A\mathbf{v}$$

한편, 잔차와 오차는 다음의 관계를 가진다. 

\begin{align*}
\mathbf{r} &= \mathbf{f} - A \mathbf{v} \\
&= A\mathbf{u} - A\mathbf{v} \\
&= A(\mathbf{u} - \mathbf{v}) \\
&= A\mathbf{e}
\end{align*}

다시 말해 방정식 $A \mathbf{e} = \mathbf{r}$을 풀면 오차 $\mathbf{e}$를 구할 수 있고, 이를 통해 근사해가 실제 해에 얼마나 근접한지 측정할 수 있다.

# Reference
- Briggs, William L.; Henson, Van Emden; McCormick, Steve F. (2000). A Multigrid Tutorial (2nd ed.). SIAM.