---
title: "Connected Graph"
author: "Youmin Chun"
date: "2026-08-08"
description: "연결 그래프와 component에 대해서 소개한다."
categories: 
  - Math > Graph Theory > Graph
---

## Theorem 1
Let $G$ be a graph, and let the relation $\sim_c$ be defined on $V(G)$ by

$$u \sim_c v \iff \text{there is a } uv\text{-walk in } G.$$

Then $\sim_c$ is an equivalence relation on $V(G)$. 

### Proof
Let $u, v, w \in V(G)$.

Clearly, there is a $uu$-walk in $G$. **(reflexive)**

If there is a $uv$-walk in $G$, say $u = x_0, x_1, ..., x_k = v$, then there is a $vu$-walk in $G$, namely $v = x_k, x_{k-1}, ..., x_0 = u$. **(symmetric)**

If there is a $uv$-walk in $G$, say $u = x_0, x_1, ..., x_k = v$, and there is a $vw$-walk in $G$, say $v = y_0, y_1, ..., y_l = w$, then there is a $uw$-walk in $G$, namely $u = x_0, x_1, ..., x_k = v = y_0, y_1, ..., y_l = w$. **(transitive)**

Thus, $\sim_c$ is an equivalence relation on $V(G)$. $\blacksquare$

## Definition
Let $G$ be a graph.

**(i)** $G$ is said to be ***connected*** if $u \sim_c v$ for all $u, v \in V(G)$.

**(ii)** Let $C$ be a equivalence class of $V(G)$ under $\sim_c$. The subgraph of $G$ induced by $C$ is called a ***component*** of $G$. 

**(iii)** The ***complement*** of $G$, denoted by $\overline{G}$, is a graph on $V(G)$, with $E(\overline{G}) = \overline{E(G)}$.

## Theorem 2
**(i)** Each component of any graph is connected.

**(ii)** A graph is connected $\iff$ it has only one component.

### Proof
**(i)** Let $C$ be a component of $G$, and let $u, v \in V(C)$. Clearly $u \sim_c v$. 

**(ii)** 

$(\Longrightarrow)$

Suppose that a graph $G$ is connected. Since $u \sim_c v, \forall u, v \in V(G)$, there is only one equivalence class, that is $V(G)$. Therefore, $G$ has only one component.

$(\Longleftarrow)$

Suppose that a graph $G$ has only one component, say $C$. Then clearly $G = C$. By (i), $G$ is connected. $\blacksquare$

## Theorem 3
If a graph $G$ is disconnected, then its complement $\overline{G}$ is connected. 

### Proof
We prove the contrapositive.

Suppose that $\overline{G}$ is disconnected. By Theorem 2 (ii), $\overline{G}$ has more than one component. Let $C_1, ..., C_n$ be the all components of $\overline{G}$. Then $u \not \sim_{\overline{G}} v, \forall u \in C_i, v \in C_j, i \ne j$, which is equivalent to $u \sim_{G} v, \forall u \in C_i, v \in C_j, i \ne j$. 

Let $x, y \in V(G)$. If $x = y$, then clearly there is a $xy$-walk in $G$. Suppose that $x \neq y$.

**Case 1**: $x \in C_i$ and $y \in C_j$ with $i \ne j$.

Then $x \sim_G y$, which means that there is a $xy$-walk in $G$. 

**Case 2**: $x, y \in C_i$.

Take $z \in C_j$ with $j \ne i$. Then $x \sim_G z$ and $z \sim_G y$, which means that there are $xz$-walk and $zy$-walk in $G$. Then there are $xy$-walks in $G$. 

Thus, for any $x, y \in V(G)$, there are $xy$-walks in $G$, so $G$ is connected. $\blacksquare$

## Remark
연결되지 않은 그래프의 인접 행렬은 다음과 같이 block-diagonal matrix로 표현될 수 있다. 각 블럭은 component의 인접 행렬 꼴이다. 

$$\mathbf{A} =
\begin{bmatrix}
    \boxed{\phantom{\Huge O}} & 0 & \cdots \\
    0 & \boxed{\phantom{\Huge O}} & \cdots \\
    \vdots & \vdots & \ddots
\end{bmatrix}.$$

주의할 점은 정점들의 인덱스가 각 component들끼리 잘 정렬되어 있어야 한다는 점이다. 때문에 주어진 그래프에서 component를 찾아야 하고, 이는 [BFS](../Breadth_First_Algorithm/index.qmd#sec-algorithm)와 같은 알고리즘으로 가능하다.

# Reference
- Matousek, J., & Nesetril, J. (2008). Invitation to Discrete Mathematics. Oxford University Press.
- Newman, M.E.J. (2010). Networks: An Introduction. Oxford University Press.