---
title: "Subbasis"
author: "Youmin Chun"
date: "2026-07-08"
categories: 
  - Math > Topology
---

## Definition
A ***subbasis*** for a set $X$ is a collection $\mathscr{S}$ of subsets of $X$ such that 

$$\bigcup_{S \in \mathscr{S}} S = X.$$

## Theorem 1
Let $\mathscr{S}$ be a subbasis on a set $X$. Then the collection $\mathscr{B} _ {\mathscr{S}}$ defined by

$$\mathscr{B} _ {\mathscr{S}} = \left\{ \bigcap_{S \in \mathscr{S}'} S \,\, \Bigg \vert \,\, \mathscr{S}' \subset \mathscr{S}, \vert \mathscr{S}' \vert < \infty \right\}$$

is a basis on $X$. In this case, we say that $\mathscr{S}$ is a ***subbasis for a topology*** on $X$, or $\mathscr{T} _ {\mathscr{S}}$ is ***the topology generated by a subbasis*** $\mathscr{S}$.

선형대수적인 센스로 볼 때 생성된 위상의 오픈 셋들은 항상 기저 집합들의 합집합으로 표현할 수 있었다. 벡터 공간이 벡터합과 스칼라배라는 연산이 주어진 공간으로 생각할 때, 위상은 합집합과 교집합이라는 연산이 주어진 공간으로 볼 수 있다. 그렇다면 자연스럽게 유한 번의 교집합으로도 위상을 만들어낼 수 있지 않을까, 하는 질문을 던질 수 있고, 그에 대한 대답이 바로 부분기저다. 

부분기저의 정의 자체는 그저 전체 집합 $X$를 커버하는 부분집합들의 모임일 뿐이지만, 이 부분기저 집합들을 유한번 교집합한 결과들을 모아놓으면 기저의 정의상 자연스럽게 기저가 된다. 그리고 기저를 통해 항상 위상을 생성해 낼 수 있었으므로 결국 부분기저를 찾으면 기저를 만들 수 있고, 그 기저로 다시 위상을 만들 수 있게 된다. 

### Proof
Let $x \in X$. Since $\mathscr{S}$ is a subbasis on $X$, $x \in S$ for some $S \in \mathscr{S}$. Since 

$$S = \bigcup_{S \in \{ S \}} S$$

and $\{ S \} \subset \mathscr{S}$, we have $S \in \mathscr{B} _ {\mathscr{S}}$. Thus the first condition is satisfied.

Let $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B} _ {\mathscr{S}}$. Then $B_1 = S_1 \cap \cdots \cap S_n$ and $B_2 = S_1' \cap \cdots \cap S_m'$ for some $S_i, S_i' \in \mathscr{S}$. Since 

$$B_1 \cap B_2 = (S_1 \cap \cdots \cap S_n) \cap (S_1' \cap \cdots \cap S_m') \in \mathscr{B} _ {\mathscr{S}}$$

and it contains $x$, the second condition is satisfied. Thus $\mathscr{B} _ {\mathscr{S}}$ is a basis on $X$. $\blacksquare$

## Example
Let $\mathscr{S} = \{ (-\infty, a), (b, \infty) \mid a, b \in \mathbb{R} \}$. Then $\mathscr{S}$ is a subbasis generating the standard topology on $\mathbb{R}$.

$(\because)$ If we take $a = 1$ and $b = -1$, then clearly $\mathscr{S}$ covers $\mathbb{R}$. The basis generated by $\mathscr{S}$ is $\mathscr{B} _ {\mathscr{S}} = \{ (a, b) \mid a, b \in \mathbb{R} \}$, which is the basis for the standard topology on $\mathbb{R}$. $\blacksquare$ 

## Theorem 2
Let $\mathscr{S}$ be a subbasis for a topology on $X$. Then $\mathscr{T} _{\mathscr{S}}$ is the smallest topology on $X$ that contains $\mathscr{S}$.

### Proof

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.