---
title: "Basis of Topology"
author: "Youmin Chun"
date: "2026-07-08 00:00:02"
description: "위상공간의 기저에 대해서 설명하고 관련된 정리들을 소개한다."
categories: 
  - Math > Topology
---

# Definition 1
A ***basis*** on a set $X$ is a collection $\mathscr{B}$ of subsets of $X$ such that

**(i)** For each $x \in X$, there exists $B \in \mathscr{B}$ such that $x \in B$.

**(ii)** If $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B}$, then there exists $B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2$.

## Example 1
**(i)** The collection 

$$\mathscr{B}_1 = \{ (a, b) \mid a, b \in \overline{\mathbb{R}} \}$$

of open intervals in $\mathbb{R}$ is a basis for a topology on $\mathbb{R}$, but it is **NOT** a topology on $\mathbb{R}$.

**(ii)** Let $X$ be a set. The collection

$$\mathscr{B}_2 = \{ \{ x \} \mid x \in X \}$$

is a basis for the discrete topology on $X$. 

# Theorem 1
**(i)** Let $\mathscr{B}$ be a basis on a set $X$. Then the collection 

$$\mathscr{T} _ { \mathscr{B} } = \{ U \subset X \mid \forall x \in U, \exists B_x \in \mathscr{B} \, [x \in B_x \subset U] \}$$

is a topology on $X$. In this case, we say that $\mathscr{T}_{ \mathscr{B} }$ is ***the topology generated by a basis $\mathscr{B}$***, or $\mathscr{B}$ is ***a basis for a topology*** on $X$. 

즉 부분집합 $U \subset X$가 기저 집합들에 대해서 오픈 셋의 성질을 만족하도록 컬렉션을 구성하면 자연스럽게 위상 공간을 만들 수 있고, 이를 기저 $\mathscr{B}$가 생성하는 위상 공간이라고 부른다.

**(ii)** Let $\mathscr{B}$ be a basis on a set $X$, and let $\mathscr{T}_{ \mathscr{B} }$ be the topology on $X$ generated by $\mathscr{B}$. Then 

$$\mathscr{T}_{ \mathscr{B} } = \left\{ \bigcup_{U \in \mathcal{A}} U \,\, \Bigg \vert \,\, \mathcal{A} \subset \mathscr{B} \right\}$$

선형대수에서 벡터 공간의 임의의 원소는 기저벡터들의 선형 결합으로 표현할 수 있었듯이, 기저 $\mathscr{B}$가 생성하는 위상 공간의 임의의 오픈 셋은 기저 집합들의 합집합으로 표현할 수 있다. 

**(iii)** Let $(X, \mathscr{T})$ be a topological space, and let $\mathscr{B}$ be a subcollection of $\mathscr{T}$. TFAE.

1. $\mathscr{B}$ is a basis for $\mathscr{T}$. That is, $\mathscr{T} = \mathscr{T}_{ \mathscr{B} }$.

2. For each $U \in \mathscr{T}$ and $x \in U$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$.

**(i)**은 어떤 기저가 만들어내는 위상에 대해서 언급했다면, Theorem 3은 주어진 위상으로부터 컬렉션 $\mathscr{B}$를 위와 같이 정의하면 기저를 만들어낼 수 있음을 언급한다. 

**(iv)** Let $\mathscr{B}$ and $\mathscr{B}'$ be bases for topologies $\mathscr{T}_{ \mathscr{B} }$ and $\mathscr{T}_{ \mathscr{B}' }$, respectively, on a set $X$. TFAE.

1. $\mathscr{T}_{ \mathscr{B} } \subset \mathscr{T}_{ \mathscr{B}' }$, that is, $\mathscr{T}_{ \mathscr{B}' }$ is finer than $\mathscr{T}_{ \mathscr{B} }$.

2. For each $x \in X$ and $B \in \mathscr{B}$ such that $x \in B$, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B$.

정리 자체는 한 방향의 포함 관계에 대해서만 말하고 있지만, 만약 두 방향 모두를 위 명제를 통해 보일 수 있다면 우리는 두 위상이 서로 같음을 보이게 된다. 

::: {.callout-note title="Proof" collapse="true"}
## Proof
**(i)** If $U = \emptyset$, then it satisfies the condition vacuously, which means that $\emptyset \in \mathscr{T}_{ \mathscr{B} }$. Let $U = X$ and let $x \in U$. Since $\mathscr{B}$ is a basis, $\exists B \in \mathscr{B}$ such that $x \in B \subset X = U$, so that $X \in \mathscr{T} _ { \mathscr{B} }$.

Let $\{ U_\alpha \} \subset \mathscr{T} _ { \mathscr{B} }$. Clearly $\bigcup U_{\alpha} \subset X$. If $x \in \bigcup U_{\alpha}$, then $x \in U_{\alpha}$ for some $\alpha$. Since each $U_{\alpha}$ is in $\mathscr{T}_{ \mathscr{B} }$, there exists $B_x \in \mathscr{B}$ such that $x \in B_x \subset U_{\alpha} \subset \bigcup U_{\alpha}$. Thus the union of $\{ U_{\alpha} \}$ is an element of $\mathscr{T} _ { \mathscr{B} }$.

We show the final condition by induction. Let $U_1, U_2 \in \mathscr{T} _ { \mathscr{B} }$. Let $x \in U_1 \cap U_2$. Since $U_1$ and $U_2$ are the elements of $\mathscr{T}_{ \mathscr{B} }$, there exists $B_1, B_2 \in \mathscr{B}$ such that $x \in B_1 \subset U_1$ and $x \in B_2 \subset U_2$. Then $x \in B_1 \cap B_2 \subset U_1 \cap U_2$. Since $\mathscr{B}$ is a basis, $\exists B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2 \subset U_1 \cap U_2$. Thus $U_1 \cap U_2 \in \mathscr{T}_{ \mathscr{B} }$.

Suppose that $U_1 \cap \cdots \cap U_{n} \in \mathscr{T}_{ \mathscr{B} }$ for any $U_1, ..., U_n \in \mathscr{T} _ { \mathscr{B} }$. Let $U_{n+1} \in \mathscr{T}_{ \mathscr{B} }$. Since we have shown the intersection of two sets in $\mathscr{T} _ { \mathscr{B} }$ is also an element of $\mathscr{T}_{ \mathscr{B} }$, we have $U_1 \cap \cdots \cap U_{n+1} \in \mathscr{T} _ { \mathscr{B} }$. Thus $\mathscr{T} _ { \mathscr{B} }$ is a topology on $X$. 

**(ii)** Let us denote 

$$T = \left\{ \bigcup_{U \in \mathcal{A}} U \,\, \Bigg \vert \,\, \mathcal{A} \subset \mathscr{B} \right\}.$$

Let $\displaystyle \bigcup_{U \in \mathcal{A}} U \in T$ where $\mathcal{A} \subset \mathscr{B}$. Since each $U \in \mathscr{B}$ is an element of $\mathscr{T}_{ \mathscr{B} }$ and $\mathscr{T}_{ \mathscr{B} }$ is a topology on $X$, the union $\displaystyle \bigcup_{U \in \mathcal{A}} U$ belongs to $\mathscr{T}_{ \mathscr{B} }$, which means that $T \subset \mathscr{T}_{ \mathscr{B} }$.

Let $U \in \mathscr{T}_{ \mathscr{B} }$. If $x \in U$, then $\exists B_x \in \mathscr{B}$ such that $x \in B_x \subset U$. Note that 

$$U = \bigcup_{x \in U} B_x.$$

Since $\{ B_x \in \mathscr{B} \mid x \in U \}$ is a subcollection of $\mathscr{B}$, we have $U \in T$, which means that $\mathscr{T}_{ \mathscr{B} } \subset T$. Thus $T = \mathscr{T}_{ \mathscr{B} }$. 

**(iii)** **1.** $\implies$ **2.** By definition of $\mathscr{T}_{ \mathscr{B} }$, it is clear.

**2.** $\implies$ **1.** First, we show that $\mathscr{B}$ is a basis. Let $x \in X$. Since $\mathscr{T}$ is a topology on $X$, $X \in \mathscr{T}$. Thus $\exists U \in \mathscr{T}$ such that $x \in U$. By assumption, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$. 

Let $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B}$. Since $B_1, B_2 \in \mathscr{T}$, so that $B_1 \cap B_2 \in \mathscr{T}$, $\exists B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2$. Thus $\mathscr{B}$ is a basis.

Next, we show that $\mathscr{T} = \mathscr{T}_{ \mathscr{B} }$. Let $U \in \mathscr{T}$. If $x \in U$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$ by assumption. Thus $U \in \mathscr{T}_{ \mathscr{B} }$ by definition of $\mathscr{T}_{ \mathscr{B} }$.

Let $U \in \mathscr{T}_{ \mathscr{B} }$. By **(ii)**, $U = \bigcup_{K \in \mathcal{A}} K$ for some $\mathcal{A} \subset \mathscr{B}$. Since $\mathscr{B} \subset \mathscr{T}$, we have $U \in \mathscr{T}$. Thus $\mathscr{T} = \mathscr{T}_{ \mathscr{B} }.$

**(iv)**
**1.** $\implies$ **2.** Let $x \in X$ and let $B \in \mathscr{B}$ such that $x \in B$. Since $\mathscr{T}_{ \mathscr{B} } \subset \mathscr{T}_{ \mathscr{B}' }$, we have $B \in \mathscr{T}_{ \mathscr{B}' }$. By definition of $\mathscr{T}_{ \mathscr{B}' }$, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B$. 

**2.** $\implies$ **1.** Let $U \in \mathscr{T}_{ \mathscr{B} }$. For each $x \in X$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$ by definition of $\mathscr{T}_{ \mathscr{B} }$. By assumption, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B \subset U$. Thus $U \in \mathscr{T}_{ \mathscr{B}' }$. Hence $\mathscr{T}_{ \mathscr{B} } \subset \mathscr{T}_{ \mathscr{B}' }. \blacksquare$ 
:::

## Remark 1
**(i)** Each basis element $B$ of $\mathscr{B}$ is an element of $\mathscr{T} _ { \mathscr{B} }$.

**(ii)** Every topology on a set $X$ has a basis generating itself. In particular, $\mathscr{T}$ is a basis for itself, that is, $\mathscr{T} = \mathscr{T} _ { \mathscr{T} }$.

::: {.callout-note title="Proof" collapse="true"}
$\big[(\because)$ Let $\mathscr{T}$ be a topology on a set $X$. For each $x \in X$, $x \in X \in \mathscr{T}$. If $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{T}$, then $x \in B_1 \cap B_2 \in \mathscr{T}$. Thus $\mathscr{T}$ is a basis for a topology on $X$. 

Let $U \in \mathscr{T}$. If $x \in U$, then $x \in U \subset U$, which means that $U \in \mathscr{T} _ {\mathscr{T}}$. Thus $\mathscr{T} \subset \mathscr{T} _ {\mathscr{T}}$.

Let $U \in \mathscr{T} _ {\mathscr{T}}$. If $x \in U$, then $\exists B_x \in \mathscr{T}$ such that $x \in B_x \subset U$. We claim that $\bigcup_{x \in U} B_x = U$. 

$\big[(\because)$ Since each $B_x \subset U$, we have $\bigcup_{x \in U} B_x \subset U$. If $x \in U$, then $\exists B_x \in \mathscr{T}$ such that $x \in B_x \subset U$, which means that $x \in \bigcup_{x \in U} B_x$. Thus $U \subset \bigcup_{x \in U} B_x.\big]$

Therefore $\bigcup_{x \in U} B_x = U$. Since $\mathscr{T}$ is a topology on $X$, $\bigcup_{x \in U} B_x \in \mathscr{T}$, which means that $U \in \mathscr{T}$. Thus $\mathscr{T} _ {\mathscr{T}} \subset \mathscr{T}$. 

Therefore $\mathscr{T} = \mathscr{T} _ {\mathscr{T}}$. $\blacksquare \big]$
:::

**(iii)** But every basis on a set $X$ need **NOT** be a topology on $X$ in general. The counterexample is $\mathscr{B}_1$ in Example **(i)**.

# Definition 2
A ***subbasis*** for a set $X$ is a collection $\mathscr{S}$ of subsets of $X$ such that 

$$\bigcup_{S \in \mathscr{S}} S = X.$$

# Theorem 2
**(i)** Let $\mathscr{S}$ be a subbasis on a set $X$. Then the collection $\mathscr{B} _ {\mathscr{S}}$ defined by

$$\mathscr{B} _ {\mathscr{S}} = \left\{ \bigcap_{S \in \mathscr{S}'} S \,\, \Bigg \vert \,\, \mathscr{S}' \subset \mathscr{S}, \vert \mathscr{S}' \vert < \infty \right\}$$

is a basis on $X$. In this case, we say that $\mathscr{S}$ is a ***subbasis for a topology*** on $X$, or $\mathscr{T} _ {\mathscr{S}}$ is ***the topology generated by a subbasis*** $\mathscr{S}$.

**(ii)** Let $\mathscr{S}$ be a subbasis for a topology on $X$. Then $\mathscr{T} _{\mathscr{S}}$ is the smallest topology on $X$ that contains $\mathscr{S}$.

선형대수적인 센스로 볼 때 생성된 위상의 오픈 셋들은 항상 기저 집합들의 합집합으로 표현할 수 있었다. 벡터 공간이 벡터합과 스칼라배라는 연산이 주어진 공간으로 생각할 때, 위상은 합집합과 교집합이라는 연산이 주어진 공간으로 볼 수 있다. 그렇다면 자연스럽게 유한 번의 교집합으로도 위상을 만들어낼 수 있지 않을까, 하는 질문을 던질 수 있고, 그에 대한 대답이 바로 부분기저다. 

부분기저의 정의 자체는 그저 전체 집합 $X$를 커버하는 부분집합들의 모임일 뿐이지만, 이 부분기저 집합들을 유한번 교집합한 결과들을 모아놓으면 기저의 정의상 자연스럽게 기저가 된다. 그리고 기저를 통해 항상 위상을 생성해 낼 수 있었으므로 결국 부분기저를 찾으면 기저를 만들 수 있고, 그 기저로 다시 위상을 만들 수 있게 된다. 

## Proof
**(i)** Let $x \in X$. Since $\mathscr{S}$ is a subbasis on $X$, $x \in S$ for some $S \in \mathscr{S}$. Since 

$$S = \bigcup_{S \in \{ S \}} S$$

and $\{ S \} \subset \mathscr{S}$, we have $S \in \mathscr{B} _ {\mathscr{S}}$. Thus the first condition is satisfied.

Let $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B} _ {\mathscr{S}}$. Then $B_1 = S_1 \cap \cdots \cap S_n$ and $B_2 = S_1' \cap \cdots \cap S_m'$ for some $S_i, S_i' \in \mathscr{S}$. Since 

$$B_1 \cap B_2 = (S_1 \cap \cdots \cap S_n) \cap (S_1' \cap \cdots \cap S_m') \in \mathscr{B} _ {\mathscr{S}}$$

and it contains $x$, the second condition is satisfied. Thus $\mathscr{B} _ {\mathscr{S}}$ is a basis on $X$. $\blacksquare$

## Example 2
Let $\mathscr{S} = \{ (-\infty, a), (b, \infty) \mid a, b \in \mathbb{R} \}$. Then $\mathscr{S}$ is a subbasis generating the standard topology on $\mathbb{R}$.

$\big[ (\because)$ If we take $a = 1$ and $b = -1$, then clearly $\mathscr{S}$ covers $\mathbb{R}$. The basis generated by $\mathscr{S}$ is $\mathscr{B} _ {\mathscr{S}} = \{ (a, b) \mid a, b \in \mathbb{R} \}$, which is the basis for the standard topology on $\mathbb{R}$. $\blacksquare \big]$ 

# Definition 3
Let $(X, \mathscr{T})$ be a topological space, and let $\mathscr{U}_x = \{ U \in \mathscr{T} \mid x \in U \}$ for each $x \in X$. Then the subcollection $\mathscr{B}_x$ of $\mathscr{U}_x$ is called a ***local basis*** at $x$ if $\forall U \in \mathscr{U}_x$, $\exists B \in \mathscr{B}_x$ such that $x \in B \subset U$.

간단하게 말하면 점 $x$에서의 국소기저란 $x$를 포함하는 오픈셋들의 컬렉션으로, $x$를 포함하는 임의의 오픈셋을 들고 오더라도 항상 그 오픈셋 안에 포함되는 국소기저의 원소를 잡아올 수 있음을 의미한다. 즉 국소기저의 원소들은 $x$ 주변에 있는 충분히 작은 오픈셋을 보장한다. 이러한 정의는 특정한 점에서의 정의나 성질을 체크할 때 오픈셋 대신 국소기저만 보더라도 충분함을 보여준다. 예컨대 국소기저를 사용하면 다음의 사실들이 성립한다.

1. For $A \subset X$, 

$$x\in\overline A \iff \forall B\in\mathscr B_x, B\cap A\neq \emptyset$$

2. For a sequence $\{ x_n \}$ of $X$, 

$$x_n\to x \iff \forall B\in\mathscr B_x, \exists N\in\mathbb N, \forall n\ge N, x_n\in B$$

3. For a function $f: X \to Y$ and local bases $\mathscr{B}_x$ and $\mathscr{C}_{f(x)}$ at $x$ and $f(x)$ respectively, 

$$f \text{ is continuous at }x \iff \forall C\in\mathcal C_{f(x)},\exists B\in\mathcal B_x, f(B)\subseteq C$$

즉 기존에는 오픈셋을 들고와서 체크해야 했던 내용들이 국소기저만 체크해도 충분함을 알려준다. 그야말로 '국소'기저라는 이름에 걸맞는 일이다.

한편 아래 정리 **(i)**에 의해 임의의 점에서의 국소기저의 존재성은 항상 보장되지만, 일반적으로 국소기저는 유일하지는 않다. 예컨대 유클리드 공간 $(\mathbb{R}, \mathscr{T}_{\text{usual}})$에서

$$\mathscr{B}_0 = \left \{ \left( - \frac{1}{n}, \frac{1}{n} \right) \,\, \Bigg \vert \,\, n \ge 1 \right \}, \quad \mathscr{B}'_0 = \left \{ \left( - \frac{1}{n}, \frac{1}{n} \right) \,\, \Bigg \vert \,\, n \ge 2 \right \}$$

는 모두 $0$의 국소기저이지만 서로 다른 국소기저이다.

또한 아래 정리 **(i)**에서 엿볼 수 있듯이, 일반적으로 국소기저라고 해서 기저가 되지는 않는다. 마찬가지로 유클리드 공간에서

$$\mathscr{B}^\ast_0 = \{ (- \varepsilon, \varepsilon) \mid \varepsilon > 0 \}$$

은 $0$의 국소기저이지만 기저는 될 수 없는데, 오픈셋 $(1, 2)$를 합집합으로 표현해낼 수 없기 때문이다. 한편 위 예시들과 아래 정리 **(ii)**에서 알 수 있듯이, 대충 말하자면 $x$에서의 국소기저란 $x$를 기준으로 점점 작아지는 오픈셋들의 집합을 의미한다고도 할 수 있겠다.

# Theorem 3
**(i)** If $\mathscr{B}$ is a basis for a space $X$, then $\mathscr{B}_x = \{ B \in \mathscr{B} \mid x \in B \}$ is a local basis at $x$. Conversely, if $\mathscr{B}_x$ is a local basis at each $x \in X$, then $\displaystyle \mathscr{B} := \bigcup_{x \in X} \mathscr{B}_x$ is a basis for $X$.

**(ii)** If $X$ is a $T_1$ space and $\mathscr{B}_x$ is a local basis for $x \in X$, then $\bigcap \mathscr{B}_x = \{ x \}$.

## Proof

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.