---
title: "싱크로트론 복사(Synchrotron Radiation)"
author: "Young Jeong Lee"
date: "2026-08-08"
description: "천체물리학의 복사 중에서 중요하게 다뤄지는 싱크로트론 복사에 대해서 소개한다."
categories: 
  - Astronomy > High Energy Astrophysics
---

# 1. 싱크로트론 복사(Synchrotron Radiation)

- **싱크로트론 복사(synchrotron radiation)**: 전자가 강한 자기장 속에서 상대론적 운동을 하며, 전파 복사하는 것을 의미한다. 보통 전자가 자기장을 따라 나선형을 그리며, 광속에 가까운 속도로 운동하면서 방출되는 복사로 생각된다. (아래 그림 참고)

![싱크로트론 복사를 보여주는 그림. [1]](synchrotron_radiation.png)

- 반면, 비상대론적으로 운동하는 전자에 의해 방출되는 복사를 **사이클로트론 복사(cyclotron radiation)** 이라고 한다. 

---

# 2. Spectrum density for single particle {#spectrum_single_particle}

- 단일 전자를 고려하자. 해당 전자는 자기장과 pitch angle $\alpha$ 를 이루고 있으며, 그때의 전자 에너지는 $E$, 그리고 Lorentz factor $\gamma \gg 1$ 라고 가정하자. 
- 이때, 주파수 $\nu$ 근처에서 단위 주파수당 방출되는 total emissivity는 다음과 같다:

$$
P(\nu) = \sqrt{3} \frac{e^3B\sin\alpha}{mc^2}  \frac{\nu}{\nu_c} \int_{\nu/\nu_c}^{\infty} K_{5/3}(\eta) d\eta  \tag{2.1}
$$

- 단위: $\mathrm{erg\ s^{-1}\ Hz^{-1}}$ 
- $K_{5/3}$ 는 차수(order) $5/3$ 의 modified Bessel function이다.
- **pitch angle**: 자기장 방향에 대한 입자 속도 벡터의 각도를 의미하며, 다음과 같이 정의된다: 

$$
\tan\alpha = \frac{|v_\perp|}{|v_\parallel|}  \tag{2.2}
$$

- 전자는 자기장 안에서 속도 $v$ 로 나선 운동하고 있으며, $v_\perp$ 은 자기장에 수직한 속도 성분, $v_\parallel$ 은 자기장에 평행한 속도 성분을 의미한다. 
- 그리고 식 (2.1)에서 임계 주파수(critical frequency) $\nu_c$ 는 다음과 같이 정의된다: 

$$
\nu_c = \frac{3}{2}\gamma^2\nu_G\sin\alpha = \frac{3}{2}\gamma^3\nu_B\sin\alpha,  \tag{2.3}
$$

- $\nu_G=\omega_G / 2\pi$ 는 비상대론적 자이로 주파수(non-relativistic gyro-frequency)이다.

<div style="height: 2rem;"></div>

- 이제 $F(x)$ 를 다음과 같이 정의하자: 

$$
F(x) = x \int_x^\infty K_{5/3}(\eta)d\eta  \tag{2.4}
$$

- 여기서 $x= {\nu} / {\nu_c}$ 이며, $\eta$ 는 적분을 위한 무차원 변수이다. 
- 이를 이용하면, 식 (2.1)은 다음과 같이 나타낼 수 있다:

$$
P(\nu) = \sqrt{3} \frac{e^3B\sin\alpha}{mc^2} F(x)  \tag{2.5}
$$

- 식 (2.5)에서 상수 부분은 방출 세기의 크기를 결정하며, $F(x)$ 는 주파수에 따른 스펙트럼의 모양을 결정한다.  
- 식 (2.4)에 대한 저주파 근사는 다음과 같다: 

$$
F(x)=\frac{4\pi}{\sqrt{3}\Gamma\left(\frac{1}{3}\right)}  
\left(\frac{x}{2}\right)^{1/3},  
\qquad x\ll 1  \tag{2.6}
$$

---

## 2.1. The Spectral Distribution of Synchrotron Radiation from an Ensemble of Electrons 

- [2. Spectrum density for single particle](#spectrum_single_particle) 에서는 단순히 1개의 전자만 고려했다. 실제 상황에서 상대론적 전자들은 넓은 범위에 걸쳐 다양한 속도를 가지며, 또한 매우 다양한 방향으로 운동한다. 더 나아가, 자기장은 불균질하고 얽혀 있다. 
- 일반적인 상대론적 전자들의 체적 방출률(volume emissivity, 단위 주파수, 단위 부피, 단위 질량당 방출되는 power)은 다음과 같이 주어진다: 

$$
\epsilon(\nu) = \int_E P(\nu, E) N(E) dE,  \tag{2.7}
$$

- $P(\nu, E)$: 에너지 $E$ 를 가진 하나의 전자가 식 (2.1)에 따라 방출하는 총 power 
- $N(E)dE$: 관측자 방향으로 운동하면서 에너지가 $E$ 에서 $E + dE$ 사이에 있는 전자들의 단위 부피당, 단위 입체각당 개수
  - 경험적 자료에 의하면 $N(E)$ 는 power-law 스펙트럼 나타난다. 전자의 개수 분포가 균일하고 등방적이라고 가정하면 전자의 운동 방향과 무관하게 다음과 같이 적을 수 있다:

$$
N(E)dE = K E^{-\delta} dE \quad \text{for } E_1 < E < E_2  \tag{2.8}
$$

- $\delta$: 전자 에너지 분포에 대한 spectral index 

<div style="height: 2rem;"></div>

이제 위와 같은 사실들을 이용하면 volume emissivity는 다음과 같이 쓸 수 있다: 

$$ 
\epsilon(\nu)\propto \nu^{-n}\int_{\nu/\nu_2}^{\nu/\nu_1} x^{n-1}P(x)dx.  \tag{2.9}
$$

이는 낮은 에너지를 가진($E_1 \sim \nu_1$) 전자의 주파수와 높은 에너지를 가진 전자의 주파수에 대해서 적분하는 것이다. 여기서 $x={\nu} / {\nu_c}$ 를 이용했다. 

<div style="height: 2rem;"></div>

그리고 $\delta$ 와 $n$ 사이에는 다음과 같은 관계가 성립한다: 

$$
\delta=2n+1  \tag{2.10}
$$

이제 식 (2.9)를 일반화해서 적으면 다음과 같다: 

$$ 
\epsilon(\nu)\propto \nu^{-n}\left[Q(n,\nu/\nu_1)-Q(n,\nu/\nu_2)\right]  \tag{2.11}
$$

$$ 
Q(n,\nu/\nu_c)=\int_{\nu/\nu_c}^{\infty} x^{n-1}F(x)dx.  \tag{2.12}
$$

만약 관측 주파수 $\nu$ 가 전자의 에너지 분포를 만드는 싱크로트론 주파수 범위 안에 있고 저주파수 한계 값과 고주파수 한계 값을 함께 표현해서 나타내면 다음과 같다: 

$$
\frac{\nu}{\nu_2} \ll 1, \quad 1 \ll \frac{\nu}{\nu_1}, \quad x \sim 1 \tag{2.13}
$$

즉, 이는 다음을 의미한다: 

$$
\nu/\nu_2 \ll x \ll \nu/\nu_1 \tag{2.14}
$$

<div style="height: 3rem;"></div>

- 식 (2.14)는 관측 주파수가 전자의 에너지 분포 하한과 상한에서 적당히 떨어진 중간에 존재한다는 의미이다. 이 경우, 식 (2.12)의 적분은 다음과 같이 쓸 수 있다: 

$$
\int_{\nu/\nu_2}^{\nu/\nu_1}  x^{n-1}F(x)dx  \approx  
\int_0^\infty  
x^{n-1}F(x)dx=\mathrm{constant}  
$$

- 적분 결과가 상수이므로 $Q$ 는 **주파수에 의존하지 않는다.** 따라서 이 경우, 식 (2.11)은 다음과 같다: 

$$
\epsilon \propto \nu^{-n}  \tag{2.15}
$$

- 이는 상대론적 전자가 많이 존재하는 경우, volume emissivity가 오로지 주파수에만 의존하는 것을 보여준다. (pitch angle 분포와도 무관하다)
- **고주파수($\nu > \nu_2$)**: 싱크로트론 스펙트럼이 지수적으로 감소한다.
- **저주파수($\nu < \nu_1$)**: 이 경우, spectral index는 식 (2.6)의 $n = 1/3$ 에 근접해야 한다. 
- 이러한 결론은 방출된 전파의 세기와 스펙트럼을 보고 **방출원 안에 어떤 에너지 분포의 전자가 있었는지 역추론**할 수 있다는 것을 시사한다.  


---

# Reference 

- $1.$ [Synchrotron Radiation](https://pages.uoregon.edu/jschombe/glossary/synchrotron_radiation.html)



<style>
h2 {
border-bottom: none !important;
}
</style>