---
title: "Lebesgue Number"
author: "Youmin Chun"
date: "2026-09-15 00:00:01"
description: "위상 수학에서의 르베그 수(Lebesgue Number)에 대해서 설명한다."
categories: 
  - Math > Topology
---

# Definition
Let $A$ be a nonempty subset of a metric space $(X, d)$.

**(i)** For each $x \in X$, we define the ***distance from $x$ to $A$*** by 

$$d(x,A) = \inf_{a \in A} d(x,a).$$

**(ii)** The ***diameter*** of $A$ is defined by 

$$\mathrm{diam}(A) = \sup_{a, b \in A} d(a, b).$$

**(iii)** A number $\delta$ is called a ***Lebesgue number*** for an open cover $\mathcal{U}$ of $X$ if every subset $A$ of $X$ with $\mathrm{diam}(A) < \delta$ is contained in some element of $\mathcal{U}$.

## Remark
**(i)** $d(x, A) \ge 0$.

**(ii)** The function $d(x, A)$ is continuous.

$\big[ (\because)$ Let $x, y \in X$. Then we have

$$\begin{align*}
&d(x, A) \le d(x, a) \le d(x, y) + d(y, a), \forall a \in A \\
\implies &d(x, A) - d(x, y) \le d(y, a), \forall a \in A \\
\implies &d(x, A) - d(x, y) \le \inf_{a \in A} d(y, a) = d(y, A) \\
\implies &d(x, A) - d(y, A) \le d(x, y)
\end{align*}$$

Similarly, we have $d(y, A) - d(x, A) \le d(y, x)$, which implies that $\vert d(x, A) - d(y, A) \vert \le d(x, y)$. For a given $\varepsilon > 0$, we choose $\delta = \varepsilon$. If $d(x, y) < \delta$, then we have

$$\vert d(x, A) - d(y, A) \vert \le d(x, y) < \delta = \varepsilon.$$

Thus, $d(x, A)$ is uniformly continuous on $X$, so it is continuous.$\big]$

**(iii)** If $x \in A$, then $d(x, A) = 0$, but the converse is not true. Actually, if $d(x, A) = 0$, then $x \in \overline{A}$. That is, if $A$ is closed, then $x \in A \iff d(x, A) = 0$.

$\big[ (\because)$ Suppose that $x \in A$. Since $d(x, a) \ge 0, \forall a \in A$ and $d(a, a) = 0, \forall a \in A$, we obtain $d(x, A) = 0$.

Suppose that $d(x, A) = 0$. By definition of the infimum, for every $\epsilon > 0$, there exists $a \in A$ such that $d(x, a) < \epsilon$. Then we construct a sequence $\{ a_n \}$ such that $d(x, a_n) < \frac{1}{n}, \forall n \in \mathbb{N}$. Let $\varepsilon > 0$. Then there exists $N \in \mathbb{N}$ such that $\frac{1}{N} < \varepsilon$. For all $n \ge N$, we have

$$d(x, a_n) < \frac{1}{n} \le \frac{1}{N} < \varepsilon,$$ 

which means that $\lim_{n \to \infty} a_n = x$. [Thus $x \in \overline{A}$.](../Metric_Space/index.qmd#sec-theorem-5) $\big]$ 

# Lebesgue Number Lemma
A compact metric space $(X, d)$ has a Lebesgue number for every open cover $\mathcal{U}$.

컴팩트의 정의를 생각해봤을 때 사실 당연한 결과이다.

## Proof
Let $\mathcal{U}$ be an open cover of $X$. Since $X$ is compact, there is a finite subcover $\{ U_1, \dots, U_n \}$. Let $C_i := X \setminus U_i$ for each $i = 1, \dots, n$. We define a function $f: X \to \mathbb{R}$ such that 

$$f(x) = \frac{1}{n} \sum_{i=1}^n d(x, C_i), \forall x \in X.$$

Clearly $f(x) \ge 0, \forall x \in X$. Moreover, $f(x) > 0, \forall x \in X$.

$\big[ (\because)$ Suppose that $f(x) = 0$ for some $x \in X$. It implies that $d(x, C_i) = 0, \forall i \in \{ 1, \dots, n\}$. By remark **(iii)**, $x \in C_i = X - U_i, \forall i \in \{ 1, \dots, n \}$. Then $x \notin U_i, \forall i \in \{ 1, \dots, n \}$. So $x \notin \bigcup_{i=1}^n U_i = X$, which is a contradiction $\big]$.

By remark **(ii)**, $f$ is continuous. Since $X$ is compact, $f(X)$ is a compact subset of $\mathbb{R}$. Then [$f(X)$ is closed and bounded](../Metric_Space/index.qmd#sec-theorem-6), so there exists $\delta = \inf f(X)$ and $\delta \in f(X)$. Since $f(x) > 0, \forall x \in X$, we have $\delta > 0$. We claim that $\delta$ is a Lebesgue number for $\mathcal{U}$.

Let $A$ be a subset of $X$ with $\mathrm{diam}(A) < \delta$. Choose $a_0 \in A$. For $a \in A$, we have $d(a, a_0) \le \mathrm{diam}(A) < \delta$, which means that $a \in B_d(a_0, \delta)$. Thus, $A \subset B_d(a_0, \delta)$. 

Let $C_m$ be a set such that $d(a_0, C_m) = \max_{1 \le i \le n} d(a_0, C_i)$. Then we have $\delta \le f(a_0) \le d(a_0, C_m)$.

Let $y \in B_d(a_0, \delta)$. Then $d(a_0, y) < \delta$. If $y \in C_m$, then $\delta \le d(a_0, C_m) \le d(a_0, y) < \delta$, which is a contradiction. Thus, $y \notin C_m$, so that $A \subset B_d(a_0, \delta) \subset X - C_m = O_m \in \mathcal{U}$. This shows that $\delta$ is a Lebesgue number for $\mathcal{U}$. $\blacksquare$

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.