---
title: "Limit of Complex Functions"
author: "Youmin Chun"
date: "2026-07-24 00:00:08"
categories: 
  - Math > Complex Analysis
---

## Definition
Let $f: D \to \mathbb{C}$ be a complex function defined on a domain $D \subset \mathbb{C}$. We say that $\lim_{z \to z_0} f(z) = w_0$ if

$$\forall \varepsilon > 0, \exists \delta > 0 \text{ such that } 0 < |z - z_0| < \delta \implies |f(z) - w_0| < \varepsilon.$$

## Theorem 1
**(i)** When a limit of a function $f(z)$ exists at a point $z_0$, it is unique. 

**(ii)** Suppose that $f(z) = u(x, y) + iv(x, y) (z = x + iy)$ and $z_0 = x_0 + iy_0, w_0 = u_0 + iv_0$. Then

$$\begin{gather*}
\lim_{(x, y) \to (x_0, y_0)} u(x, y) = u_0 \quad \text{and} \quad \lim_{(x, y) \to (x_0, y_0)} v(x, y) = v_0 \iff \lim_{z \to z_0} f(z) = w_0.
\end{gather*}
$$

### Proof
**(ii)** 

$(\Longrightarrow)$

Let $\varepsilon > 0$. Since $u(x, y) \to u_0$ and $v(x, y) \to v_0$ as $(x, y) \to (x_0, y_0)$, there exist $\delta_1 > 0$ and $\delta_2 > 0$ such that

$$\begin{gather*}
0 < \sqrt{(x - x_0)^2 + (y - y_0)^2} < \delta_1 \implies \vert u(x, y) - u_0\vert < \frac{\varepsilon}{2} \\
0 < \sqrt{(x - x_0)^2 + (y - y_0)^2} < \delta_2 \implies \vert v(x, y) - v_0\vert < \frac{\varepsilon}{2}.
\end{gather*}$$

Take $\delta = \min \{ \delta_1, \delta_2 \}$. Note that

$$\vert z - z_0 \vert = \sqrt{(x - x_0)^2 + (y - y_0)^2}.$$

For $z \in N_{\delta}(z_0) \setminus \{ z_0 \}$, we have

$$\begin{align*}
\vert f(z) - w_0 \vert &= \vert u(x, y) - u_0 + i(v(x, y) - v_0) \vert \\
&\le \vert u(x, y) - u_0 \vert + \vert v(x, y) - v_0 \vert \\
&\le \frac{\varepsilon}{2} + \frac{\varepsilon}{2} = \varepsilon,
\end{align*}$$

so that $\lim_{z \to z_0} f(z) = w_0$.

($\Longleftarrow$)

Let $\varepsilon > 0$. Since $\lim_{z \to z_0} f(z) = w_0$, there exists $\delta > 0$ such that

$$0 < \vert z - z_0 \vert < \delta \implies \vert f(z) - w_0 \vert < \varepsilon.$$

For $(x, y)$ such that $0 < \sqrt{(x - x_0)^2 + (y - y_0)^2} < \delta$, we have

$$\vert u(x, y) - u_0 \vert \le \vert f(z) - w_0 \vert < \varepsilon.$$

Thus, $\lim_{(x, y) \to (x_0, y_0)} u(x, y) = u_0$. Similarly, we can show that $\lim_{(x, y) \to (x_0, y_0)} v(x, y) = v_0$. $\blacksquare$

## Theorem 2
Suppose that $\displaystyle \lim_{z \to z_0} f(z) = w_0$ and $\displaystyle \lim_{z \to z_0} g(z) = w_1$. Then the followings hold:

**(i)** $\displaystyle \lim_{z \to z_0} [f(z) + cg(z)] = w_0 + cw_1$

**(ii)** $\displaystyle \lim_{z \to z_0} [f(z) - g(z)] = w_0 - w_1$

**(iii)** $\displaystyle \lim_{z \to z_0} [f(z) g(z)] = w_0 w_1$

**(iv)** $\displaystyle \lim_{z \to z_0} \frac{f(z)}{g(z)} = \frac{w_0}{w_1}, \quad \text{provided } w_1 \ne 0.$

**(v)** $\displaystyle \lim_{z \to z_0} \overline{f(z)} = \overline{f(z_0)}$

# Reference
- Brown, James Ward, & Churchill, Ruel V. (2017). Complex Variables and Applications (9th ed.). McGraw-Hill.