---
title: "Vector Space"
author: "Youmin Chun"
date: "2026-09-04 00:00:01"
description: "벡터공간에 대해서 설명한다."
categories: 
  - Math > Linear Algebra
---

# Definition
***A vector space $V$ over a field $F$*** consists of a nonempty set on which two binary operations $+: V \times V \to V$ and $\cdot : F \times V \to V$ (called ***addition*** and ***scalar multiplication***, respectively) are defined such that the following conditions hold:

**(i)** $x + y = y + x, \forall x, y \in V$,

**(ii)** $(x+y)+z=x+(y+z), \forall x, y, z \in V$,

**(iii)** $\exists \,\mathbf{0} \in V$ such that $x+\mathbf{0}=x, \forall x \in V$,

**(iv)** $\forall x \in V, \exists \,y \in V$ such that $x+y=\mathbf{0}$ (We denote $y = -x$)

**(v)** $1 \cdot x = x, \forall x \in V$ where $1 \in F$,

**(vi)** $(ab)x = a(bx), \forall a, b \in F$ and $\forall x \in V$,

**(vii)** $a(x+ y) = ax + ay, \forall a \in F$ and $\forall x, y V$,

**(viii)** $(a + b)x = ax + bx, \forall a, b \in F$ and $\forall x \in V$,

We call an elemetnt $v$ in $V$ a ***vector*** and an element $a$ in $F$ a ***scalar***.

선형대수학을 배우기 전까지는 벡터란 보통 크기와 방향을 모두 가지는 값 정도로 정의하고 화살표를 그려서 표기했다. 이때 벡터가 가지는 여러가지 성질들이 있었는데, 이제는 선후관계를 뒤집어서 이런 성질들을 가지는 원소들을 모두 모아놓은 집합을 벡터공간이라고 정의하고, 이 집합의 원소를 벡터라고 부른다. 앞으로 특별한 일이 없는 이상 벡터공간을 언급할 때 필드 $F$는 생략한다.

## Proposition
Let $V$ be a vector space. Then the followings hold:

**(i)** If $x, y, z \in V$ such that $x + z = y + z$, then $x = y$.

**(ii)** If $x+y = y$ for some $y \in V$, then $x = \mathbf{0}$.

**(iii)** $0x = \mathbf{0}, \forall x \in V$.

**(iv)** $a\mathbf{0} = \mathbf{0}, \forall a \in F$.

**(v)** $(-a)x = -(ax) = a(-x), \forall x \in V$ and $\forall a \in F$.

**(vi)** $\exists ! \mathbf{0} \in V$.

**(vii)** $\forall x \in V, \exists ! (-x) \in V$.

(vi), (vii)로부터 덧셈에 대한 항등원과 역원이 유일함을 얻고, (v)를 통해 $-x = (-1)x$로 사용할 수 있음이 보장된다.

### Proof
**(i)** 

$$\begin{align*}
x &= x + \mathbf{0} \\
&= x + z - z \\
&= y + z - z \\
&= y + \mathbf{0} \\
&= y
\end{align*}$$

**(ii)** Suppose that $x + y = y$ for some $y \in V$. Since $x + y = y = \mathbf{0} + y$ and by (i), we have $x = \mathbf{0}$.

**(iii)** 

$$\begin{align*}
0x &= (0 + 0)x \\
&= 0x + 0 \cdot x \\
&\Longrightarrow 0x = \mathbf{0} \\
&\text{by (ii)}
\end{align*}$$

**(iv)** 

$$\begin{align*}
a\mathbf{0} &= a(\mathbf{0} + \mathbf{0}) \\
&= a\mathbf{0} + a\mathbf{0} \\
&\Longrightarrow a\mathbf{0} = \mathbf{0} \\
&\text{by (ii)}
\end{align*}$$

**(v)** 

$$\begin{align*}
\mathbf{0} &= ax + [-(ax)] \\
&= 0x \\
&= (a + (-a))x \\
&= ax + (-a)x \\
&\Longrightarrow -(ax) = (-a)x \\
&\text{and} \\
\mathbf{0} &= a(x + (-x)) \\
&= ax + a(-x) \\
&\Longrightarrow a(-x) = -(ax)
\end{align*}$$

**(vi)** Suppose that there are two zero vectors $\mathbf{0}_1$ and $\mathbf{0}_2$. Then $\mathbf{0}_1 = \mathbf{0}_1 + \mathbf{0}_2 = \mathbf{0}_2$.

**(vii)** Suppose that for each $x \in V$, there are two inverses $-x_1$ and $-x_2$. Then 

$$\begin{align*}
-x_1 &= -x_1 + \mathbf{0} \\
&= -x_1 + x - x_2 \\
&= \mathbf{0} - x_2 \\
&= -x_2
\end{align*}$$ $\blacksquare$

# Reference
- S. H. Friedberg, A. J. Insel, and L. E. Spence, Linear Algebra, 4th ed. (Pearson New International Edition), Pearson, 2013.