---
title: "Subspace Topology"
author: "Youmin Chun"
date: "2026-07-10"
categories: 
  - Math > Topology
---

## Theorem 1
Let $(X, \mathscr{T})$ be a topological space and let $Y \subset X$. 

**(i)** The collection

$$\mathscr{T}_Y = \{ Y \cap U \mid U \in \mathscr{T} \}$$

is a topology on $Y$. We call $\mathscr{T}_Y$ the ***subspace topology*** on $Y$, and call $(Y, \mathscr{T}_Y)$ a ***subspace*** of $(X, \mathscr{T})$.

**(ii)** If $\mathscr{B}$ is a basis for $\mathscr{T}$, then

$$\mathscr{B}_Y = \{ Y \cap B \mid B \in \mathscr{B} \}$$

is a basis for $\mathscr{T}_Y$.

### Proof
**(i)** Since $\emptyset = Y \cap \emptyset \in \mathscr{T}_Y$ and $Y = Y \cap X \in \mathscr{T}_Y$, the first condition is satisfied.

Let $\{ U _ {\alpha} \} \subset \mathscr{T}_Y$. Since each $U _ {\alpha} \in \mathscr{T}_Y$, we have $U _ {\alpha} = Y \cap V _ {\alpha}$ for some $V _ {\alpha} \in \mathscr{T}$, for each $\alpha$. Then

$$\bigcup U _ {\alpha} = \bigcup (Y \cap V _ {\alpha}) = Y \cap \bigcup V _ {\alpha}.$$

Since $\bigcup V _ {\alpha} \in \mathscr{T}$, we have $\bigcup U _ {\alpha} \in \mathscr{T}_Y$. 

Let $U_1, ..., U_n \in \mathscr{T}_Y$. Then $U_i = Y \cap V_i$ for some $V_i \in \mathscr{T}$, for each $i = 1, ..., n$. Then

$$\bigcap_{i=1}^n U_i = \bigcap_{i=1}^n (Y \cap V_i) = Y \cap \bigcap_{i=1}^n V_i.$$

Since $\bigcap_{i=1}^n V_i \in \mathscr{T}$, we have $\bigcap_{i=1}^n U_i \in \mathscr{T}_Y$. Thus $\mathscr{T}_Y$ is a topology on $Y$. 

**(ii)** Let $U \in \mathscr{T}_Y$. Then $U = Y \cap V$ for some $V \in \mathscr{T}$. Since $\mathscr{B}$ is a basis for $\mathscr{T}$ and $V$ is an open set in $X$, for each $x \in U = Y \cap V$ (so that $x \in V$), $\exists B \in \mathscr{B}$ such that $x \in B \subset V$. Since $x \in Y$, we have $x \in Y \cap B \subset Y \cap V = U$. Since $Y \cap B \in \mathscr{B}_Y$, $\mathscr{B}_Y$ is a basis generating $\mathscr{T}_Y$. $\blacksquare$

## Example
**(i)** Let $\mathscr{T}$ be the standard topology on $\mathbb{R}$, and let $Y = [0, 3] \subset \mathbb{R}$. Then $[0, 1) = Y \cap (-1, 1)$ so is open in $Y$. But $(-1, 1)$ is NOT open in $Y$. 

$\big[(\because)$ If $(-1, 1)$ is open in $Y$, then $(-1, 1) = Y \cap (a, b)$ for some $(a, b) \in \mathscr{T}$. Note that $-0.5 \in (-1, 1)$ but $-0.5 \notin [0, 3] = Y$. $\bigotimes$ Thus $(-1, 1)$ is not open in $Y.\big]$

**(ii)** Let $\mathscr{T}$ be the standard topology on $\mathbb{R}^2$, and let $Y = S^1$. Then each arc without the boundary points is open in $Y$.

## Definition
Let $(X, \mathscr{T})$ be a topological space, and let $(Y, \mathscr{T}_Y)$ be a subspace of $(X, \mathscr{T})$. We say that $U$ is ***open in $Y$*** if $U \in \mathscr{T}_Y$, that is, $U = Y \cap V$ for some $V \in \mathscr{T}$.

## Note
$\mathscr{T}$ and $\mathscr{T}_Y$ are NOT comparable in general. That is, an open set $U \in \mathscr{T}$ is not necessarily open in $Y$, and an open set $V \in \mathscr{T}_Y$ is not necessarily open in $X$.

## Theorem 2
Let $(Y, \mathscr{T}_Y)$ be a subspace of $(X, \mathscr{T})$. If $U$ is open in $Y$ and $Y$ is open in $X$, then $U$ is open in $X$. 

### Proof
Since $U$ is open in $Y$, $U = Y \cap V$ for some $V \in \mathscr{T}$. Since $Y$ is open in $X$ and $\mathscr{T}$ is a topology, $U = Y \cap V$ is open in $X$. $\blacksquare$

## Theorem 3
Let $(X, \mathscr{T}_X)$ and $(Y, \mathscr{T}_Y)$ be topological spaces, and let $A \subset X$ and $B \subset Y$. Let $(X \times Y, \mathscr{T} _ {X \times Y})$ be the product topological space, and let $(A, \mathscr{T}_A)$ and $(B, \mathscr{T}_B)$ be the subspace topologies on $A$ and $B$, respectively. Then the product topology on $A \times B$ is the same as the subspace topology on $A \times B$.

### Proof
Let $\mathscr{T}$ be the product topology on $A \times B$, and let $\mathscr{T}'$ be the subspace topology on $A \times B$. Let $(A \times B) \cap (U \times V)$ be a basis element for $\mathscr{T}'$ where $U \in \mathscr{T}_X$ and $V \in \mathscr{T}_Y$. ($U \times V$ is a basis element of $\mathscr{T} _ {X \times Y}$.) Since 

$$(A \times B) \cap (U \times V) = (A \cap U) \times (B \cap V),$$

and $A \cap U$, $B \cap V$ are basis elements of $\mathscr{T}_A, \mathscr{T}_B$, respectively, $(A \cap U) \times (B \cap V)$ is a basis element for $\mathscr{T}$. Conversely, it is easy to verify that each basis element for $\mathscr{T}$ is also a basis element for $\mathscr{T}'$. Thus the basis for $\mathscr{T}$ and the basis for $\mathscr{T}'$ are the same, which means that $\mathscr{T} = \mathscr{T}'$. $\blacksquare$

## Theorem 4
If $Y$ is a subspace of $X$, and $A$ is a subset of $Y$, then the topology $A$ inherits as a subspace of $Y$ is the same as the topology it inherits as a subspace of $X$.

### Proof
Let $\mathscr{T}_1$ and $\mathscr{T}_2$ be topology $A$ inherits as a subspace of $Y$ and the topology it inherits as a subspace of $X$, respectively.

Let $U \in \mathscr{T}_1$. Then $U = A \cap U_1$ for some open subset $U_1$ of $Y$. Note that $U_1 = Y \cap U_2$ for some open subset $U_2$ of $X$. Then $U = A \cap (Y \cap U_2) = A \cap U_2$, which implies that $U \in \mathscr{T}_2$. 

Let $V \in \mathscr{T}_2$. Then $V = A \cap V_1$ for some open subset $V_1$ of $X$. Note that $V \subset A \subset Y$. Then we have $V = V \cap Y = A \cap (Y \cap V_1)$. Since $Y \cap V_1$ is an open subset of $Y$, it follows that $V \in \mathscr{T}_1$. Thus, $\mathscr{T}_1 = \mathscr{T}_2$. $\blacksquare$

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.