---
title: "Order of Groups"
author: "Youmin Chun"
date: "2026-07-31"
categories: 
  - Math > Abstract Algebra > Group Theory
---

## Definition
- Let $G$ be a group. 

**(i)** The ***order of a group*** $G$ is the number of elements in $G$, denoted by $\vert G \vert$.

**(ii)** The ***order of an element*** $a \in G$ is the order of the cyclic group $\langle a \rangle$. That is, $\vert a \vert = \vert \langle a \rangle \vert$.

## Theorem
- Let $G$ be a finite group, and let $a \in G$. Then

$$\vert a \vert = \vert \langle a \rangle \vert = \min \{ m \in \mathbb{N} \mid a^m = e \}$$

### Proof
Let $n = \min \{ m \in \mathbb{N} \mid a^m = e \}$, that is, $a^n = e$ and $a^k \neq e, \forall 1 \le k < n$. We claim that $\langle a \rangle = \{ e, a, a^2, \cdots, a^{n-1} \}$.

Suppose that $a^i = a^j$ for some $0 \le i < j \le n-1$. Then $a^{j-i} = e$, but it contradicts for the minimality of $n$. $\bigotimes$ Thus $a^i \neq a^j, \forall 0 \le i < j \le n-1$. 

Clearly $\langle a \rangle \supset \{ e, a, a^2, \cdots, a^{n-1} \}$. Let $x \in \langle a \rangle$. Then $x = a^\ell$ for some $\ell \in \mathbb{Z}$. By division algorithm, $\exists q, r \in \mathbb{Z}$ such that $\ell = nq + r$ and $0 \le r \le n-1$. Then we have 

$$x = a^{\ell} = (a^{n})^q a^r = a^r \in \{ e, a, a^2, \cdots, a^{n-1} \}.$$

Thus $\langle a \rangle = \{ e, a, a^2, \cdots, a^{n-1} \}$, so that $\vert a \vert = \vert \langle a \rangle \vert = n = \min \{ m \in \mathbb{N} \mid a^m = e \}$. $\blacksquare$

군의 order는 단순히 군의 원소의 개수를 말하지만, 군의 원소의 order는 그 원소를 생성원으로 하는 순환군의 order로 정의된다. 나아가 이 값은 특별히 $a^m = e$를 만족하는 가장 작은 자연수 $m$으로 주어진다.

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.