---
title: "Approximation"
author: "Youmin Chun"
date: "2026-10-06 00:00:01"
description: "수치해석학에서 근사법(Approximation)에 대해서 살펴본다"
categories: 
  - Math > Numerical Analysis
---

# Best Approximation
구간 $[a, b]$에서 정의된 연속함수 $f$가 주어졌을 때 우리는 $f$를 최대한 잘 근사하는 다항식을 찾으려고 한다. 다시 말해 다항식

$$p^\ast(x) = \argmin_{p \in \mathcal{P}_n} \| f(x) - p(x) \|$$

를 찾으려고 하고, 이러한 $n$차 다항식 $p^\ast$를 **최적근사다항식(best approximation polynomial)**이라고 부른다. 놈은 $L_2$ 놈이 주어진 것으로 간주한다. 이러한 $p^\ast$가 존재함은 이미 증명되어 있으므로, 이 포스트에서는 $p^\ast$를 어떻게 계산할 수 있는지에 대한 방법을 다룬다. 편의를 위해 간단하게 구간을 $[0, 1]$로 두자.

우선 접근할 수 있는 첫번째 방법은 $n$차 다항식 공간 $\mathcal{P}_n$의 기저를 $\{ 1, x, x^2, \dots, x^n \}$로 택하는 것이다. 그러면

$$p^\ast(x) = \sum_{j=0}^n a_j x^j$$

로 둘 수 있고, 우리는

$$G(a_0, \dots, a_n) := \| f(x) - p^\ast(x) \|^2 = \int_0^1 (f(x) - p^\ast(x))^2 dx$$

을 최소화하는 그러한 계수 $a_j$들을 선택하면 된다. 다시 말해 $G$를 $a_j$에 관해 미분했을 때 $0$을 만족하는 $a_j$ 중에서 선택해야 한다. 따라서 $G$를 $a_j$로 미분해주면 다음의 결과를 얻는다.

$$\begin{align*}
0 &= \frac{\partial G}{\partial a_i} \\
&= 2 \int_0^1 \left( f(x) - \sum_{j=0}^n a_j x^j \right) (-x^i) dx \\
&= 2 \sum_{j=0}^n a_j \int_0^1 x^{i+j} dx - 2 \int_0^1 f(x) x^i dx \\
&= 2 \sum_{j=0}^n a_j \frac{1}{i+j+1} - 2 \int_0^1 f(x) x^i dx
\end{align*}$$

이때

$$\alpha_{ij} = \frac{1}{i+j+1}, \quad \beta_i = \int_0^1 f(x) x^i dx$$

라고 두면

$$\sum_{j=0}^n \alpha_{ij} a_j = \beta_i, \quad i = 0, 1, \dots, n$$

를 얻는다. 이는 연립방정식 $Ax = b$의 꼴이며, 따라서 이 방정식을 풀면 계수 $a_j$를 구할 수 있다. 그러나 행렬 $[\alpha_{ij}]$는 행렬의 사이즈가 커질수록 오차가 매우 커지는 ill-conditioned 행렬이다. 때문에 우리는 다른 방법으로 $\mathcal{P}_n$의 기저를 직교기저로 두는 방법을 사용하게 된다.

## Least Square Approximation
그람-슈미트 직교과정(Gram-Schmidt Orthogonalization)에 의해 $\mathcal{P}_n$의 직교기저 $\{ P_0, P_1, \dots, P_n \}$의 존재성이 보장되므로, 우리는

$$p^\ast(x) = \sum_{j=0}^n c_j P_j(x)$$

와 같이 두고 계수 $c_j$를 찾으려고 한다. 이때 다음이 성립한다.

$$\begin{align*}
\| f(x) - p^\ast(x) \|^2 &= \| f(x) \|^2 - 2 \langle f(x), p^\ast(x) \rangle + \| p^\ast(x) \|^2 \\
&= \| f(x) \|^2 - 2 \left\langle f(x), \sum_{j=0}^n c_j P_j(x) \right\rangle + \left \langle \sum_{i=0}^n c_i P_i(x), \sum_{j=0}^n c_j P_j(x) \right \rangle \\
&= \| f(x) \|^2 - 2 \sum_{j=0}^n c_j \langle f(x), P_j(x) \rangle + \sum_{j=0}^n c_j^2 \| P_j(x) \|^2 \\
&= \| f(x) \|^2 + \sum_{j=0}^n \| P_j(x) \|^2 \left( c_j^2 - 2 \frac{c_j \langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2} \right) \\
&= \| f(x) \|^2 + \sum_{j=0}^n \| P_j(x) \|^2\left[ \left( c_j - \frac{\langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2} \right)^2 - \left( \frac{\langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2} \right)^2 \right] \\
&= \| f(x) \|^2 - \sum_{j=0}^n \frac{\langle f(x), P_j(x) \rangle^2}{\| P_j(x) \|^2} + \sum_{j=0}^n \| P_j(x) \|^2\left( c_j - \frac{\langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2} \right)^2
\end{align*}$$

마지막 식이 최소가 되기 위해

$$c_j = \frac{\langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2}$$

로 택하면 된다. 이렇게 얻어지는 다항식

$$p^\ast(x) = \sum_{j=0}^n \frac{\langle f(x), P_j(x) \rangle}{\| P_j(x) \|^2} P_j(x)$$

을 **최소제곱근사다항식(Least Squares Approximation)**이라고 부른다.

# Reference
- K. E. Atkinson and W. Han, Elementary Numerical Analysis, 3rd ed., John Wiley & Sons, 2004.