---
title: "Special Topologies"
date: "2026-07-08"
categories: 
  - Math > Topology
---

## Definition
**(i)** Let $\mathscr{B} = \{ (a, b) \mid a, b \in \mathbb{R} \}$. Then the topology generated by $\mathscr{B}$ is called the ***standard(usual) topology*** on $\mathbb{R}$.

**(ii)** Let $\mathscr{B}' = \{ [a, b) \mid a, b \in \mathbb{R} \}$. Then the topology generated by $\mathscr{B}'$ is called the ***lower limit topology*** on $\mathbb{R}$. We denote $\mathbb{R} _{\ell} = (\mathbb{R}, \mathscr{T} _{\mathscr{B}'})$.

**(iii)** Let $\mathscr{B}'' = \{ (a, b] \mid a, b \in \mathbb{R} \}$. Then the topology generated by $\mathscr{B}''$ is called the ***lower limit topology*** on $\mathbb{R}$. We denote $\mathbb{R} _{u} = (\mathbb{R}, \mathscr{T} _{\mathscr{B}''})$.

**(iv)** Let $\mathscr{B}_K = \{ (a,b), (a, b) \setminus K \mid a, b \in \mathbb{R} \}$ where $K = \{ \frac{1}{n} \mid n \in \mathbb{N} \}$. Then the topology generated by $\mathscr{B}_K$ is called the ***$K$-topology*** on $\mathbb{R}$. We denote $\mathbb{R}_{K} = (\mathbb{R}, \mathscr{T} _{\mathscr{B}_K})$.

**(v)** The collection $\mathscr{T}_f = \\{ U \subset \mathbb{R} \mid \mathbb{R} \setminus U \text{ is either finite or } \mathbb{R} \\}$ of subsets of $\mathbb{R}$ is called the ***cofinite topology*** or the ***finite complement topology***. 

## Theorem
**(i)** $\mathscr{T} \subsetneq \mathscr{T} _{\ell}$

**(ii)** $\mathscr{T} \subsetneq \mathscr{T} _{u}$

**(iii)** $\mathscr{T} \subsetneq \mathscr{T} _{K}$

**(iv)** $\mathscr{T} _{\ell}$ and $\mathscr{T} _{K}$ are NOT comparable.

**(v)** $\mathscr{T} _K \subsetneq \mathscr{T} _u$

**(vi)** $\mathscr{T} \subsetneq \mathscr{T}_f$

### Proof
We will use the Theorem 4.

**(i)** 

If $x \in \mathbb{R}$, then $\exists (a, b) \in \mathscr{B}$ such that $x \in (a, b)$. Since $x \in [x, b) \in \mathscr{B}'$ and $[x, b) \subset (a, b)$, we have $\mathscr{T} \subset \mathscr{T} _{\ell}$. 

Suppose that for $[a, b) \in \mathscr{B}'$, if $x \in [a, b)$, then $\exists (a', b') \in \mathscr{B}$ such that $x \in (a', b') \subset [a, b)$. Since $a \in [a, b)$, we have $a \in (a', b') \subset [a, b)$ for some $(a', b') \in \mathscr{B}$. Then we have $a \le a' < a < b' \le b$. $\bigotimes$ Thus $\mathscr{T} \subsetneq \mathscr{T} _{\ell}$.  

**(ii)** 

If $x \in \mathbb{R}$, then $\exists (a, b) \in \mathscr{B}$ such that $x \in (a, b)$. Since $x \in (a, b) \in \mathscr{B}''$, we have $\mathscr{T} \subset \mathscr{T} _{K}$. 

Suppose that for $(0, 1) \setminus K \in \mathscr{B}''$, if $x \in (-1, 1) \setminus K$, then $\exists (a, b) \in \mathscr{B}$ such that $x \in (a, b) \subset (-1, 1) \setminus K$. Since $0 \in (-1, 1) \setminus K$, we have $0 \in (a, b) \subset (-1, 1) \setminus K$ for some $(a, b) \in \mathscr{B}$. Since $0 < b$, we have $\frac{1}{n} < b$ for some $n \in \mathbb{N}$ by Archimedean Property, which contradicts to $(a, b) \subset (-1, 1) \setminus K$. $\bigotimes$ Thus $\mathscr{T} \subsetneq \mathscr{T} _{K}$. 

**(iii)** 
Suppose that for $(0, 1) \setminus K \in \mathscr{B}''$, if $x \in (-1, 1) \setminus K$, then $\exists [a, b) \in \mathscr{B}'$ such that $x \in [a, b) \subset (-1, 1) \setminus K$. Since $0 \in (-1, 1) \setminus K$, we have $0 \in [a, b) \subset (-1, 1) \setminus K$ for some $[a, b) \in \mathscr{B}'$. Since $0 < b$, we have $\frac{1}{n} < b$ for some $n \in \mathbb{N}$ by Archimedean Property, which contradicts to $[a, b) \subset (-1, 1) \setminus K$. $\bigotimes$ Thus $\mathscr{T} _{K} \not\subset \mathscr{T} _{\ell}$. 

Suppose that for $[a, b) \in \mathscr{B}'$, if $x \in [a, b)$, then $\exists B'' \in \mathscr{B}''$ such that $x \in B'' \subset [a, b)$. Since $a \in [a, b)$, we have $a \in B'' \subset [a, b)$ for some $B'' \in \mathscr{B}''$. Note that $B'' = (a', b')$ or $(a', b') \setminus K$. For any case, we have $a \le a' < a < b' \le b$. $\bigotimes$ Thus $\mathscr{T} _{\ell} \not\subset \mathscr{T} _{K}$, and therefore, $\mathscr{T} _{\ell}$ and $\mathscr{T} _{K}$ are NOT comparable. $\blacksquare$

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.