---
title: "Basis of Topology"
date: "2026-07-08"
categories: 
  - Math > Topology
---

## Definition
A ***basis*** on a set $X$ is a collection $\mathscr{B}$ of subsets of $X$ such that

**(i)** For each $x \in X$, there exists $B \in \mathscr{B}$ such that $x \in B$.

**(ii)** If $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B}$, then there exists $B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2$.

## Example
**(i)** The collection 

$$\mathscr{B}_1 = \{ (a, b) \mid a, b \in \overline{\mathbb{R}} \}$$

of open intervals in $\mathbb{R}$ is a basis for a topology on $\mathbb{R}$, but it is **NOT** a topology on $\mathbb{R}$.

**(ii)** Let $X$ be a set. The collection

$$\mathscr{B}_2 = \{ \{ x \} \mid x \in X \}$$

is a basis for the discrete topology on $X$. 

## Theorem 1
Let $\mathscr{B}$ be a basis on a set $X$. Then the collection 

$$\mathscr{T} _ { \mathscr{B} } = \{ U \subset X \mid \forall x \in U, \exists B_x \in \mathscr{B} \, [x \in B_x \subset U] \}$$

is a topology on $X$. In this case, we say that $\mathscr{T} _ { \mathscr{B} }$ is ***the topology generated by a basis $\mathscr{B}$***, or $\mathscr{B}$ is ***a basis for a topology*** on $X$. 

즉 부분집합 $U \subset X$가 기저 집합들에 대해서 오픈 셋의 성질을 만족하도록 컬렉션을 구성하면 자연스럽게 위상 공간을 만들 수 있고, 이를 기저 $\mathscr{B}$가 생성하는 위상 공간이라고 부른다.

### Proof
If $U = \emptyset$, then it satisfies the condition vacuously, which means that $\emptyset \in \mathscr{T} _ { \mathscr{B} }$. Let $U = X$ and let $x \in U$. Since $\mathscr{B}$ is a basis, $\exists B \in \mathscr{B}$ such that $x \in B \subset X = U$, so that $X \in \mathscr{T} _ { \mathscr{B} }$.

Let $\\{ U_\alpha \\} \subset \mathscr{T} _ { \mathscr{B} }$. Clearly $\bigcup U_{\alpha} \subset X$. If $x \in \bigcup U_{\alpha}$, then $x \in U_{\alpha}$ for some $\alpha$. Since each $U_{\alpha}$ is in $\mathscr{T} _ { \mathscr{B} }$, there exists $B_x \in \mathscr{B}$ such that $x \in B_x \subset U_{\alpha} \subset \bigcup U_{\alpha}$. Thus the union of $\\{ U_{\alpha} \\}$ is an element of $\mathscr{T} _ { \mathscr{B} }$.

We show the final condition by induction. Let $U_1, U_2 \in \mathscr{T} _ { \mathscr{B} }$. Let $x \in U_1 \cap U_2$. Since $U_1$ and $U_2$ are the elements of $\mathscr{T} _ { \mathscr{B} }$, there exists $B_1, B_2 \in \mathscr{B}$ such that $x \in B_1 \subset U_1$ and $x \in B_2 \subset U_2$. Then $x \in B_1 \cap B_2 \subset U_1 \cap U_2$. Since $\mathscr{B}$ is a basis, $\exists B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2 \subset U_1 \cap U_2$. Thus $U_1 \cap U_2 \in \mathscr{T} _ { \mathscr{B} }$.

Suppose that $U_1 \cap \cdots \cap U_{n} \in \mathscr{T} _ { \mathscr{B} }$ for any $U_1, ..., U_n \in \mathscr{T} _ { \mathscr{B} }$. Let $U_{n+1} \in \mathscr{T} _ { \mathscr{B} }$. Since we have shown the intersection of two sets in $\mathscr{T} _ { \mathscr{B} }$ is also an element of $\mathscr{T} _ { \mathscr{B} }$, we have $U_1 \cap \cdots \cap U_{n+1} \in \mathscr{T} _ { \mathscr{B} }$. Thus $\mathscr{T} _ { \mathscr{B} }$ is a topology on $X$. $\blacksquare$

## Remark 1
**(i)** Each basis element $B$ of $\mathscr{B}$ is an element of $\mathscr{T} _ { \mathscr{B} }$.

**(ii)** Every topology on a set $X$ has a basis generating itself. In particular, $\mathscr{T}$ is a basis for itself, that is, $\mathscr{T} = \mathscr{T} _ { \mathscr{T} }$.

$\big[(\because)$ Let $\mathscr{T}$ be a topology on a set $X$. For each $x \in X$, $x \in X \in \mathscr{T}$. If $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{T}$, then $x \in B_1 \cap B_2 \in \mathscr{T}$. Thus $\mathscr{T}$ is a basis for a topology on $X$. 

Let $U \in \mathscr{T}$. If $x \in U$, then $x \in U \subset U$, which means that $U \in \mathscr{T} _ {\mathscr{T}}$. Thus $\mathscr{T} \subset \mathscr{T} _ {\mathscr{T}}$.

Let $U \in \mathscr{T} _ {\mathscr{T}}$. If $x \in U$, then $\exists B_x \in \mathscr{T}$ such that $x \in B_x \subset U$. We claim that $\bigcup_{x \in U} B_x = U$. 

$\big[(\because)$ Since each $B_x \subset U$, we have $\bigcup_{x \in U} B_x \subset U$. If $x \in U$, then $\exists B_x \in \mathscr{T}$ such that $x \in B_x \subset U$, which means that $x \in \bigcup_{x \in U} B_x$. Thus $U \subset \bigcup_{x \in U} B_x.\big]$

Therefore $\bigcup_{x \in U} B_x = U$. Since $\mathscr{T}$ is a topology on $X$, $\bigcup_{x \in U} B_x \in \mathscr{T}$, which means that $U \in \mathscr{T}$. Thus $\mathscr{T} _ {\mathscr{T}} \subset \mathscr{T}$. 

Therefore $\mathscr{T} = \mathscr{T} _ {\mathscr{T}}$. $\blacksquare \big]$

**(iii)** But every basis on a set $X$ need **NOT** be a topology on $X$ in general. The counterexample is $\mathscr{B}_1$ in Example **(i)**.

## Theorem 2
Let $\mathscr{B}$ be a basis on a set $X$, and let $\mathscr{T} _ { \mathscr{B} }$ be the topology on $X$ generated by $\mathscr{B}$. Then 

$$\mathscr{T} _ { \mathscr{B} } = \left\{ \bigcup_{U \in \mathcal{A}} U \,\, \Bigg \vert \,\, \mathcal{A} \subset \mathscr{B}   \right\}$$

선형대수에서 벡터 공간의 임의의 원소는 기저벡터들의 선형 결합으로 표현할 수 있었듯이, 기저 $\mathscr{B}$가 생성하는 위상 공간의 임의의 오픈 셋은 기저 집합들의 합집합으로 표현할 수 있다. 

### Proof 
Let us denote 

$$T = \left\{ \bigcup_{U \in \mathcal{A}} U \,\, \Bigg \vert \,\, \mathcal{A} \subset \mathscr{B} \right\}.$$

Let $\displaystyle \bigcup_{U \in \mathcal{A}} U \in T$ where $\mathcal{A} \subset \mathscr{B}$. Since each $U \in \mathscr{B}$ is an element of $\mathscr{T} _ { \mathscr{B} }$ and $\mathscr{T} _ { \mathscr{B} }$ is a topology on $X$, the union $\displaystyle \bigcup_{U \in \mathcal{A}} U$ belongs to $\mathscr{T} _ { \mathscr{B} }$, which means that $T \subset \mathscr{T} _ { \mathscr{B} }$.

Let $U \in \mathscr{T} _ { \mathscr{B} }$. If $x \in U$, then $\exists B_x \in \mathscr{B}$ such that $x \in B_x \subset U$. Note that 

$$U = \bigcup_{x \in U} B_x.$$

Since $\\{ B_x \in \mathscr{B} \mid x \in U \\}$ is a subcollection of $\mathscr{B}$, we have $U \in T$, which means that $\mathscr{T} _ { \mathscr{B} } \subset T$. Thus $T = \mathscr{T} _ { \mathscr{B} }. \blacksquare$ 

## Theorem 3
Let $(X, \mathscr{T})$ be a topological space, and let $\mathscr{B}$ be a subcollection of $\mathscr{T}$. TFAE.

**(i)** $\mathscr{B}$ is a basis for $\mathscr{T}$. That is, $\mathscr{T} = \mathscr{T} _ { \mathscr{B} }$.

**(ii)** For each $U \in \mathscr{T}$ and $x \in U$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$.

Theorem 1은 어떤 기저가 만들어내는 위상에 대해서 언급했다면, Theorem 3은 주어진 위상으로부터 컬렉션 $\mathscr{B}$를 위와 같이 정의하면 기저를 만들어낼 수 있음을 언급한다. 

### Proof
**(i)** $\implies$ **(ii)**

By definition of $\mathscr{T} _ { \mathscr{B} }$, it is clear.

**(ii)** $\implies$ **(i)**

First, we show that $\mathscr{B}$ is a basis.

Let $x \in X$. Since $\mathscr{T}$ is a topology on $X$, $X \in \mathscr{T}$. Thus $\exists U \in \mathscr{T}$ such that $x \in U$. By assumption, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$. 

Let $x \in B_1 \cap B_2$ for $B_1, B_2 \in \mathscr{B}$. Since $B_1, B_2 \in \mathscr{T}$, so that $B_1 \cap B_2 \in \mathscr{T}$, $\exists B_3 \in \mathscr{B}$ such that $x \in B_3 \subset B_1 \cap B_2$. Thus $\mathscr{B}$ is a basis.

Next, we show that $\mathscr{T} = \mathscr{T} _ { \mathscr{B} }$. 

Let $U \in \mathscr{T}$. If $x \in U$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$ by assumption. Thus $U \in \mathscr{T} _ { \mathscr{B} }$ by definition of $\mathscr{T} _ { \mathscr{B} }$.

Let $U \in \mathscr{T} _ { \mathscr{B} }$. By Theorem 2, $U = \bigcup_{K \in \mathcal{A}} K$ for some $\mathcal{A} \subset \mathscr{B}$. Since $\mathscr{B} \subset \mathscr{T}$, we have $U \in \mathscr{T}$.

Thus $\mathscr{T} = \mathscr{T} _ { \mathscr{B} }. \blacksquare$

## Theorem 4
Let $\mathscr{B}$ and $\mathscr{B}'$ be bases for topologies $\mathscr{T} _ { \mathscr{B} }$ and $\mathscr{T} _ { \mathscr{B}' }$, respectively, on a set $X$. TFAE.

**(i)** $\mathscr{T} _ { \mathscr{B} } \subset \mathscr{T} _ { \mathscr{B}' }$, that is, $\mathscr{T} _ { \mathscr{B}' }$ is finer than $\mathscr{T} _ { \mathscr{B} }$.

**(ii)** For each $x \in X$ and $B \in \mathscr{B}$ such that $x \in B$, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B$.

정리 자체는 한 방향의 포함 관계에 대해서만 말하고 있지만, 만약 두 방향 모두를 위 명제를 통해 보일 수 있다면 우리는 두 위상이 서로 같음을 보이게 된다. 

### Proof
**(i)** $\implies$ **(ii)**

Let $x \in X$ and let $B \in \mathscr{B}$ such that $x \in B$. Since $\mathscr{T} _ { \mathscr{B} } \subset \mathscr{T} _ { \mathscr{B}' }$, we have $B \in \mathscr{T} _ { \mathscr{B}' }$. By definition of $\mathscr{T} _ { \mathscr{B}' }$, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B$. 

**(ii)** $\implies$ **(i)**

Let $U \in \mathscr{T} _ { \mathscr{B} }$. For each $x \in X$, $\exists B \in \mathscr{B}$ such that $x \in B \subset U$ by definition of $\mathscr{T} _ { \mathscr{B} }$. By assumption, $\exists B' \in \mathscr{B}'$ such that $x \in B' \subset B \subset U$. Thus $U \in \mathscr{T} _ { \mathscr{B}' }$. Hence $\mathscr{T} _ { \mathscr{B} } \subset \mathscr{T} _ { \mathscr{B}' }. \blacksquare$ 

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.