---
title: "Group"
author: "Youmin Chun"
date: "2026-06-25 00:00:03"
description: "대수학의 군(Group)에 대해서 설명하고 군에서 성립하는 여러 결과들에 대해서 소개한다."
categories: 
  - Math > Abstract Algebra > Group Theory
---

## Definition
**(i)** A ***group*** $\langle G, \ast \rangle$ is a binary algebraic structure which satisfies the following conditions:

- $(a \ast b) \ast c = a \ast (b \ast c), \forall a, b, c \in G$.

- $\exists e \in G$ such that $e \ast a = a \ast e = a, \forall a \in G$.

- $\forall a \in G$, $\exists b \in G$ such that $a \ast b = e = b \ast a$.

**(ii)** A group $\langle G, \ast \rangle$ is called an ***abelian group*** if $\ast$ is commutative.

## Example
**(i)** $\langle \mathbb{Z}, + \rangle, \langle \mathbb{Q}, + \rangle$, and $\langle \mathbb{R}, + \rangle$ are abelian groups.

**(ii)** $\langle \mathbb{Q}^{\ast}, \cdot \rangle$ and $\langle \mathbb{R}^{\ast}, \cdot \rangle$ are abelian groups.

**(iii)** $\langle \mathbb{R}^{m \times n}, + \rangle$ is an abelian group.

**(iv)** $\langle GL(n, \mathbb{R}), \cdot \rangle$ and $\langle SL(n, \mathbb{R}), \cdot \rangle$ are not abelian groups.

## Remark 1
정수군 $\langle \mathbb{Z}, + \rangle$에서 정의된 일차방정식 $5 + x = 2$은 군의 정의에 의해 다음과 같이 풀 수 있다.

$$\begin{align*}
5 + x &= 2 \\
-5 + (5 + x) &= -5 + 2 \\
(-5 + 5) + x &= -3 \quad \text{(associativity)} \\
0 + x & = -3 \quad \text{(inverse)} \\
x &= -3 \quad \text{(identity)}
\end{align*}$$

마찬가지로 유리수군 $\langle \mathbb{Q}, \cdot \rangle$에서 정의된 일차방정식 $2 \cdot x = 3$은 다음과 같이 풀 수 있다.

$$\begin{align*}
2 \cdot x &= 3 \\
\frac{1}{2} \cdot (2 \cdot x) &= \frac{1}{2} \cdot 3 \\
\left(\frac{1}{2} \cdot 2\right) \cdot x &= \frac{3}{2} \quad \text{(associativity)} \\
1 \cdot x &= \frac{3}{2} \quad \text{(inverse)} \\
x &= \frac{3}{2} \quad \text{(identity)}
\end{align*}$$

이와 같이 일차방정식을 풀려면 위와 같은 세 가지 조건, 즉 결합성과 항등원, 역원의 존재성이 필요하고 이 조건만을 가지고 있는 대수적 구조가 군이라고 할 수 있다. 

## Cancellation Law
- Let $\langle G, \ast \rangle$ be a group. Then ***the left and right cancellation laws*** hold:

**(i)** $a \ast b = a \ast c \implies b = c, \forall a, b, c \in G$.

**(ii)** $b \ast a = c \ast a \implies b = c, \forall a, b, c \in G$.

### Proof
**(i)** Let $g$ be the inverse of $a$. Then we have 

$$\begin{align*}
b &= e \ast b \\
&= (g \ast a) \ast b \\
&= g \ast (a \ast b) \\
&= g \ast (a \ast c) \\
&= (g \ast a) \ast c \\
&= e \ast c \\
&= c.
\end{align*}$$

**(ii)** Similarly, we can prove (ii). $\blacksquare$

## Existence and Uniqueness of The Solution of Linear Equations
- Let $\langle G, \ast \rangle$ be a group, and let $a, b \in G$. Then $\exists ! x, y \in G$ such that 

$$a \ast x = b \quad \text{and} \quad y \ast a = b.$$

즉 군이 주어지면 군 안에서 일차방정식의 해는 항상 유일하게 존재한다. 

### Proof
Let $g$ be the inverse of $a$. If we let $x = g \ast b$, then

$$\begin{align*}
a \ast x &= a \ast (g \ast b) \\
&= (a \ast g) \ast b \\
&= e \ast b \\
&= b,
\end{align*}$$

so that $x = g \ast b$ is a solution to $a \ast x = b$. 

Suppose that $x_1$ and $x_2$ are solutions to $a \ast x = b$. Then we have 

$$\begin{align*}
a \ast x_1 = b = a \ast x_2 \\ 
\implies x_1 = x_2
\end{align*}$$

by the cancellation law. Thus there uniquely exists $x \in G$ such that $a \ast x = b$. $\blacksquare$

## Uniquness of The Identity and The Inverse
- Let $\langle G, \ast \rangle$ be a group.

**(i)** $\exists ! e \in G$ such that $e \ast a = a \ast e = a, \forall a \in G$.

**(ii)** For each $a \in G$, $\exists ! b \in G$ such that $a \ast b = e = b \ast a$. In this case, we denote $b$ by $a^{-1}$.

### Proof
**(i)** Since any binary algebraic structure has at most one identity element, there uniquely exists the identity element of $\langle G, \ast \rangle$.

**(ii)** Since $\langle G, \ast \rangle$ is a group, each $a$ in $G$ has its inverse element in $G$. Let $b_1, b_2 \in G$ be such that 

$$a \ast b_1 = e = b_1 \ast a \quad \text{and} \quad a \ast b_2 = e = b_2 \ast a.$$

Then we have 

$$\begin{align*}
b_1 &= b_1 \ast e \\
&= b_1 \ast (a \ast b_2) \\
&= (b_1 \ast a) \ast b_2 \\
&= e \ast b_2 \\
&= b_2. \blacksquare
\end{align*}$$

## Socks Shoes Property
- Let $\langle G, \ast \rangle$ be a group, and let $a, b \in G$. Then 

$$(a \ast b)^{-1} = b^{-1} \ast a^{-1}$$

### Proof
Since $G$ is a group, we have 

$$\begin{align*}
(a \ast b) \ast (b^{-1} \ast a^{-1}) &= a \ast (b \ast b^{-1}) \ast a^{-1} \\
&= a \ast e \ast a^{-1} \\
&= a \ast a^{-1} \\
&= e.
\end{align*}$$

Similarly, $(b^{-1} \ast a^{-1}) \ast (a \ast b) = e$ holds. $\blacksquare$

## Remark 2
어떤 대수 구조 $\langle G, \ast \rangle$가 군이 되려면 결합법칙이 성립하고 항등원, 역원이 존재해야 한다. 좀 더 정확하게 적으면, 왼쪽에 대한 항등원과 역원, 오른쪽에 대한 항등원과 역원이 모두 존재해야 한다. 그런데 실제로는 대수 구조 $\langle G, \ast \rangle$가 결합법칙이 성립하고 왼쪽에 대한 항등원, 역원만 존재하면 오른쪽에 대한 항등원과 역원이 존재하고 그것들은 왼쪽에 대한 것들과 동일함을 증명할 수 있다. (반대도 마찬가지이다.) 즉 군의 정의는 한쪽에 대한 존재성으로 약화시킬 수 있다.

증명은 다음과 같다. $\langle G, \ast \rangle$는 이항 연산 $\ast$가 주어진 집합 $G$를 가리키고, 결합법칙이 성립하며 좌항등원, 좌역원이 존재한다고 하자. 즉 다음이 성립한다.

**(i)** $\exists e \in G$ such that $e \ast x = x, \forall x \in G$.

**(ii)** $\forall x \in G, \exists x^{-1} \in G$ such that $x^{-1} \ast x = e$.

우선 우역원이 존재하고 그것은 좌역원과 같음을 보이자. $G$ 안의 임의의 원소 $x$에 대하여 좌역원 $x^{-1}$이 존재하고, $x^{-1}$ 또한 $G$의 원소이므로 좌역원 $y$가 존재한다. 이에 대해서 다음이 성립한다.

$$\begin{align*}
x^{-1} \ast (x \ast x^{-1}) &= (x^{-1} \ast x) \ast x^{-1} \\
&= e \ast x^{-1} \\
&= x^{-1}
\end{align*}
$$

양변의 왼쪽에 $y$의 연산을 취하면 다음과 같다.

$$
\begin{align*}
\implies y \ast (x^{-1} \ast (x \ast x^{-1})) &= y \ast x^{-1}\\
&= e
\end{align*}$$

한편 

$$\begin{align*}
y \ast (x^{-1} \ast (x \ast x^{-1})) &= (y \ast x^{-1}) \ast (x \ast x^{-1}) \\
&= e \ast (x \ast x^{-1}) \\
&= x \ast x^{-1}
\end{align*}$$

이 성립하므로 $x \ast x^{-1} = e$를 얻는다. 즉 좌항등원과 좌역원이 존재한다면 우역원도 존재하고, 우역원의 값은 좌역원의 값과 동일하다.

이제 우항등원이 존재하고 그 값은 좌항등원과 같음을 보이자. $G$ 안의 임의의 원소 $x$에 대하여 다음이 성립한다.

$$\begin{align*}
x \ast e &= x \ast (x^{-1} \ast x) \\
&= (x \ast x ^{-1}) \ast x \\
&= e \ast x \\
&= x
\end{align*}$$

따라서 우항등원은 존재하고 그 값은 좌항등원과 같다.

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.