---
title: "Fixed Point Iteration"
author: "Youmin Chun"
date: "2026-09-17 00:00:01"
description: "수치해석학에서 고정점 반복법(Fixed Point Iteration)에 대해서 살펴본다"
categories: 
  - Math > Numerical Analysis
---

# Definition 1
For a function $f: X \to X$, a point $\alpha \in X$ satisfying $\alpha = f(\alpha)$ is called a ***fixed point*** of $f$.

# Lemma
Let $g : [a, b] \to [a, b]$ be a continuous function. Then $g$ has a fixed point in $[a, b]$.

## Proof
Put $f(x) = x - g(x), \forall x \in [a, b]$. Then we have $f(a) = a - g(a) \le 0$ and $f(b) = b - g(b) \ge 0$. By the Intermediate Value Theorem, there exists $c \in [a, b]$ such that $f(c) = 0$. Thus $c - g(c) = 0$, which implies $c = g(c)$. Hence $c$ is a fixed point of $g$. $\blacksquare$

# Theorem
Let $g: [a, b] \to [a, b]$ be a function satisfying that $g$ and $g'$ is continuous on $[a, b]$. Assume that 

$$\lambda = \max_{a \le x \le b} \vert g'(x) \vert < 1.$$

Then the followings hold:

**(i)** $g$ has a unique fixed point $\alpha \in [a, b]$.

**(ii)** For any initial estimate $x_0 \in [a, b]$, the iteration $x_{n+1} = g(x_n)$ converges to the unique fixed point $\alpha$.

**(iii)**

$$\vert \alpha - x_n \vert \le \frac{\lambda^n}{1 - \lambda} \vert x_0 - x_1 \vert, \forall n = 0, 1, \dots$$

**(iv)**

$$\lim_{n \to \infty} \frac{\alpha - x_{n+1}}{\alpha - x_n} = g'(\alpha)$$

Thus, $\vert \alpha - x_{n+1} \vert \le C \vert \alpha - x_n \vert$ for sufficiently large $n$ and for some constant $C \ge 0$ independent of $n$.

## Proof
**(i)** Let $\alpha, \beta$ be two fixed points of $g$ with $\alpha < \beta$, that is, $\alpha = g(\alpha)$ and $\beta = g(\beta)$. By the mean value theorem, there exists $c \in (\alpha, \beta)$ such that

$$\begin{align*}
\alpha - \beta = g(\alpha) - g(\beta) = g'(c)(\alpha - \beta) \\
\implies (\alpha - \beta)(1 - g'(c)) = 0
\end{align*}$$

Since $\displaystyle \lambda = \max_{a \le x \le b} \vert g'(x) \vert < 1$, we have $1 - g'(c) \neq 0$, which implies $\alpha - \beta = 0$. Hence $\alpha = \beta$.

**(ii)** By the mean value theorem, there exists $c_n$ between $\alpha$ and $x_n$ such that

$$\begin{align*}
&\alpha - x_{n+1} = g(\alpha) - g(x_n) = g'(c_n)(\alpha - x_n) \\
\implies &\vert \alpha - x_{n+1} \vert \le \lambda \vert \alpha - x_n \vert \\
\implies &\vert \alpha - x_n \vert \le \lambda^{n+1} \vert \alpha - x_0 \vert
\end{align*}$$ 

Since $\lambda < 1$, we obtain that $\displaystyle \lim_{n \to \infty} x_n = \alpha$.

**(iii)** We have shown that $\vert \alpha - x_{n+1} \vert \le \lambda \vert \alpha - x_n \vert$ for all $n \ge 0$. Then it follows that

$$\begin{align*}
\vert \alpha - x_0 \vert &= \vert \alpha - x_1 + x_1 - x_0 \vert \\
&\le \vert \alpha - x_1 \vert + \vert x_1 - x_0 \vert \\
&\le \lambda \vert \alpha - x_0 \vert + \vert x_1 - x_0 \vert \\
\implies \vert \alpha - x_0 \vert &\le \frac{1}{1-\lambda} \vert x_1 - x_0 \vert
\end{align*}$$

Similarly, we have

$$\vert \alpha - x_n \vert \le \lambda^n \vert \alpha - x_0 \vert,$$

so that

$$\vert \alpha - x_n \vert \le \frac{\lambda^n}{1 - \lambda} \vert x_0 - x_1 \vert, \forall n = 0, 1, \dots.$$

**(iv)** By the mean value theorem, there exists $c_n$ between $\alpha$ and $x_n$ such that

$$\begin{align*}
\alpha - x_{n+1} &= g(\alpha) - g(x_n) \\
&= g'(c_n)(\alpha - x_n) \\
\implies \frac{\alpha - x_{n+1}}{\alpha - x_n} &= g'(c_n)
\end{align*}$$ 

From **(ii)**, we have $\displaystyle \lim_{n \to \infty} x_n = \alpha$, so that $\displaystyle \lim_{n \to \infty} c_n = \alpha$. Since $g'$ is continuous on $[a, b]$, we have

$$\lim_{n \to \infty} \frac{\alpha - x_{n+1}}{\alpha - x_n} = g'(\alpha)$$

Hence, for sufficiently large $n$ and some constant $C \ge 0$, we have

$$\vert \alpha - x_{n+1} \vert \le C \vert \alpha - x_n \vert. \blakcsquare$$

# Definition 2
A sequence $\{ x_n \}$ is said to converge to $\alpha$ ***with order of convergence*** $p \ge 1$ if

$$\vert \alpha - x_{n+1} \vert \le c \vert \alpha - x_n \vert^p, \quad n \ge n_0$$

for some constant $c > 0$. The cases $p=1$ and $p=2$ are called linear convergence and quadratic convergence, respectively. 

# Reference
- K. E. Atkinson and W. Han, Elementary Numerical Analysis, 3rd ed., John Wiley & Sons, 2004.