---
title: "Analytic Continuation"
author: "Youmin Chun"
date: "2026-07-25 00:00:17"
categories: 
  - Math > Complex Analysis
---

## Definition
Let $f_1: D_1 \to \mathbb{C}$ be an analytic function in $D_1$. If there exists an analytic function $f_2: D_2 \to \mathbb{C}$ such that $f_1(z) = f_2(z), \forall z \in D_1 \cap D_2 \neq \emptyset$, then $f_2$ is called an ***analytic continuation*** of $f_1$ into $D_2$.

설명은 일반적으로 써놨지만, 많은 경우 $D_1 \subset D_2$인 경우를 생각하며, 특별히 $D_1 = \mathbb{R}$이고 $D_2 = \mathbb{C}$인 경우 실수공간에서 정의된 함수가 복소공간으로 정의역을 확장하여도 잘 정의되기를 바라는 경우를 생각할 수 있다.

## Remark
**(i)** If an analytic continuation exists, then it is unique. $(\because)$ By [coincidence principle.](../Coincidence_Principle/index.qmd#sec-coincidence-principle)

**(ii)** If $f_2$ is the analytic continuation of $f_1$ from a domain $D_1$ into a domain $D_2$, then the function $F$ defined by

$$F(z) = \begin{cases}
f_1(z) & z \in D_1 \\
f_2(z) & z \in D_2
\end{cases}$$

is analytic in $D_1 \cup D_2$. The function $F$ is the analytic continuation into $D_1 \cup D_2$ of either $f_1$ or $f_2$.

# Reference
- Brown, James Ward, & Churchill, Ruel V. (2017). Complex Variables and Applications (9th ed.). McGraw-Hill.