---
title: "Cocitation and Bibliographic Coupling"
author: "Youmin Chun"
date: "2026-07-24"
categories: 
  - Math > Graph Theory > Network Analysis
---

## Definition
Let $A$ be the $n \times n$ adjacency matrix of a directed graph $G$.

**(i)** The ***cocitation matrix*** $C$ of $A$ is the $n \times n$ matrix $C = AA^T$, and the ****cocitation network**** is a network in wich there is an edge between $i$ and $j$ if $C_{ij} > 0$ for $i \neq j$ in the graph $G$.

**(ii)** The ***bibliographic coupling matrix*** $B$ of $A$ is the $n \times n$ matrix $B = A^TA$, and the ****bibliographic coupling network**** is a network in wich there is an edge between $i$ and $j$ if $B_{ij} > 0$ for $i \neq j$ in the graph $G$.

유향 그래프를 무향 그래프로 바꾸는 작업은 네트워크를 분석할 때 종종 필요한 일이다. 가장 단순한 방법은 원래는 방향이 있는데 그냥 없다고 생각하는 것이다. 그러나 이럴 경우 기존 그래프에 있던 정보들이 손쉽게 사라진다는 단점이 있기에 조금 복잡하지만 유용한 방법을 도입하게 되는데, 이때 등장하는 접근법이 바로 cocitation과 bibliographic coupling이다. 

## Cocitation
논문에는 항상 인용하거나 참고한 다른 논문이 있기 마련이다. 이때 서로 다른 두 논문이 또 다른 논문에 의해 동시에 인용되었다고 해보자. 즉 논문 1과 논문 2가 있는데, 논문 3이 논문 1과 2를 동시에 인용한 상황이다. 이때 논문 3 뿐만 아니라 논문 4, 5, 6와 같이 논문 1과 2를 동시에 인용한 논문들이 많아질수록 논문 1과 2는 서로 연관되어 있는 주제를 다뤘다고 생각할 수 있다. 이를 유향 그래프의 언어로 표현하면 $i \to 1, i \to 2$ $(i = 3, 4, 5, 6)$와 같이 쓸 수 있고 인접 행렬은 $A_{1i} = 1 = A_{2i} (i = 3, 4, 5, 6)$이다. 그러면 모든 $i$에 대해서 이 값을 더하면 구체적으로 논문 1과 2가 얼마나 동시에 인용되었는지, 즉 cocited되었는지 알 수 있고 이 값을 성분으로 가지는 행렬이 cocitation matrix이다.

$$C_{ij} = \sum_{k=1}^n A_{ik}A_{jk} = \sum_{k=1}^n A_{ik}A^T_{kj} = (AA^T)_{ij}$$

위 서술에서 알 수 있듯이 $C_{ij}$는 $0$ 아니면 $1$의 값만을 가지며 $C$는 대칭행렬이다. 기존에 유향 그래프 $G$의 인접행렬 $A$는 대칭행렬이 아니었지만, $A$의 cocitation matrix는 대칭행렬이고, 따라서 무향 그래프이다. 

한편 Cocitation matrix로부터 cocitation network가 유도되는데, 주의할 점은 이 cocitation network의 인접행렬은 cocitation matrix가 아니다. 단적으로 알 수 있는 방법은 대각성분인데, cocitation matrix의 대각성분은 일반적으로 $0$이 아니다. 대각성분 $C_{ii}$에 대해서는

$$C_{ii} = \sum_{k=1}^n A^2_{ik} = \sum_{k=1}^n A_{ik}$$

이 성립하는데, 각 $A_{ik}$가 $0$ 아니면 $1$의 값만을 가지기 때문이다. 그러면 $C_{ii}$는 쉽게 말해 논문 $i$를 인용한 다른 논문의 개수를 의미하고, 이는 일반적으로 $0$일 필요가 없다.

## Bibliographic Coupling
Bibliographic coupling은 cocitation과 정반대이다. 두 논문을 동시에 인용한 논문들을 측정한 개념이 cocitation이었다면, bibliographic coupling은 두 논문이 동시에 인용한 논문들을 측정한 개념이다. 즉 논문 1과 2가 논문 3, 4, 5, 6을 동시에 인용한 상황이고, 많으면 많을수록 논문 1과 2는 서로 비슷한 주제를 다루고 있다고 생각할 수 있다. 유향 그래프의 언어로 표현하면 $1 \to i, 2 \to i (i = 3, 4, 5, 6)$이고 $A_{1i} = 1 = A_{2i} (i = 3, 4, 5, 6)$이다. 따라서 모든 $i$에 대해서 이 값을 더하면 구체적으로 논문 1과 2가 서로 다른 논문들을 얼마나 동시에 인용했는지, 즉 bibliography 목록이 얼마나 coupled되었는지 측정할 수 있고 이 값을 성분으로 가지는 행렬이 bibliographic coupling matrix이다.

$$B_{ij} = \sum_{k=1}^n A_{ki}A_{kj} = \sum_{k=1}^n A^T_{ik}A_{kj} = (A^TA)_{ij}$$

마찬가지로 $B_{ij}$는 $0$ 아니면 $1$의 값만을 가지며 $B$는 대칭행렬이다. 

## Remark
이렇게 두 개념 모두 서로 다른 두 논문, 다르게 말하면 두 버텍스의 연관성을 기존의 유향 그래프로부터 새롭게 측정하는 방법인데, 유향 그래프의 에지 속 방향성을 고려해서 측정했다는 점에서 기존 그래프의 방향성이 완전히 소실되지 않는다. 

그런데 두 개념은 연관성을 측정하는 방법이 다른만큼 그 특장점도 다르다. Cocitation은 피인용된 논문 수가 많을수록 높은 값이 매겨지므로 상대적으로 유명한 논문들에 높은 값이 매겨지고, 덜 유명하거나 출판된지 얼마 되지 않은 논문들에는 낮은 값이 매겨진다. 다르게 말하면 시간이 지날수록 값이 변할 수도 있다.

반대로 bibliographic coupling은 자신이 인용한 논문 수가 많으면 많을수록 높은 값이 매겨지므로 논문 간 유사도를 보다 균일하게 측정할 수 있다는 장점이 있다. 또한 출판된 순간 참고문헌 목록은 고정되므로 측정값 역시 변하지 않는다.

# Reference
- Newman, M.E.J. (2010). Networks: An Introduction. Oxford University Press.