---
title: "Compact Space"
author: "Youmin Chun"
date: "2026-09-03 00:00:01"
description: "컴팩트 공간에 대해서 설명한다."
categories: 
  - Math > Topology
---

# Definition
Let $X$ be a topological space.

**(i)** A collection $\mathscr{U}$ of open subsets of $X$ is called an ***open cover*** of $X$ if $\displaystyle X = \bigcup_{U \in \mathscr{U}} U$.

**(ii)** The space $X$ is said to be ***compact*** if every open cover of $X$ has a finite subcover.

## Example
**(i)** $\mathbb{R}$ with the usual topology is **NOT** compact.

$\big[ (\because)$ The collection $\{ (n, n+2) \mid n \in \mathbb{Z} \}$ is an open cover of $\mathbb{R}$, but it has no finite subcover. $\big]$

**(ii)** $\mathbb{R}$ with the trivial topology is compact.

**(iii)** $[0, 1)$ is NOT compact.

$\big[ (\because)$ The collection $\left \{ \left[ 0, 1 - \frac{1}{n} \right) \,\, \bigg | \,\, n \in \mathbb{N} \right \}$ is an open cover of $[0, 1)$, but it has no finite subcover. $\big]$

**(iv)** $K = \{ 0 \} \cup \left \{ \frac{1}{n} \,\, \bigg | \,\, n \in \mathbb{N} \right \}$ is compact.

$\big[ (\because)$ Let $\mathscr{U}$ be an open cover of $K$. Since $0 \in K$ and $\mathscr{U}$ is an open cover of $K$, $0 \in U$ for some $U \in \mathscr{U}$. Then $U$ contains all but finitely many of the points $\frac{1}{n}$. By choosing, for each point of $X$ not in $U$, an open set in $\mathscr{U}$ containing it, we obtain a finite subcover of $K$. $\big]$

**(v)** A closed interval $[a, b]$ is compact.

$\big[ (\because)$ Suppose that $[a, b]$ is not compact. Then there is an open cover $\mathscr{U}$ of $[a, b]$ such that $\mathscr{U}$ does not have a finite subcover.

Note that $\displaystyle [a, b] = \left[ a, \frac{a+b}{2} \right] \cup \left[ \frac{a+b}{2}, b \right]$. Then $\mathscr{U}$ has no finite subcover that covers one of $\left[ a, \frac{a+b}{2} \right]$ and $\left[ \frac{a+b}{2}, b \right]$, say $I_1 = [a_1, b_1]$. 

Again, note that $\left[ a_1, b_1 \right] = \left[ a_1, \frac{a_1 + b_1}{2} \right] \cup \left[ \frac{a_1 + b_1}{2}, b_1 \right]$. Then $\mathscr{U}$ has no finite subcover that covers one of $\left[ a_1, \frac{a_1 + b_1}{2} \right]$ and $\left[ \frac{a_1 + b_1}{2}, b_1 \right]$, say $I_2 = [a_2, b_2]$.

Continuing the process, we can construct a sequence $\{ I_n \}_{n=1}^\infty$ of nested closed intervals $I_n = [a_n, b_n]$ of $[a, b]$ such that each $I_n$ cannot be covered by a finite subcover of $\mathscr{U}$, and $\vert x-y \vert \le \frac{b-a}{2^n} = \vert I_n \vert,\forall x, y \in I_n$.

By the nested interval theorem, there exists $x^\ast \in \displaystyle \bigcap_{n=1}^\infty I_n$. Since $\mathscr{U}$ is an open cover of $[a, b]$ and $x^\ast \in [a, b]$, $x^\ast \in U$ for some $U \in \mathscr{U}$. Then there is $\delta > 0$ such that $(x^\ast - \delta, x^\ast + \delta) \subset U$. Choosing $n$ large enough such that $\vert I_n \vert = \frac{b-a}{2^n} < \delta$, we obtain that $I_n \subset (x^\ast - \delta, x^\ast + \delta) \subset U$. $\big[ (\because)$ If $y \in I_n$, then $\vert x^\ast - y \vert < \vert I_n \vert < \delta$, so $y \in (x^\ast - \delta, x^\ast + \delta)$.$\big]$ This contradicts that $\mathscr{U}$ does not have a finite subcover that covers $I_n$. Thus, $[a, b]$ is compact. $\blacksquare \big]$

**(vi)** Since $S^n$ is a closed subspace of a compact space $[-1, 1]^{n+1}$, $S^n$ is compact. Similarly, $B^n$ is compact. 

# Theorem 1
**(i)** Let $Y$ be a subspace of $X$. Then $Y$ is compact $\iff$ every collection $\mathscr{U} = \{ U \subset X \mid U \text{ is open in } X \}$ such that $Y \subset \bigcup_{U \in \mathscr{U}} U$ has a finite subcollection that covers $Y$.

**(ii)** Every closed subspace of a compact space is compact.

**(iii)** Every compact subspace of a Hausdorff space is closed.

**(iv)** Let $X$ be a compact space, and let $f: X \to Y$ be a continuous function. Then $f(X)$ is compact.

**(v)** Let $f: X \to Y$ be a bijective continuous function. If $X$ is compact and $Y$ is Hausdorff, then $f$ is a homeomorphism.

**(vi)** $\displaystyle \prod_{i=1}^n X_i$ is compact $\iff X_i$ is compact for all $i = 1, \dots, n$.

본디 부분공간 $Y$의 오픈 커버는 $Y$의 오픈셋들로 구성되어야 한다. 이는 부분공간의 정의상 오픈셋의 모양이 조금 지저분해질 수 밖에 없는데, 위 정리는 그러한 불편함을 없애고 $X$의 오픈셋들만 가지고도 부분공간의 컴팩터성을 논할 수 있게 해준다는 점을 시사한다.

## Proof
**(i)**

$(\Longrightarrow)$ Suppose that $Y$ is compact. Let $\mathscr{U} = \{ U \subset X \mid U \text{ is open in } X \}$ be a collection such that $Y \subset \bigcup_{U \in \mathscr{U}} U$. Since $U \cap Y$ is open in $Y$ for each $U \in \mathscr{U}$, the collection $\{ U \cap Y \mid U \in \mathscr{U} \}$ is an open cover of $Y$. Since $Y$ is compact, there exists a finite subcover $\{ U_1 \cap Y, U_2 \cap Y, \dots, U_n \cap Y \}$ of $Y$. Then $\{ U_1, U_2, \dots, U_n \}$ is a finite subcollection of $\mathscr{U}$ that covers $Y$.

$(\Longleftarrow)$ Suppose that the given condition holds. Let $\mathscr{U}$ be an open cover of $Y$. Since $U_\alpha = V_\alpha \cap Y$ for some open subset $V_\alpha$ of $X$, the collection $\{ V_\alpha \}$ satisfies that $\displaystyle Y \subset \bigcup_{\alpha} V_\alpha$. By the assumption, there exists a finite subcollection $\{ V_1, V_2, \dots, V_n \}$ that covers $Y$. Then $\{ V_1 \cap Y, V_2 \cap Y, \dots, V_n \cap Y \}$ is a finite subcover of $\mathscr{U}$. Thus, $Y$ is compact.

**(ii)** Let $Y$ be a closed subspace of a compact space $X$. Let $\mathscr{U}$ be a collection of open subsets of $X$ such that $Y \subset \bigcup_{U \in \mathscr{U}} U$. Then $\mathscr{U} \cup \{ X - Y \}$ is an open cover of $X$. Since $X$ is compact, it has a finite subcover $\{ U_1, \dots, U_n, X - Y \}$. Since $\{ U_1, \dots, U_n \}$ covers $Y$, by **(i)**, $Y$ is compact.

**(iii)** Let $Y$ be a compact subspace of a Hausdorff space $X$. We will show that $X - Y$ is open, so $Y$ is closed.

Let $x \in X - Y$. Since $x \notin Y$ and $X$ is Hausdorff, for each $y \in Y$, there exist two disjoint open subsets $U_y, V_y$ of $X$ such that $x \in U_y$ and $y \in V_y$. Then the collection of such $V_y$ covers $Y$. Since $Y$ is compact, the finite subcollection $\{ V_{y_1}, \dots, V_{y_n} \}$ covers $Y$ by **(i)**. That is, 

$$V := \bigcup_{i=1}^n V_{y_i} \supset Y.$$

Note that 

**(a)** $\displaystyle U := \bigcap_{i=1}^n U_{y_i}$ is open, 

**(b)** $U \cap V_i = \emptyset, \forall i \in \{ 1, \dots, n \}$, so 

$$\displaystyle U \cap \bigcup_{i=1}^n V_{y_i} = U \cap V = \emptyset.$$

Since $V$ contains $Y$, we have $U \cap Y = \emptyset$, so $U \subset X - Y$. Since each $U_{y}$ contains $x$, we conclude that 

$$x \in U \subset X - Y,$$

which means that $X - Y$ is open. Therefore, $Y$ is closed.

**(iv)** Let $\mathscr{V}$ be a collection consisting of open subsets of $Y$ that covers $f(X)$. Then the collection $\{ f^{-1}(V) \mid V \in \mathscr{V} \}$ covers $X$. $\big[ (\because)$ Let $x \in X$. Since $\mathscr{V}$ covers $f(X)$, $f(x) \in V$ for some $V \in \mathscr{V}$. Then $x \in f^{-1}(V)$. $\big]$

Since $f$ is continuous, the collection $\{ f^{-1}(V) \mid V \in \mathscr{V} \}$ is an open covering of $X$. Since $X$ is compact, the finite subcover $\{ f^{-1}(V_1), \dots, f^{-1}(V_n) \}$ exists. Thus, we have 

$$\begin{align*}
X &= \bigcup_{i=1}^n f^{-1}(V_i) \\
&= f^{-1} \left( \bigcup_{i=1}^n V_i \right),
\end{align*}$$

which means that

$$f(X) \subset \bigcup_{i=1}^n V_i.$$

By **(i)**, $f(X)$ is compact.

**(v)** We need to show that $f^{-1}: Y \to X$ is continuous. Let $C$ be a closed subset of $X$. Since $X$ is compact, $C$ is compact by **(ii)**. Since $f$ is continuous, $(f^{-1})^{-1}(C) = f(C)$ is compact by **(iv)**. Since $Y$ is Hausdorff, $f(C)$ is closed by **(iii)**. Thus, $f^{-1}$ is continuous.

**(vi)** 

$(\implies)$ Suppose that $\displaystyle \prod_{i=1}^n X_i$ is compact. Since $\pi_j : \displaystyle \prod_{i=1}^n X_i \to X_j$ is continuous for all $j = 1, \dots, n$, and $X_j$ is the image of $\pi_j$, $X_j$ is compact by **(iv)**.

$(\Longleftarrow)$ We use induction on $n$.

**Base Case:** Let $\mathcal{O}$ be an open cover of $X_1 \times X_2$. For each $(x, y) \in X_1 \times X_2$, there exists $O_{(x, y)} \in \mathcal{O}$ such that $(x, y) \in O_{(x, y)}$. Then $(x, y) \in U_{(x, y)} \times V_{(x, y)} \subset O_{(x, y)}$ for some open subsets $U_{(x, y)}$ of $X_1$ and $V_{(x, y)}$ of $X_2$. 

Note that $\{ U_{(x, y)} \}_{x \in X_1}$ is an open cover of $X_1$. Since $X_1$ is compact, the finite subcover $\{ U_{(x_1, y)}, \dots, U_{(x_n, y)} \}$ exists. Set

$$V_y := \bigcap_{i=1}^n V_{(x_i, y)}.$$

Since $V_y$ is open in $X_2$, $\{ V_y \}_{y \in X_2}$ is an open cover of $X_2$. Since $X_2$ is compact, there exists a finite subcover $\{ V_{y_1}, \dots, V_{y_m} \}$ of $X_2$. Then $\{ O_{(x_i, y_j)} \}_{i=1, \dots, n, j = 1, \dots, m}$ is a finite subcollection of $\mathcal{O}$ that covers $X_1 \times X_2$, which means that $X_1 \times X_2$ is compact.

**Inductive Step:** Suppose that $X_1, \dots, X_n$ are compact for some $n \in \mathbb{N}$, and $\prod_{i=1}^n X_i$ is compact. Let $X_{n+1}$ be a compact space. By the base case, we argue 

$$\prod_{i=1}^{n+1} X_i = \left( \prod_{i=1}^n X_i \right) \times X_{n+1}$$

is compact. Thus, we complete the proof. $\blacksquare$

# Definition 2
A point $x$ of a space $X$ is called an isolated point of $X$ if $\{ x \}$ is open in $X$.

## Example
**(i)** $(\mathbb{R}, \mathscr{T}_{\text{usual}})$ has no isolated points.

**(ii)** Every point in $(X, \mathscr{T}_\text{discrete})$ is an isolated point.

**(iii)** A subspace $\{ 0 \} \cup [1, 2]$ of $(\mathbb{R}, \mathscr{T}_{\text{usual}})$ has an isolated point $0$.

# Theorem 2
Let $X$ be a nonempty compact Hausdorff space. If $X$ has no isolated points, then $X$ is uncountable.

## Proof
Let $U$ be a nonempty open subset of $X$, and let $x \in X$. Then there exists a nonempty open subset $V$ of $U$ such that $x \notin \overline{V}$.

$\big[ (\because)$ If $U$ is a singleton, then $X$ has an isolated point, which is a contradiction. It implies that we can choose a point $y \in U$ with $x \neq y$. Since $X$ is Hausdorff, there are open sets $W_1, W_2$ such that $x \in W_1, y \in W_2$ and $W_1 \cap W_2 = \emptyset$. Let $V = U \cap W_2$. Then $V$ is nonempty open subset of $U$.

If $z \in W_1$, then $z \in W \subset W_1$ for some basis element $W$. Since $W_1 \subset X \setminus W_2$, we have $z \in W \subset X \setminus W_2$, which means that $z \in \mathrm{int}(X \setminus W_2)$. This shows that $W_1 \subset \mathrm{int}(X \setminus W_2)$. Note that $V \subset W_2$, so $\overline{V} \subset \overline{W_2}$. Since $\mathrm{int}(X \setminus W_2) \cap \overline{W_2} = \emptyset$, we have $x \notin \overline{V}$.$\big]$

Let $f:\mathbb{N} \to X$ be a map. We will show that $f$ cannot be surjective, which implies that $X$ is uncountable.

$\big[ (\because)$  Let $x_1 = f(1) \in X$. By above assertation, there exists a nonempty open subset $V_1 \subset X$ such that $x_1 \notin \overline{V_1}$. Let $x_2 = f(2) \in X$. Again, there exists a nonempty open subset $V_2 \subset V_1$ such that $x_2 \notin \overline{V_2}$. Repeating this process, we can construct a sequence of nonempty open subsets $V_n$ such that $V_n \subset V_{n-1}$ and $x_n \notin \overline{V_n}$ for all $n \in \mathbb{N}$.

[Since $X$ is compact, $\displaystyle \exists x \in \bigcap_{n=1}^\infty \overline{V_n}$.](../Finite_Intersection_Property/index.qmd#sec-theorem) Since $x \in \overline{V_n}, \forall n \in \mathbb{N}$, $x \neq x_n = f(n), \forall n \in \mathbb{N}$. Hence, $f$ is not surjective. $\blacksquare \big]$

## Corollary
Every nonempty closed interval in $\mathbb{R}$ is uncountable. Thus, $\mathbb{R}$ is uncountable.

# Reference
- James R. Munkres. (2000). Topology (2nd ed.). Pearson.