---
title: "Cauchy-Riemann Equations"
author: "Youmin Chun"
date: "2026-07-24 00:00:13"
categories: 
  - Math > Complex Analysis
---

## Theorem 1
Suppose that $f(z) = u(x, y) + i v(x, y)$ is differentiable at $z_0 = x_0 + i y_0$. Then $u_x, u_y, v_x, v_y$ exist and satisfy the Cauchy-Riemann equations at $(x_0, y_0)$:

$$
\begin{cases}
u_x = v_y \\
u_y = -v_x
\end{cases}
$$

### Proof
Denote $\Delta z = \Delta x + i \Delta y$. Note that 

$$\begin{align*}
\Delta w &= f(z + \Delta z) - f(z) \\
&= u(x_0 + \Delta x, y_0 + \Delta y) - u(x_0, y_0) + i [v(x_0 + \Delta x, y_0 + \Delta y) - v(x_0, y_0)] 
\end{align*}$$

Then we have 

$$\begin{align*}
\frac{\Delta w}{\Delta z} &= \frac{u(x_0 + \Delta x, y_0 + \Delta y) - u(x_0, y_0)}{\Delta x + i \Delta y} + i \frac{v(x_0 + \Delta x, y_0 + \Delta y) - v(x_0, y_0)}{\Delta x + i \Delta y}
\end{align*}$$

Along the horizontal line $\Delta y = 0$, we have 

$$\begin{align*}
f'(z_0) &= \lim_{\Delta x \to 0} \frac{\Delta w}{\Delta z} \\
&= \lim_{\Delta x \to 0} \frac{u(x_0 + \Delta x, y_0) - u(x_0, y_0)}{\Delta x} + i \lim_{\Delta x \to 0} \frac{v(x_0 + \Delta x, y_0) - v(x_0, y_0)}{\Delta x} \\
&= u_x(x_0, y_0) + i v_x(x_0, y_0)
\end{align*}$$

Along the vertical line $\Delta x = 0$, we have 

$$\begin{align*}
f'(z_0) &= \lim_{\Delta y \to 0} \frac{\Delta w}{\Delta z} \\
&= \lim_{\Delta y \to 0} \frac{u(x_0, y_0 + \Delta y) - u(x_0, y_0)}{i \Delta y} + i \lim_{\Delta y \to 0} \frac{v(x_0, y_0 + \Delta y) - v(x_0, y_0)}{i \Delta y} \\
&= -i u_y(x_0, y_0) + v_y(x_0, y_0)
\end{align*}$$

Thus we have 

$$\begin{cases}
u_x = v_y \\
u_y = -v_x. \blacksquare
\end{cases}$$

## Theorem 2
Let $f(z) = u(x, y) +iv(x, y)$ be defined throughout some $\varepsilon$ neighborhood of $z_0 = x_0 + i y_0$. Suppose that $u_x, u_y, v_x, v_y$ exist in this neighborhood, are continuous at $(x_0, y_0)$, and satisfy the Cauchy-Riemann equations at $(x_0, y_0)$. Then $f$ is differentiable at $z_0$ and $f'(z_0)$ is given by

$$ \begin{align*}
f'(z_0) &= u_x(x_0, y_0) + i v_x(x_0, y_0) \\
&= v_y(x_0, y_0) - i u_y(x_0, y_0)
\end{align*}
$$

미분가능하면 코시-리만 방정식이 성립하지만, 그 역이 성립하기 위해서는 추가로 함수 $f$가 $C^1$ 함수여야 한다.

### Proof
Let $\Delta z = \Delta x + i \Delta y$ where $0 < \vert \Delta z \vert < \varepsilon$. Since the first order partial derivatives exist and are continuous at $(x_0, y_0)$, we have 

$$\Delta u = u(x_0 + \Delta x, y_0 + \Delta y) - u(x_0, y_0) = u_x \Delta x + u_y \Delta y + \varepsilon_1 \Delta x + \varepsilon_2 \Delta y$$

for some $\varepsilon_1, \varepsilon_2 > 0$ such that $\varepsilon_1, \varepsilon_2 \to 0$ as $(\Delta x, \Delta y) \to 0$. Then we have 

$$\begin{align*}
\Delta w &= \Delta u + i \Delta v \\
&= (u_x \Delta x + u_y \Delta y + \varepsilon_1 \Delta x + \varepsilon_2 \Delta y) + i (v_x \Delta x + v_y \Delta y + \varepsilon_3 \Delta x + \varepsilon_4 \Delta y) \\
&= (u_x + iv_x) \Delta x + (u_y + iv_y) \Delta y + (\varepsilon_1 + i \varepsilon_3) \Delta x + (\varepsilon_2 + i \varepsilon_4) \Delta y \\
&= u_x(\Delta x + i \Delta y) + i v_x(\Delta x + i \Delta y) + (\varepsilon_1 + i \varepsilon_3) \Delta x + (\varepsilon_2 + i \varepsilon_4) \Delta y \\
&= (u_x + iv_x) \Delta z + (\varepsilon_1 + i \varepsilon_3) \Delta x + (\varepsilon_2 + i \varepsilon_4) \Delta y
\end{align*}$$

where $\varepsilon_1, \varepsilon_2, \varepsilon_3, \varepsilon_4 \to 0$ as $(\Delta x, \Delta y) \to (0, 0)$.

Then we have 
$$\begin{align*}
\frac{\Delta w}{\Delta z} &= u_x + iv_x + (\varepsilon_1 + i \varepsilon_3) \frac{\Delta x}{\Delta z} + (\varepsilon_2 + i \varepsilon_4) \frac{\Delta y}{\Delta z}
\end{align*}$$

Since $\vert \frac{\Delta x}{\Delta z} \vert \le 1$ and $\vert \frac{\Delta y}{\Delta z} \vert \le 1$, we have 

$$\begin{align*}
\left\vert \frac{\Delta w}{\Delta z} - (u_x + iv_x) \right\vert &= \left\vert (\varepsilon_1 + i \varepsilon_3) \frac{\Delta x}{\Delta z} + (\varepsilon_2 + i \varepsilon_4) \frac{\Delta y}{\Delta z} \right\vert \\
&\le \vert \varepsilon_1 \vert + \vert \varepsilon_3 \vert + \vert \varepsilon_2 \vert + \vert \varepsilon_4 \vert \\
&\to 0 \quad \text{as } (\Delta x, \Delta y) \to (0, 0).
\end{align*}$$

Thus $f$ is differentiable at $z_0$ and $f'(z_0) = u_x + iv_x$. $\blacksquare$

# Reference
- Brown, James Ward, & Churchill, Ruel V. (2017). Complex Variables and Applications (9th ed.). McGraw-Hill.