---
title: "Cross Product"
author: "Youmin Chun"
date: "2026-09-07 00:00:01"
description: "벡터의 외적(Cross Product)에 대해서 설명한다."
categories: 
  - Math > Differential Geometry
---

# Definition
For vectors $\mathbf{u} = (u_1, u_2, u_3), \mathbf{v} = (v_1, v_2, v_3) \in \mathbb{R}^3$, the ***cross product*** of $\mathbf{u}$ and $\mathbf{v}$ is defined as

$$\begin{align*}
\mathbf{u} \times \mathbf{v} &:= \det \begin{bmatrix}
\mathbf{e}_1 & \mathbf{e}_2 & \mathbf{e}_3 \\
u_1 & u_2 & u_3 \\
u_1 & v_2 & v_3
\end{bmatrix} \\
&= ((u_2v_3 - u_3v_2), -(u_1v_3 - u_3v_1), (u_1v_2 - u_2v_1))
\end{align*}$$

where $\{ \mathbf{e}_1, \mathbf{e}_2, \mathbf{e}_3 \}$ is the standard ordered [basis](../Basis/index.qmd#sec-definition-1)
 for $\mathbb{R}^3$.

## Proposition
Let $\mathbf{u}, \mathbf{v}, \mathbf{w} \in \mathbb{R}^3$, and $r \in \mathbb{R}$. Then

**(i)** $\mathbf{u} \times \mathbf{v} = - \mathbf{v} \times \mathbf{u}$

**(ii)** $(r\mathbf{u}) \times \mathbf{v} = r(\mathbf{u} \times \mathbf{v}) = \mathbf{u} \times (r \mathbf{v})$

**(iii)** $\mathbf{u} \times \mathbf{v} = \mathbf{0} \iff \{ \mathbf{u}, \mathbf{v} \}$ is [linearly dependent.](../Linearly_Independence/index.qmd#sec-definition)

**(iv)** $(\mathbf{u} + \mathbf{v}) \times \mathbf{w} = (\mathbf{u} \times \mathbf{w}) + (\mathbf{v} \times \mathbf{w})$

**(v)** $\mathbf{u} \times \mathbf{v} \perp \mathbf{u}, \mathbf{v}$, that is, $\langle \mathbf{u} \times \mathbf{v}, \mathbf{u} \rangle = 0 = \langle \mathbf{u} \times \mathbf{v}, \mathbf{v} \rangle$

**(vi)** $\vert \mathbf{u} \times \mathbf{v} \vert = \vert \mathbf{u} \vert \vert \mathbf{v} \vert \sin \theta$, where $\theta$ is the angle between $\mathbf{u}$ and $\mathbf{v}$. Furthermore, $\vert \mathbf{u} \times \mathbf{v} \vert$ is the ***area of the parallelogram*** generated by $\mathbf{u}$ and $\mathbf{v}$.

**(vii)** If $\{ \mathbf{u}, \mathbf{v} \}$ is linearly independent, then $\{ \mathbf{u}, \mathbf{v}, \mathbf{u} \times \mathbf{v} \}$ is a [basis](../Basis/index.qmd#sec-definition-1)
 for $\mathbb{R}^3$ and gives a [right handed orientation](../Basis_Orientation/index.qmd#sec-definition) to $\mathbb{R}^3$.

### Proof
**(v)** WLOG, it suffices to show that $\langle \mathbf{u} \times \mathbf{v}, \mathbf{u} \rangle = 0$. 

By the [scalar triple product](../Scalar_Triple_Product/index.qmd#sec-definition), we have

$$\begin{align*}
\langle \mathbf{u} \times \mathbf{v}, \mathbf{u} \rangle &= \det \begin{bmatrix} u_1 & u_2 & u_3 \\ v_1 & v_2 & v_3 \\ u_1 & u_2 & u_3 \end{bmatrix} \\
&= 0
\end{align*}$$

since the determinant of a matrix with two identical rows is $0$.

**(vi)** 

$$\begin{align*}
\vert \mathbf{u} \vert^2 \vert \mathbf{v} \vert^2 \sin^2 \theta &= \vert \mathbf{u} \vert^2 \vert \mathbf{v} \vert^2 (1 - \cos^2 \theta) \\
&= \vert \mathbf{u} \vert^2 \vert \mathbf{v} \vert^2 - (\vert \mathbf{u} \vert \vert \mathbf{v} \vert \cos \theta)^2 \\
&= \vert \mathbf{u} \vert^2 \vert \mathbf{v} \vert^2 - \langle \mathbf{u}, \mathbf{v} \rangle^2 \\
&= (u_1^2 + u_2^2 + u_3^2)(v_1^2 + v_2^2 + v_3^2) - (u_1v_1+ u_2v_2 + u_3v_3)^2 \\
&= (u_1v_2 - u_2v_1)^2 + (u_1v_3 - u_3v_1)^2 + (u_2v_3 - u_3v_2)^2 \\
&= \vert \mathbf{u} \times \mathbf{v} \vert^2.
\end{align*}$$

**(vii)** By **(v)**, $\mathbf{u} \times \mathbf{v}$ is perpendicular to $\mathbf{u}$ and $\mathbf{v}$, which implies that the set $\{ \mathbf{u}, \mathbf{v}, \mathbf{u} \times \mathbf{v} \}$ is linearly independent. Since $\mathbb{R}^3$ has the [dimension](../Basis/index.qmd#sec-definition-2) $3$, it follows that it is a basis for $\mathbb{R}^3$.

We check that $\{ \mathbf{u}, \mathbf{v}, \mathbf{u} \times \mathbf{v} \}$ gives the same orientation with the standard ordered basis $\{ \mathbf{e}_1, \mathbf{e}_2, \mathbf{e}_3 \}$.

Let $\mathsf{T}: \mathbb{R}^3 \to \mathbb{R}^3$ be the linear transformation defined by 

$$\begin{align*}
\mathsf{T}(\mathbf{e}_1) &= \mathbf{u}, \\
\mathsf{T}(\mathbf{e}_2) &= \mathbf{v}, \\
\mathsf{T}(\mathbf{e}_3) &= \mathbf{u} \times \mathbf{v}.
\end{align*}$$

Let $\alpha = \{ \mathbf{e}_1, \mathbf{e}_2, \mathbf{e}_3 \}$ and $\beta = \{ \mathbf{u}, \mathbf{v}, \mathbf{u} \times \mathbf{v} \}$. Then we have

$$\begin{align*}
\det(\mathsf{T}) &= \det([\mathsf{T}]_{\alpha}) \\
&= \det \begin{bmatrix} u_1 & v_1 & (\mathbf{u} \times \mathbf{v})_1 \\ u_2 & v_2 & (\mathbf{u} \times \mathbf{v})_2 \\ u_3 & v_3 & (\mathbf{u} \times \mathbf{v})_3 \end{bmatrix} \\
&= (\mathbf{u} \times \mathbf{v})_1 \det \begin{bmatrix} u_2 & v_2 \\ u_3 & v_3 \end{bmatrix} - (\mathbf{u} \times \mathbf{v})_2 \det \begin{bmatrix} u_1 & v_1 \\ u_3 & v_3 \end{bmatrix} + (\mathbf{u} \times \mathbf{v})_3 \det \begin{bmatrix} u_1 & v_1 \\ u_2 & v_2 \end{bmatrix}\\
&= \left( \det \begin{bmatrix} u_2 & v_2 \\ u_3 & v_3 \end{bmatrix} \right)^2 - \left( - \det \begin{bmatrix} u_1 & v_1 \\ u_3 & v_3 \end{bmatrix} \right)^2 + \left( \det \begin{bmatrix} u_1 & v_1 \\ u_2 & v_2 \end{bmatrix} \right)^2 \\
&=\left( \det \begin{bmatrix} u_2 & v_2 \\ u_3 & v_3 \end{bmatrix} \right)^2 + \left( \det \begin{bmatrix} u_1 & v_1 \\ u_3 & v_3 \end{bmatrix} \right)^2 + \left( \det \begin{bmatrix} u_1 & v_1 \\ u_2 & v_2 \end{bmatrix} \right)^2 > 0,
\end{align*}$$

which means that $\alpha$ and $\beta$ have the same orientation. Thus, $\beta = \{ \mathbf{u}, \mathbf{v}, \mathbf{u} \times \mathbf{v} \}$ is a right handed basis for $\mathbb{R}^3$. $\blacksquare$

# Reference
- R. S. Millman and G. D. Parker, Elements of Differential Geometry, Prentice-Hall, 1977.