---
title: "Field of Quotients of an Integral Domain"
author: "Youmin Chun"
date: "2026-09-18 00:00:01"
description: "주어진 정역(Integral Domain)을 가지고 분수체(Field of Quotients)를 구성하는 방법에 대해 설명한다."
categories: 
  - Math > Abstract Algebra > Ring Theory
---

# Motivation
[정수 집합 $\mathbb{Z}$는 환이면서 동시에 정역이지만 일반적으로 체가 되지는 않는다.](../Integral_Domain/index.qmd#sec-theorem) 반면 $\mathbb{Z}$를 포함하는 체는 많이 찾을 수 있는데, $\mathbb{Q}, \mathbb{R}, \mathbb{C}$는 모두 체이면서 $\mathbb{Z}$를 포함한다. 이때 $\mathbb{Z}$를 포함하는 체 중에서 가장 작은 체가 존재할까? 존재한다면, 무엇일까?

후술하겠지만, 답은 유리수 집합 $\mathbb{Q}$로 주어진다. 정수 집합은 그 자체만으로는 곱셈에 대한 역원을 보장할 수 없기 때문에 체가 되지 않지만, 유리수 범위 안에서 생각할 때는 체로 간주할 수 있다.

이를 일반화하면, 어떤 정역 $D$가 주어졌을 때 $D$를 포함하는 체를 찾는 문제가 되고, 이러한 체를 $D$의 ***분수체(field of quotients)***라고 한다. 아래 설명한 방법을 사용했을 때 우리는 항상 분수체를 찾을 수 있고, 특별히 분수체는 $D$를 포함하는 체 중 가장 작은 체이면서 동형사상에 대해서 유일하다는 사실까지 얻게 된다.

# Construction
Let $D$ be an integral domain. We will construct the field of quotients $F$ of $D$ by following the below steps:

**Step 1:** Define what the elements of $F$ are to be.

**Step 2:** Define the binary operations of addition and multiplication on $F$.

**Step 3:** Show that $F$ is a field under these operations.

**Step 4:** Show that $F$ can be viewed as containing $D$ as an integral subdomain.

**Step 5:** Show that such $F$ is the smallest field containing $D$ as an integral subdomain.

## Step 1
For an integral domain $D$, let 

$$S = \{ (a, b) \mid a \in D \text{ and } b \in D \setminus \{ 0 \} \}.$$

Two elements $(a, b)$ and $(c, d)$ of $S$ is said to be ***equivalent*** if $ad = bc$. In this case, we write $(a, b) \sim (c, d)$.

Then $\sim$ is an equivalence relation on $S$.

::: {.callout-note collapse="true"}
$\big[ (\because)$ Let $(a_1, b_1), (a_2, b_2), (a_3, b_3)$ be elements of $S$.

1. Since $a_1b_1 = b_1a_1$, we have $(a_1, b_1) \sim (a_1, b_1)$.

2. If $(a_1, b_1) \sim (a_2, b_2)$, then $a_1b_2 = b_1a_2$. Since $a_2b_1 = b_2a_1$, we have $(a_2, b_2) \sim (a_1, b_1)$.

3. If $(a_1, b_1) \sim (a_2, b_2)$ and $(a_2, b_2) \sim (a_3, b_3)$, then $a_1b_2 = b_1a_2$ and $a_2b_3 = b_2a_3$. Since $D$ is an integral domain, we have $a_1b_2b_3 = b_1a_2b_3 = b_1b_2a_3$. Thus $(a_1, b_1) \sim (a_3, b_3)$.

Thus, $\sim$ is an equivalence relation on $S$.$\big]$
:::

For $(a, b) \in S$, $[(a, b)]$ denotes the equivalence class of $(a, b)$ in $S$ under $\sim$. We define $F = \{ [(a, b)] \mid (a, b) \in S \} = S/ \sim$, the quotient set of $S$ under $\sim$.

## Step 2
Define $+ : F \times F \to F$ by

$$[(a, b)] + [(c, d)] = [(ad + bc, bd)]$$

for all $[(a, b)], [(c, d)] \in F$.

Define $\cdot: F \times F \to F$ by

$$[(a, b)] \cdot [(c, d)] = [(ac, bd)]$$

for all $[(a, b)], [(c, d)] \in F$.

Then $+, \cdot$ are binary operations on $F$.

::: {.callout-note collapse="true"}
$\big[ (\because)$ Let $[(a_1, b_1)], [(a_2, b_2)], [(c_1, d_1)], [(c_2, d_2)]$ be elements of $F$. Since $b_1, d_1 \neq 0$ and $D$ is an integral domain, $b_1d_1 \neq 0$. Thus, $[(a_1, b_1)] + [(c_1, d_1)] = [(a_1d_1 + b_1c_1, b_1d_1)] \in F$ and $[(a_1, b_1)] \cdot [(c_1, d_1)] = [(a_1c_1, b_1d_1)] \in F$.

Suppose that $[(a_1, b_1)] = [(a_2, b_2)]$ and $[(c_1, d_1)] = [(c_2, d_2)]$. Then we have

$$\begin{align*}
& a_1b_2 = b_1a_2 \quad \text{and} \quad c_1d_2 = d_1c_2 \\
\implies & a_1b_2d_1d_2 = b_1a_2d_1d_2 \quad \text{and} \quad c_1d_2b_1b_2 = d_1c_2b_1b_2 \\
\implies & (a_1d_1 + b_1c_1)b_2d_2 = (a_2d_2 + b_2c_2)b_1d_1 \\
\implies & [(a_1d_1 + b_1c_1, b_1d_1)] = [(a_2d_2 + b_2c_2, b_2d_2)] \\
\implies & [(a_1, b_1)] + [(c_1, d_1)] = [(a_2, b_2)] + [(c_2, d_2)],
\end{align*}$$

and

$$\begin{align*}
a_1b_2 = b_1a_2 \quad \text{and} \quad c_1d_2 = d_1c_2 \\
\implies & a_1b_2c_1d_2 = b_1a_2c_1d_2 = b_1a_2d_1c_2 \\
\implies & (a_1c_1)b_2d_2 = (a_2c_2)b_1d_1 \\
\implies & [(a_1c_1, b_1d_1)] = [(a_2c_2, b_2d_2)] \\
\implies & [(a_1, b_1)] \cdot [(c_1, d_1)] = [(a_2, b_2)] \cdot [(c_2, d_2)].
\end{align*}$$

Hence, $+, \cdot$ are binary operation on $F$.$\big]$
:::

## Step 3
Under these operations, $\langle F, +, \cdot \rangle$ is a field.

::: {.callout-note collapse="true"}
$\big[ (\because)$ Note that for each $(a, b) \in F$, $(a, b) \sim (ax, bx)$ for any $x \in D \setminus \{ 0 \}$. It implies that we can choose arbitrary elements $(a, b), (c, d)$ of $F$ such that $[(a, b)] = [(a', x)]$ and $[(c, d)] = [(c', x)]$ for some $x \in D \setminus \{ 0 \}$.

Let $(a, x), (b, x), (c, x) \in F$. 

1. $+$ is associative.

$$\begin{align*}
([(a, x)] + [(b, x)]) + [(c, x)] &= [(ax + bx, x^2)] + [(c, x)] \\
&= [(a+b, x)] + [(c, x)] \\
&= [((a+b)x + cx, x^2)] \\
&= [(ax + bx + cx, x^2)] \\
&= [(a, x)] + [(b+c, x)] \\
&= [(a, x)] + ([(b, x)] + [(c, x)]).
\end{align*}$$

2. For any $x \in D \setminus \{0\}$, $[(0, x)]$ is the additive identity in $F$.

$$\begin{align*}
[(a, x)] + [(0, x)] &= [(ax + x \cdot 0, x^2)] \\
&= [(ax, x^2)] \\
&= [(a, x)].
\end{align*}$$

3. For each $(a, x) \in F$, $[(-a, x)]$ is the additive inverse of $[(a, x)]$. 

Since $a \in D$, we have $-a \in D$. Thus, $[(-a, x)] \in F$. Moreover, we have

$$\begin{align*}
[(a, x)] + [(-a, x)] &= [(ax + x(-a), x^2)] \\
&= [(0, x^2)] \\
&= [(0, x)].
\end{align*}$$

4. $+$ is commutative.

$$\begin{align*}
[(a, x)] + [(b, x)] &= [(ax + bx, x^2)] \\
&= [(a+b, x)] \\
&= [(b+a, x)] \\
&= [(bx + ax, x^2)] \\
&= [(b, x)] + [(a, x)].
\end{align*}$$

5. $\cdot$ is associative.

$$\begin{align*}
([(a, x)] \cdot [(b, x)]) \cdot [(c, x)] &= [(ab, x^2)] \cdot [(c, x)] \\
&= [(abc, x^3)] \\
&= [(a, x)] \cdot [(bc, x^2)] \\
&= [(a, x)] \cdot ([(b, x)] \cdot [(c, x)]).
\end{align*}$$

6. $\cdot$ is commutative.

$$\begin{align*}
[(a, x)] \cdot [(b, x)] &= [(ab, x^2)] \\
&= [(ba, x^2)] \\
&= [(b, x)] \cdot [(a, x)].
\end{align*}$$

7. For any $x \in D \setminus \{0\}$, $[(x, x)]$ is the multiplicative identity in $F$.

$$\begin{align*}
[(a, x)] \cdot [(x, x)] &= [(a \cdot x, x \cdot x)] \\
&= [(ax, x^2)] \\
&= [(a, x)].
\end{align*}$$

8. For each $(a, x) \in F \setminus \{ [(0, x)] \}$, $[(x, a)]$ is the multiplicative inverse of $[(a, x)]$.

$$\begin{align*}
[(a, x)] \cdot [(x, a)] &= [(a \cdot x, x \cdot a)] \\
&= [(ax, ax)] \\
&= [(x, x)].
\end{align*}$$

9. $\cdot$ is distributive over $+$.

$$\begin{align*}
([(a, x)] + [(b, x)]) \cdot [(c, x)] &= [(a+b, x)] \cdot [(c, x)] \\
&= [((a+b)c, x^2)] \\
&= [(ac + bc, x^2)] \\
&= [(a, x)] \cdot [(c, x)] + [(b, x)] \cdot [(c, x)].
\end{align*}$$

Thus, $\langle F, +, \cdot \rangle$ is a field.$\big]$
:::

## Step 4
An integral domain $D$ can be embedded in a field $F$ such that every element of $F$ can be expressed as a quotient of two elments of $D$. This field $F$ is called a ***quotient field*** of $D$. For $[(a, b)] \in F$, we write $\frac{a}{b} \left( = \frac{a}{b}F \right)$ instead of $[(a, b)]$.

::: {.callout-note collapse="true"}
$\big[ (\because)$ First, we claim that the map $i: D \to F$ defined by $i(a) = [(a, 1)], \forall a \in D$ is a monomorphism. 

Clearly, $i$ is well-defined. Suppose that $i(a) = i(b)$. Then 

$$\begin{align*}
&[(a, 1)] = [(b, 1)] \\
\implies & (a, 1) \sim (b, 1) \\
\implies & a = b,
\end{align*}$$

so $i$ is one-to-one.

Let $a, b \in D$. Then we have

$$\begin{align*}
i(a + b) &= [(a + b, 1)] \\
&= [(a, 1)] + [(b, 1)] \\
&= i(a) + i(b)
\end{align*}$$

and

$$
\begin{align*}
i(ab) &= [(ab, 1)] \\
&= [(a, 1)] \cdot [(b, 1)] \\
&= i(a) \cdot i(b).
\end{align*}$

Thus $i$ is a ring homomorphism, so $i$ is a monomorphism. This means that $D \cong i(D)$ is a subdomain of $F$. Let $[(a, b)] \in F$. Then we obtain

$$\begin{align*}
[(a, b)] &= [(a, 1)] \cdot [(1, b)] \\
&= \frac{[(a, 1)]}{[(b, 1)]} \\
&= \frac{i(a)}{i(b)} \\
&= \frac{a}{b}. \blacksquare
\end{align*}$$
:::

## Step 5
Let $F$ be a quotient field of an integral domain $D$, and let $L$ be any field containing $D$. Then there exists a map $\psi: F \to L$ that gives an isomorphism of $F$ with a subfield of $L$ such that $\psi(a) = a, \forall a \in D$. Thus, $F$ can be embedded in $L$. In other words, a quotient field of $D$ is the smallest field containing $D$. It implies that any two quotient fields of $D$ are isomorphic.

다시 말해 주어진 정역 $D$를 포함하는 어떤 필드 $F$를 가지고 와도 동형사상 $\psi$가 존재해서 $L$ 안에 $F$를 임베딩할 수 있으므로 동형사상의 관점에서 볼 때 분수체 $F$가 $D$를 포함하는 가장 작은 필드임을 알 수 있다. 또한 자연스럽게 분수체는 동형사상의 관점에서 유일함까지 알 수 있다.

:::{.callout-note collapse="true"}
$\big[ (\because)$ Let $i : D \to D$ be the identity map. Define the map $\psi : F \to L$ by

$$\psi \left( \frac{a}{b}F \right) = \frac{i(a)}{i(b)}L = \frac{a}{b}L, \forall \frac{a}{b}F \in F.$$

1. $\psi$ is well-defined.

$\big[ (\because)$ Suppose that $\frac{a_1}{b_1}F = \frac{a_2}{b_2}F$. Then $a_1b_2 = a_2b_1$ in $D$, so we have

$$\begin{align*}
& i(a_1)i(b_2) = i(a_1b_2) = i(a_2b_1) = i(a_2)i(b_1) \\
\implies & \psi \left( \frac{a_1}{b_1}F \right) = \frac{i(a_1)}{i(b_1)}L = \frac{i(a_2)}{i(b_2)}L = \psi \left( \frac{a_2}{b_2}F \right)
\end{align*}$$

Thus $\psi$ is well-defined on $F$.$\big]$

2. $\psi$ is a ring isomorphism.

$\big[ (\because)$ Let $\frac{a_1}{b_1}F, \frac{a_2}{b_2}F \in F$. Then we have

$$\begin{align*}
\psi \left( \frac{a_1}{b_1}F + \frac{a_2}{b_2}F \right) &= \psi \left( \frac{a_1b_2 + b_1a_2}{b_1b_2}F \right) \\
&= \frac{i(a_1b_2 + b_1a_2)}{i(b_1b_2)}L \\
&= \frac{i(a_1)i(b_2) + i(b_1)i(a_2)}{i(b_1)i(b_2)}L \\
&= \frac{i(a_1)}{i(b_1)}L + \frac{i(a_2)}{i(b_2)}L \\
&= \psi \left( \frac{a_1}{b_1}F \right) + \psi \left( \frac{a_2}{b_2}F \right),
\end{align*}$$

and

$$\begin{align*}
\psi \left( \frac{a_1}{b_1}F \cdot \frac{a_2}{b_2}F \right) &= \psi \left( \frac{a_1a_2}{b_1b_2}F \right) \\
&= \frac{i(a_1a_2)}{i(b_1b_2)}L \\
&= \frac{i(a_1)i(b_2)}{i(b_1)i(b_2)}L \\
&= \frac{i(a_1)}{i(b_1)}L \cdot \frac{i(a_2)}{i(b_2)}L \\
&= \psi \left( \frac{a_1}{b_1}F \right) \cdot \psi \left( \frac{a_2}{b_2}F \right).
\end{align*}$$

Thus, $\psi$ is a ring homomorphism.$\big]$

3. $\psi$ is an isomorphism of $F$ with a subfield $\psi(F)$ of $L$ such that $\psi(a) = a, \forall a \in D$.

$\big[ (\because)$ Suppose that $\psi\left( \frac{a_1}{b_1}F \right) = \psi \left( \frac{a_2}{b_2}F \right)$. Then 

$$\begin{align*}
& \psi \left( \frac{a_1}{b_1}F \right) = \psi \left( \frac{a_2}{b_2}F \right) \\
\implies & \frac{i(a_1)}{i(b_1)}L = \frac{i(a_2)}{i(b_2)}L \\
\implies & i(a_1)i(b_2) = i(a_2)i(b_1) \\
\implies & a_1b_2 = a_2b_1 \\
\implies & \frac{a_1}{b_1}F = \frac{a_2}{b_2}F.
\end{align*}$$

Thus $\psi$ is one-to-one.

For $a \in D$, we have

$$\begin{align*}
\psi(a) &= \psi \left( \frac{a}{1}F \right) \\
&= \frac{i(a)}{i(1)}L \\
&= \frac{a}{1}L \\
&= a.
\end{align*}$$ 

Thus $\psi(F)$ is a subfield of $L$ containing $D$, and $\psi(a) = a, \forall a \in D$.$\big]$

Let $F$ and $L$ be quotient fields of $D$. By above claims, there exists a monomorphism $\psi: F \to L$ such that $\psi(a) = a, \forall a \in D$. We claim that $\psi$ is an isomorphism.

Let $x \in L$. Then $x = \frac{a}{b}L$ for some $a, b \in D$, so we have $\psi\left( \frac{a}{b}F \right) = \frac{i(a)}{i(b)}L = \frac{a}{b}L = x$. Thus $\psi$ is onto. Hence, $\psi$ is an isomorphism, so $F \cong L$.$\blacksquare \big]$
:::

# Reference
- John B. Fraleigh. (2004). A First Course in Abstract Algebra (7th ed.). Pearson.